/**
 * Level 1 Unit 1 Lesson 3 — Gemination (held consonants) and vowel length.
 * Comprehension-only: hear, reveal, discriminate. Duration features are
 * taught through focus-clip pairs and word pairs, with brief text cues.
 */

import type { Lesson } from '../../types'

export const lesson3GeminationVowels: Lesson = {
  id: 'l1u1l3',
  levelId: 'level1',
  unitId: 'unit1',
  title: 'Held sounds and long vowels',
  reviewSlots: 0,
  sprite: { file: 'audio/l1u1l3.mp3' },
  items: [
    {
      id: 'ka',
      manglish: 'ka',
      script: 'ക',
      meaning: 'the ka sound — a quick single k',
      kind: 'sound',
      articulation: {
        cue: 'Back of the tongue touches the soft palate. One quick release.',
      },
      audio: { slow: 'ka.slow', medium: 'ka.medium', normal: 'ka.normal', focus: ['ka.focus'] },
      tags: ['sound:geminate', 'level:1'],
    },
    {
      id: 'kka',
      manglish: 'kka',
      script: 'ക്ക',
      meaning: 'the kka sound — a held k',
      kind: 'sound',
      articulation: {
        cue: 'Same as ka, but hold the closure a beat longer before you release.',
      },
      audio: { slow: 'kka.slow', medium: 'kka.medium', normal: 'kka.normal', focus: ['kka.focus'] },
      notes: ['A doubled consonant means a held sound: kk, tt, pp.'],
      tags: ['sound:geminate', 'level:1'],
    },
    {
      id: 'aa',
      manglish: 'aa',
      script: 'ആ',
      meaning: 'the long aa sound',
      kind: 'sound',
      articulation: {
        cue: 'Mouth open, tongue low. Hold the vowel twice as long as a short a.',
      },
      audio: { slow: 'aa.slow', medium: 'aa.medium', normal: 'aa.normal', focus: ['aa.focus'] },
      notes: ['Long vowels are always written doubled: aa, ee, uu.'],
      tags: ['sound:vowelLength', 'level:1'],
    },
    {
      id: 'a',
      manglish: 'a',
      script: 'അ',
      meaning: 'the short a sound',
      kind: 'sound',
      articulation: {
        cue: 'Mouth open, tongue low. One quick beat.',
      },
      audio: { slow: 'a.slow', medium: 'a.medium', normal: 'a.normal', focus: ['a.focus'] },
      tags: ['sound:vowelLength', 'level:1'],
    },
    {
      id: 'ee',
      manglish: 'ee',
      script: 'ഈ',
      meaning: 'the long ee sound',
      kind: 'sound',
      articulation: {
        cue: 'Lips spread, tongue high at the front. Hold it long — like the ee in see.',
      },
      audio: { slow: 'ee.slow', medium: 'ee.medium', normal: 'ee.normal', focus: ['ee.focus'] },
      tags: ['sound:vowelLength', 'level:1'],
    },
    {
      id: 'i',
      manglish: 'i',
      script: 'ഇ',
      meaning: 'the short i sound',
      kind: 'sound',
      articulation: {
        cue: 'Lips spread, tongue high at the front. One quick beat — like the i in sit.',
      },
      audio: { slow: 'i.slow', medium: 'i.medium', normal: 'i.normal', focus: ['i.focus'] },
      tags: ['sound:vowelLength', 'level:1'],
    },
    {
      id: 'uu',
      manglish: 'uu',
      script: 'ഊ',
      meaning: 'the long uu sound',
      kind: 'sound',
      articulation: {
        cue: 'Lips rounded, tongue high at the back. Hold it long — like the oo in food.',
      },
      audio: { slow: 'uu.slow', medium: 'uu.medium', normal: 'uu.normal', focus: ['uu.focus'] },
      tags: ['sound:vowelLength', 'level:1'],
    },
    {
      id: 'u',
      manglish: 'u',
      script: 'ഉ',
      meaning: 'the short u sound',
      kind: 'sound',
      articulation: {
        cue: 'Lips rounded, tongue high at the back. One quick beat — like the u in put.',
      },
      audio: { slow: 'u.slow', medium: 'u.medium', normal: 'u.normal', focus: ['u.focus'] },
      tags: ['sound:vowelLength', 'level:1'],
    },
    {
      id: 'aadi',
      manglish: 'aadi',
      script: 'ആടി',
      meaning: 'swing',
      kind: 'word',
      pos: 'noun',
      audio: { slow: 'aadi.slow', medium: 'aadi.medium', normal: 'aadi.normal' },
      tags: ['sound:vowelLength', 'level:1'],
    },
    {
      id: 'adi',
      manglish: 'adi',
      script: 'അടി',
      meaning: 'hit',
      kind: 'word',
      pos: 'noun',
      audio: { slow: 'adi.slow', medium: 'adi.medium', normal: 'adi.normal' },
      tags: ['sound:vowelLength', 'level:1'],
    },
    {
      id: 'alla',
      manglish: 'alla',
      script: 'അല്ല',
      meaning: "isn't, not",
      kind: 'word',
      pos: 'particle',
      audio: { slow: 'alla.slow', medium: 'alla.medium', normal: 'alla.normal' },
      tags: ['sound:geminate', 'level:1'],
    },
    {
      id: 'pulli',
      manglish: 'puḷḷi',
      script: 'പുള്ളി',
      meaning: 'dot, spot',
      kind: 'word',
      pos: 'noun',
      acceptedInputs: ['pulli'],
      notes: ['Colloquially also "that person": aa puḷḷi, "that guy".'],
      audio: { slow: 'pulli.slow', medium: 'pulli.medium', normal: 'pulli.normal' },
      tags: ['sound:geminate', 'level:1'],
    },
    {
      id: 'puli',
      manglish: 'puli',
      script: 'പുലി',
      meaning: 'tiger, leopard',
      kind: 'word',
      pos: 'noun',
      audio: { slow: 'puli.slow', medium: 'puli.medium', normal: 'puli.normal' },
      tags: ['sound:geminate', 'level:1'],
    },
    {
      id: 'cheettha',
      manglish: 'cheettha',
      script: 'ചീത്ത',
      meaning: 'bad',
      kind: 'word',
      pos: 'adjective',
      audio: { slow: 'cheettha.slow', medium: 'cheettha.medium', normal: 'cheettha.normal' },
      tags: ['sound:geminate', 'sound:vowelLength', 'level:1'],
    },
  ],
  pairs: [
    { id: 'pair-kka-ka', aItemId: 'kka', bItemId: 'ka', segment: 'geminate', aClip: 'kka.focus', bClip: 'ka.focus' },
    { id: 'pair-aa-a', aItemId: 'aa', bItemId: 'a', segment: 'vowelLength', aClip: 'aa.focus', bClip: 'a.focus' },
    { id: 'pair-ee-i', aItemId: 'ee', bItemId: 'i', segment: 'vowelLength', aClip: 'ee.focus', bClip: 'i.focus' },
    { id: 'pair-uu-u', aItemId: 'uu', bItemId: 'u', segment: 'vowelLength', aClip: 'uu.focus', bClip: 'u.focus' },
    { id: 'pair-aadi-adi', aItemId: 'aadi', bItemId: 'adi', segment: 'vowelLength', aClip: 'aadi.normal', bClip: 'adi.normal' },
    { id: 'pair-pulli-puli', aItemId: 'pulli', bItemId: 'puli', segment: 'geminate', aClip: 'pulli.normal', bClip: 'puli.normal' },
  ],
  drills: [
    { kind: 'multipleChoice', itemId: 'aadi', distractors: ['adi', 'puli', 'cheettha'] },
    { kind: 'multipleChoice', itemId: 'adi', distractors: ['aadi', 'pulli', 'cheettha'] },
    { kind: 'multipleChoice', itemId: 'alla', distractors: ['pulli', 'puli', 'aadi'] },
    { kind: 'multipleChoice', itemId: 'pulli', distractors: ['puli', 'aadi', 'adi'] },
    { kind: 'multipleChoice', itemId: 'puli', distractors: ['pulli', 'adi', 'alla'] },
    { kind: 'multipleChoice', itemId: 'cheettha', distractors: ['aadi', 'pulli', 'puli'] },
    { kind: 'minimalPair', pairId: 'pair-kka-ka' },
    { kind: 'minimalPair', pairId: 'pair-aa-a' },
    { kind: 'minimalPair', pairId: 'pair-ee-i' },
    { kind: 'minimalPair', pairId: 'pair-uu-u' },
    { kind: 'minimalPair', pairId: 'pair-aadi-adi' },
    { kind: 'minimalPair', pairId: 'pair-pulli-puli' },
  ],
}
