/**
 * Level 2 Unit 3 — Tag questions and the -o particle (PLAN.md §5):
 * the small turn-taking moves that keep a conversation going.
 */

import type { Lesson } from '../../types'

export const lesson3Tags: Lesson = {
  id: 'l2u1l3',
  levelId: 'level2',
  unitId: 'unit3',
  title: 'Keeping the conversation going',
  reviewSlots: 2,
  sprite: { file: 'audio/l2u1l3.mp3' },
  items: [
    {
      id: 'kettiyo',
      manglish: 'ketto',
      script: 'കേട്ടോ',
      meaning: 'did you hear? (tag)',
      kind: 'expression',
      audio: { slow: 'kettiyo.slow', medium: 'kettiyo.medium', normal: 'kettiyo.normal' },
      tags: ['level:2'],
    },
    {
      id: 'kettayirunno',
      manglish: 'kettayirunno',
      meaning: 'did you hear? (about the past)',
      kind: 'expression',
      notes: ['No script here: the written form spells a long a that is short in speech.'],
      audio: { slow: 'kettayirunno.slow', medium: 'kettayirunno.medium', normal: 'kettayirunno.normal' },
      tags: ['level:2'],
    },
    {
      id: 'niyyo',
      manglish: 'neeyo',
      script: 'നീയോ',
      meaning: 'you? (question tag)',
      kind: 'expression',
      acceptedInputs: ['niyyo', 'neeyyo'],
      notes: ['The -o tag turns a word into a question: nee (you) becomes neeyo (you?).'],
      audio: { slow: 'niyyo.slow', medium: 'niyyo.medium', normal: 'niyyo.normal' },
      tags: ['level:2'],
    },
    {
      id: 'niyyum',
      manglish: 'neeyum',
      script: 'നീയും',
      meaning: 'you too?',
      kind: 'expression',
      acceptedInputs: ['niyyum', 'neeyyum'],
      notes: ['The -um adds "too": nee (you) becomes neeyum (you too?).'],
      audio: { slow: 'niyyum.slow', medium: 'niyyum.medium', normal: 'niyyum.normal' },
      tags: ['level:2'],
    },
    {
      id: 'sheriyalle',
      manglish: 'sheriyalle',
      script: 'ശെരിയല്ലേ',
      meaning: 'right? (isn’t it right)',
      kind: 'expression',
      audio: { slow: 'sheriyalle.slow', medium: 'sheriyalle.medium', normal: 'sheriyalle.normal' },
      tags: ['level:2'],
    },
    {
      id: 'chaaya-alle',
      manglish: 'chaaya alle',
      script: 'ചായ അല്ലേ',
      meaning: "it's tea, isn't it?",
      kind: 'sentence',
      segments: [
        { token: 'chaaya', gloss: 'tea' },
        { token: 'alle', gloss: "isn't it?" },
      ],
      audio: { slow: 'chaaya-alle.slow', medium: 'chaaya-alle.medium', normal: 'chaaya-alle.normal' },
      tags: ['level:2'],
    },
    {
      id: 'pokuva-alle',
      manglish: 'pokuva alle',
      script: 'പോകുവാ അല്ലേ',
      meaning: 'going, right?',
      kind: 'sentence',
      segments: [
        { token: 'pokuva', gloss: 'going' },
        { token: 'alle', gloss: 'right?' },
      ],
      audio: { slow: 'pokuva-alle.slow', medium: 'pokuva-alle.medium', normal: 'pokuva-alle.normal' },
      tags: ['level:2'],
    },
    {
      id: 'athu-alle',
      manglish: 'athu alle',
      script: 'അത് അല്ലേ',
      meaning: 'that, right?',
      kind: 'sentence',
      segments: [
        { token: 'athu', gloss: 'that' },
        { token: 'alle', gloss: 'right?' },
      ],
      audio: { slow: 'athu-alle.slow', medium: 'athu-alle.medium', normal: 'athu-alle.normal' },
      tags: ['level:2'],
    },
    {
      id: 'ippo-alle',
      manglish: 'ippo alle',
      script: 'ഇപ്പോ അല്ലേ',
      meaning: 'now, right?',
      kind: 'sentence',
      segments: [
        { token: 'ippo', gloss: 'now' },
        { token: 'alle', gloss: 'right?' },
      ],
      audio: { slow: 'ippo-alle.slow', medium: 'ippo-alle.medium', normal: 'ippo-alle.normal' },
      tags: ['level:2'],
    },
    {
      id: 'athu-sheri-alle',
      manglish: 'athu sheri alle',
      script: 'അത് ശെരി അല്ലേ',
      meaning: "that's correct, right?",
      kind: 'sentence',
      segments: [
        { token: 'athu', gloss: 'that' },
        { token: 'sheri', gloss: 'correct' },
        { token: 'alle', gloss: 'right?' },
      ],
      audio: { slow: 'athu-sheri-alle.slow', medium: 'athu-sheri-alle.medium', normal: 'athu-sheri-alle.normal' },
      tags: ['level:2'],
    },
    {
      id: 'niyyo-varuva',
      manglish: 'neeyum varunnundo',
      script: 'നീയും വരുന്നുണ്ടോ',
      meaning: 'are you coming too?',
      kind: 'sentence',
      acceptedInputs: ['niyyum varunundo', 'neeyyum varunundo'],
      segments: [
        { token: 'neeyum', gloss: 'you too?' },
        { token: 'varunnundo', gloss: 'is coming?' },
      ],
      audio: { slow: 'niyyo-varuva.slow', medium: 'niyyo-varuva.medium', normal: 'niyyo-varuva.normal' },
      tags: ['level:2'],
    },
  ],
  pairs: [],
  drills: [
    { kind: 'multipleChoice', itemId: 'kettiyo', distractors: ['kettayirunno', 'niyyum', 'athu-sheri-alle'] },
    { kind: 'multipleChoice', itemId: 'niyyo', distractors: ['niyyum', 'kettayirunno', 'sheriyalle'] },
    { kind: 'multipleChoice', itemId: 'niyyum', distractors: ['niyyo', 'kettayirunno', 'sheriyalle'] },
    {
      kind: 'sentenceBuilder',
      sentenceId: 'chaaya-alle',
      bank: ['chaaya', 'alle'],
      acceptedInputs: ['chaaya alle'],
    },
    {
      kind: 'sentenceBuilder',
      sentenceId: 'pokuva-alle',
      bank: ['pokuva', 'alle'],
      acceptedInputs: ['pokuva alle'],
    },
    {
      kind: 'sentenceBuilder',
      sentenceId: 'athu-alle',
      bank: ['athu', 'alle'],
      acceptedInputs: ['athu alle'],
    },
    {
      kind: 'sentenceBuilder',
      sentenceId: 'ippo-alle',
      bank: ['ippo', 'alle'],
      acceptedInputs: ['ippo alle'],
    },
    {
      kind: 'sentenceBuilder',
      sentenceId: 'niyyo-varuva',
      bank: ['neeyum', 'varunnundo'],
      acceptedInputs: ['niyyum varunundo', 'neeyyum varunundo'],
    },
    {
      kind: 'sentenceBuilder',
      sentenceId: 'athu-sheri-alle',
      bank: ['athu', 'sheri', 'alle'],
      acceptedInputs: ['athu sheri alle'],
    },
    { kind: 'typing', itemId: 'kettiyo' },
    { kind: 'typing', itemId: 'niyyo', acceptedInputs: ['niyyo'] },
  ],
}
