/**
 * Level 2 Unit 1 — The everyday present tense (PLAN.md §5). The -uva
 * pattern is made explicit: the casual verb chunks from Level 1 slot
 * into sentences immediately. Every sentence carries a word-by-word
 * breakdown.
 */

import type { Lesson } from '../../types'

export const lesson1UvaPattern: Lesson = {
  id: 'l2u1l1',
  levelId: 'level2',
  unitId: 'unit1',
  title: 'Everyday present tense',
  reviewSlots: 2,
  sprite: { file: 'audio/l2u1l1.mp3' },
  items: [
    {
      id: 'kudikkuva',
      manglish: 'kudikkuva',
      script: 'കുടിക്കുവാ',
      meaning: 'drinking (the everyday form)',
      kind: 'word',
      pos: 'verb',
      notes: ['The casual present: the -uva form is what you hear every day.'],
      audio: { slow: 'kudikkuva.slow', medium: 'kudikkuva.medium', normal: 'kudikkuva.normal' },
      tags: ['level:2'],
    },
    {
      id: 'varuva',
      manglish: 'varuva',
      script: 'വരുവാ',
      meaning: 'coming (the everyday form)',
      kind: 'word',
      pos: 'verb',
      audio: { slow: 'varuva.slow', medium: 'varuva.medium', normal: 'varuva.normal' },
      tags: ['level:2'],
    },
    {
      id: 'pokuva',
      manglish: 'pokuva',
      script: 'പോകുവാ',
      meaning: 'going (the everyday form)',
      kind: 'word',
      pos: 'verb',
      audio: { slow: 'pokuva.slow', medium: 'pokuva.medium', normal: 'pokuva.normal' },
      tags: ['level:2'],
    },
    {
      id: 'parayuva',
      manglish: 'parayuva',
      script: 'പറയുവാ',
      meaning: 'saying (the everyday form)',
      kind: 'word',
      pos: 'verb',
      audio: { slow: 'parayuva.slow', medium: 'parayuva.medium', normal: 'parayuva.normal' },
      tags: ['level:2'],
    },
    {
      id: 'kazhikkuva',
      manglish: 'kazhikkuva',
      script: 'കഴിക്കുവാ',
      meaning: 'eating (the everyday form)',
      kind: 'word',
      pos: 'verb',
      audio: { slow: 'kazhikkuva.slow', medium: 'kazhikkuva.medium', normal: 'kazhikkuva.normal' },
      tags: ['level:2'],
    },
    {
      id: 'nokkuva',
      manglish: 'nokkuva',
      script: 'നോക്കുവാ',
      meaning: 'looking (the everyday form)',
      kind: 'word',
      pos: 'verb',
      audio: { slow: 'nokkuva.slow', medium: 'nokkuva.medium', normal: 'nokkuva.normal' },
      tags: ['level:2'],
    },
    {
      id: 'njan-chaaya-kudikkuva',
      manglish: 'njaan chaaya kudikkuva',
      script: 'ഞാൻ ചായ കുടിക്കുവാ',
      meaning: 'I am drinking tea.',
      kind: 'sentence',
      segments: [
        { token: 'njaan', gloss: 'I' },
        { token: 'chaaya', gloss: 'tea' },
        { token: 'kudikkuva', gloss: 'drinking' },
      ],
      audio: { slow: 'njan-chaaya-kudikkuva.slow', medium: 'njan-chaaya-kudikkuva.medium', normal: 'njan-chaaya-kudikkuva.normal' },
      tags: ['level:2'],
    },
    {
      id: 'njan-pokuva',
      manglish: 'njaan pokuva',
      script: 'ഞാൻ പോകുവാ',
      meaning: 'I am going.',
      kind: 'sentence',
      segments: [
        { token: 'njaan', gloss: 'I' },
        { token: 'pokuva', gloss: 'going' },
      ],
      audio: { slow: 'njan-pokuva.slow', medium: 'njan-pokuva.medium', normal: 'njan-pokuva.normal' },
      tags: ['level:2'],
    },
    {
      id: 'njan-varuva',
      manglish: 'njaan varuva',
      script: 'ഞാൻ വരുവാ',
      meaning: 'I am coming.',
      kind: 'sentence',
      segments: [
        { token: 'njaan', gloss: 'I' },
        { token: 'varuva', gloss: 'coming' },
      ],
      audio: { slow: 'njan-varuva.slow', medium: 'njan-varuva.medium', normal: 'njan-varuva.normal' },
      tags: ['level:2'],
    },
    {
      id: 'avan-varuva',
      manglish: 'avan varuva',
      script: 'അവൻ വരുവാ',
      meaning: 'He is coming.',
      kind: 'sentence',
      segments: [
        { token: 'avan', gloss: 'he' },
        { token: 'varuva', gloss: 'coming' },
      ],
      audio: { slow: 'avan-varuva.slow', medium: 'avan-varuva.medium', normal: 'avan-varuva.normal' },
      tags: ['level:2'],
    },
    {
      id: 'avan-parayuva',
      manglish: 'avan parayuva',
      script: 'അവൻ പറയുവാ',
      meaning: 'He is saying.',
      kind: 'sentence',
      segments: [
        { token: 'avan', gloss: 'he' },
        { token: 'parayuva', gloss: 'saying' },
      ],
      audio: { slow: 'avan-parayuva.slow', medium: 'avan-parayuva.medium', normal: 'avan-parayuva.normal' },
      tags: ['level:2'],
    },
    {
      id: 'nammal-pokuva',
      manglish: 'nammaḷ pokuva',
      script: 'നമ്മൾ പോകുവാ',
      meaning: 'We are going.',
      kind: 'sentence',
      segments: [
        { token: 'nammaḷ', gloss: 'we' },
        { token: 'pokuva', gloss: 'going' },
      ],
      audio: { slow: 'nammal-pokuva.slow', medium: 'nammal-pokuva.medium', normal: 'nammal-pokuva.normal' },
      tags: ['level:2'],
    },
  ],
  pairs: [],
  drills: [
    { kind: 'multipleChoice', itemId: 'kudikkuva', distractors: ['varuva', 'pokuva', 'parayuva'] },
    { kind: 'multipleChoice', itemId: 'varuva', distractors: ['kudikkuva', 'kazhikkuva', 'nokkuva'] },
    { kind: 'multipleChoice', itemId: 'pokuva', distractors: ['varuva', 'nokkuva', 'parayuva'] },
    { kind: 'multipleChoice', itemId: 'parayuva', distractors: ['kudikkuva', 'pokuva', 'kazhikkuva'] },
    { kind: 'multipleChoice', itemId: 'kazhikkuva', distractors: ['kudikkuva', 'nokkuva', 'varuva'] },
    { kind: 'multipleChoice', itemId: 'nokkuva', distractors: ['pokuva', 'kazhikkuva', 'parayuva'] },
    {
      kind: 'sentenceBuilder',
      sentenceId: 'njan-chaaya-kudikkuva',
      bank: ['njaan', 'chaaya', 'kudikkuva'],
      acceptedInputs: ['njaan chaaya kudikkuva'],
    },
    {
      kind: 'sentenceBuilder',
      sentenceId: 'njan-pokuva',
      bank: ['njaan', 'pokuva'],
      acceptedInputs: ['njaan pokuva'],
    },
    {
      kind: 'sentenceBuilder',
      sentenceId: 'avan-varuva',
      bank: ['avan', 'varuva'],
      acceptedInputs: ['avan varuva'],
    },
    {
      kind: 'sentenceBuilder',
      sentenceId: 'nammal-pokuva',
      bank: ['nammaḷ', 'pokuva'],
      acceptedInputs: ['nammal pokuva'],
    },
    { kind: 'typing', itemId: 'njan-varuva', acceptedInputs: ['njan varuva'] },
    { kind: 'typing', itemId: 'avan-parayuva', acceptedInputs: ['avan parayuva'] },
  ],
}
