/**
 * Level 2 Unit 1 — The everyday present tense (PLAN.md §5). The -uva
 * pattern is made explicit: the casual verb chunks from Level 1 slot
 * into sentences immediately. Every sentence carries a word-by-word
 * breakdown.
 */

import type { Lesson } from '../../types'

export const lesson1UvaPattern: Lesson = {
  id: 'l2u1l1',
  levelId: 'level2',
  unitId: 'unit1',
  title: 'Everyday present tense',
  reviewSlots: 2,
  sprite: { file: 'audio/l2u1l1.mp3' },
  items: [
    {
      id: 'kudikkuva',
      manglish: 'kudikkuva',
      script: 'കുടിക്കുവാ',
      meaning: 'drinking (right now)',
      kind: 'word',
      pos: 'verb',
      notes: ['The casual present: the -uva form is what you hear every day.'],
      audio: { slow: 'kudikkuva.slow', medium: 'kudikkuva.medium', normal: 'kudikkuva.normal' },
      tags: ['level:2'],
    },
    {
      id: 'varuva',
      manglish: 'varuva',
      script: 'വരുവാ',
      meaning: 'coming (right now)',
      kind: 'word',
      pos: 'verb',
      audio: { slow: 'varuva.slow', medium: 'varuva.medium', normal: 'varuva.normal' },
      tags: ['level:2'],
    },
    {
      id: 'pokuva',
      manglish: 'pokuva',
      script: 'പോകുവാ',
      meaning: 'going (right now)',
      kind: 'word',
      pos: 'verb',
      audio: { slow: 'pokuva.slow', medium: 'pokuva.medium', normal: 'pokuva.normal' },
      tags: ['level:2'],
    },
    {
      id: 'parayuva',
      manglish: 'parayuva',
      script: 'പറയുവാ',
      meaning: 'saying (right now)',
      kind: 'word',
      pos: 'verb',
      audio: { slow: 'parayuva.slow', medium: 'parayuva.medium', normal: 'parayuva.normal' },
      tags: ['level:2'],
    },
    {
      id: 'kazhikkuva',
      manglish: 'kazhikkuva',
      script: 'കഴിക്കുവാ',
      meaning: 'eating (right now)',
      kind: 'word',
      pos: 'verb',
      audio: { slow: 'kazhikkuva.slow', medium: 'kazhikkuva.medium', normal: 'kazhikkuva.normal' },
      tags: ['level:2'],
    },
    {
      id: 'nokkuva',
      manglish: 'nokkuva',
      script: 'നോക്കുവാ',
      meaning: 'looking (right now)',
      kind: 'word',
      pos: 'verb',
      audio: { slow: 'nokkuva.slow', medium: 'nokkuva.medium', normal: 'nokkuva.normal' },
      tags: ['level:2'],
    },
    {
      id: 'kudikkum',
      manglish: 'kudikkum',
      script: 'കുടിക്കും',
      meaning: 'drinks (sometimes, the habit)',
      kind: 'word',
      pos: 'verb',
      notes: ['The -um form says what happens sometimes: kudikkum is "drinks", kudikkuva is "is drinking".'],
      audio: { slow: 'kudikkum.slow', medium: 'kudikkum.medium', normal: 'kudikkum.normal' },
      tags: ['level:2'],
    },
    {
      id: 'nokkum',
      manglish: 'nokkum',
      script: 'നോക്കും',
      meaning: 'looks (sometimes, the habit)',
      kind: 'word',
      pos: 'verb',
      notes: ['The -um form says what happens sometimes: nokkum is "looks", nokkuva is "looking".'],
      audio: { slow: 'nokkum.slow', medium: 'nokkum.medium', normal: 'nokkum.normal' },
      tags: ['level:2'],
    },
    {
      id: 'veedu',
      manglish: 'veedu',
      script: 'വീട്',
      meaning: 'home, house',
      kind: 'word',
      pos: 'noun',
      audio: { slow: 'veedu.slow', medium: 'veedu.medium', normal: 'veedu.normal' },
      tags: ['level:2'],
    },
    {
      id: 'njan-chaaya-kudikkuva',
      manglish: 'njan chaaya kudikkuva',
      script: 'ഞാൻ ചായ കുടിക്കുവാ',
      meaning: 'I am drinking tea.',
      kind: 'sentence',
      segments: [
        { token: 'njan', gloss: 'I' },
        { token: 'chaaya', gloss: 'tea' },
        { token: 'kudikkuva', gloss: 'drinking' },
      ],
      audio: { slow: 'njan-chaaya-kudikkuva.slow', medium: 'njan-chaaya-kudikkuva.medium', normal: 'njan-chaaya-kudikkuva.normal' },
      tags: ['level:2'],
    },
    {
      id: 'njan-pokuva',
      manglish: 'njan pokuva',
      script: 'ഞാൻ പോകുവാ',
      meaning: 'I am going.',
      kind: 'sentence',
      segments: [
        { token: 'njan', gloss: 'I' },
        { token: 'pokuva', gloss: 'going' },
      ],
      audio: { slow: 'njan-pokuva.slow', medium: 'njan-pokuva.medium', normal: 'njan-pokuva.normal' },
      tags: ['level:2'],
    },
    {
      id: 'njan-varuva',
      manglish: 'njan varuva',
      script: 'ഞാൻ വരുവാ',
      meaning: 'I am coming.',
      kind: 'sentence',
      segments: [
        { token: 'njan', gloss: 'I' },
        { token: 'varuva', gloss: 'coming' },
      ],
      audio: { slow: 'njan-varuva.slow', medium: 'njan-varuva.medium', normal: 'njan-varuva.normal' },
      tags: ['level:2'],
    },
    {
      id: 'avan-varuva',
      manglish: 'avan varuva',
      script: 'അവൻ വരുവാ',
      meaning: 'He is coming.',
      kind: 'sentence',
      segments: [
        { token: 'avan', gloss: 'he' },
        { token: 'varuva', gloss: 'coming' },
      ],
      audio: { slow: 'avan-varuva.slow', medium: 'avan-varuva.medium', normal: 'avan-varuva.normal' },
      tags: ['level:2'],
    },
    {
      id: 'avan-parayuva',
      manglish: 'avan parayuva',
      script: 'അവൻ പറയുവാ',
      meaning: 'He is saying.',
      kind: 'sentence',
      segments: [
        { token: 'avan', gloss: 'he' },
        { token: 'parayuva', gloss: 'saying' },
      ],
      audio: { slow: 'avan-parayuva.slow', medium: 'avan-parayuva.medium', normal: 'avan-parayuva.normal' },
      tags: ['level:2'],
    },
    {
      id: 'nammal-pokuva',
      manglish: 'nammaḷ pokuva',
      script: 'നമ്മൾ പോകുവാ',
      meaning: 'We are going.',
      kind: 'sentence',
      segments: [
        { token: 'nammaḷ', gloss: 'we' },
        { token: 'pokuva', gloss: 'going' },
      ],
      audio: { slow: 'nammal-pokuva.slow', medium: 'nammal-pokuva.medium', normal: 'nammal-pokuva.normal' },
      tags: ['level:2'],
    },
    {
      id: 'njan-chaaya-kudikkum',
      manglish: 'njan chaaya kudikkum',
      script: 'ഞാൻ ചായ കുടിക്കും',
      meaning: 'I drink tea sometimes.',
      kind: 'sentence',
      segments: [
        { token: 'njan', gloss: 'I' },
        { token: 'chaaya', gloss: 'tea' },
        { token: 'kudikkum', gloss: 'drink (sometimes)' },
      ],
      audio: { slow: 'njan-chaaya-kudikkum.slow', medium: 'njan-chaaya-kudikkum.medium', normal: 'njan-chaaya-kudikkum.normal' },
      tags: ['level:2'],
    },
    {
      id: 'njan-veettil-pokuva',
      manglish: 'njan veettil pokuva',
      script: 'ഞാൻ വീട്ടിൽ പോകുവാ',
      meaning: 'I am going home.',
      kind: 'sentence',
      notes: ['Sandhi: veedu + il joins into veettil, the d doubles before -il.'],
      segments: [
        { token: 'njan', gloss: 'I' },
        { token: 'veettil', gloss: 'home (veedu + il, to home)' },
        { token: 'pokuva', gloss: 'going' },
      ],
      audio: { slow: 'njan-veettil-pokuva.slow', medium: 'njan-veettil-pokuva.medium', normal: 'njan-veettil-pokuva.normal' },
      tags: ['level:2'],
    },
  ],
  pairs: [],
  drills: [
    { kind: 'multipleChoice', itemId: 'kudikkuva', distractors: ['kudikkum', 'varuva', 'pokuva'] },
    { kind: 'multipleChoice', itemId: 'kudikkum', distractors: ['kudikkuva', 'varuva', 'parayuva'] },
    { kind: 'multipleChoice', itemId: 'veedu', distractors: ['kudikkum', 'varuva', 'nokkuva'] },
    { kind: 'multipleChoice', itemId: 'varuva', distractors: ['kudikkuva', 'kazhikkuva', 'nokkuva'] },
    { kind: 'multipleChoice', itemId: 'pokuva', distractors: ['varuva', 'nokkuva', 'parayuva'] },
    { kind: 'multipleChoice', itemId: 'parayuva', distractors: ['kudikkuva', 'pokuva', 'kazhikkuva'] },
    { kind: 'multipleChoice', itemId: 'kazhikkuva', distractors: ['kudikkuva', 'nokkuva', 'varuva'] },
    { kind: 'multipleChoice', itemId: 'nokkuva', distractors: ['pokuva', 'kazhikkuva', 'parayuva'] },
    { kind: 'multipleChoice', itemId: 'nokkum', distractors: ['nokkuva', 'kudikkum', 'varuva'] },
    {
      kind: 'sentenceBuilder',
      sentenceId: 'njan-chaaya-kudikkuva',
      bank: ['njan', 'chaaya', 'kudikkuva'],
      acceptedInputs: ['njan chaaya kudikkuva'],
    },
    {
      kind: 'sentenceBuilder',
      sentenceId: 'njan-chaaya-kudikkum',
      bank: ['njan', 'chaaya', 'kudikkum'],
      acceptedInputs: ['njan chaaya kudikkum'],
    },
    {
      kind: 'sentenceBuilder',
      sentenceId: 'njan-veettil-pokuva',
      bank: ['njan', 'veettil', 'pokuva'],
      acceptedInputs: ['njan veettil pokuva'],
    },
    {
      kind: 'sentenceBuilder',
      sentenceId: 'njan-pokuva',
      bank: ['njan', 'pokuva'],
      acceptedInputs: ['njan pokuva'],
    },
    {
      kind: 'sentenceBuilder',
      sentenceId: 'avan-varuva',
      bank: ['avan', 'varuva'],
      acceptedInputs: ['avan varuva'],
    },
    {
      kind: 'sentenceBuilder',
      sentenceId: 'nammal-pokuva',
      bank: ['nammaḷ', 'pokuva'],
      acceptedInputs: ['nammal pokuva'],
    },
    { kind: 'typing', itemId: 'njan-varuva', acceptedInputs: ['njan varuva'] },
    { kind: 'typing', itemId: 'avan-parayuva', acceptedInputs: ['avan parayuva'] },
  ],
}
