/**
 * Level 2 Unit 5 — The third-person ladder (PLAN.md §5): talking
 * about a man you know, a man you respect, and a person you do not
 * know at all. The pronoun ladder from Level 1 extends to "he".
 */

import type { Lesson } from '../../types'

export const lesson5ThirdPerson: Lesson = {
  id: 'l2u1l5',
  levelId: 'level2',
  unitId: 'unit5',
  title: 'Talking about him',
  reviewSlots: 2,
  sprite: { file: 'audio/l2u1l5.mp3' },
  items: [
    {
      id: 'ayaal',
      manglish: 'ayaaḷ',
      script: 'അയാൾ',
      meaning: 'he (casual, distant)',
      kind: 'word',
      pos: 'pronoun',
      notes: [
        'For a man who is not close, and usually not in the room.',
        'The final chillu keeps its diacritic: ayaaḷ.',
      ],
      audio: { slow: 'ayaal.slow', medium: 'ayaal.medium', normal: 'ayaal.normal' },
      tags: ['level:2'],
    },
    {
      id: 'iyaal',
      manglish: 'iyaaḷ',
      script: 'ഇയാൾ',
      meaning: 'this person (neutral)',
      kind: 'word',
      pos: 'pronoun',
      notes: ['Points at someone nearby without saying he or she.'],
      audio: { slow: 'iyaal.slow', medium: 'iyaal.medium', normal: 'iyaal.normal' },
      tags: ['level:2'],
    },
    {
      id: 'addheham',
      manglish: 'addheham',
      script: 'അദ്ദേഹം',
      meaning: 'he (respectful)',
      kind: 'word',
      pos: 'pronoun',
      notes: ['For elders, bosses, and people you respect.'],
      audio: { slow: 'addheham.slow', medium: 'addheham.medium', normal: 'addheham.normal' },
      tags: ['level:2'],
    },
    {
      id: 'avar',
      manglish: 'avar',
      script: 'അവർ',
      meaning: 'they; polite he or she',
      kind: 'word',
      pos: 'pronoun',
      notes: ['Avar is "they", and doubles as the polite way to say he or she.'],
      audio: { slow: 'avar.slow', medium: 'avar.medium', normal: 'avar.normal' },
      tags: ['level:2'],
    },
    {
      id: 'ayaal-varunnundo',
      manglish: 'ayaaḷ ingott varunnundo',
      script: 'അയാൾ ഇങ്ങോട്ട് വരുന്നുണ്ടോ',
      meaning: 'is he coming here? (casual)',
      kind: 'sentence',
      acceptedInputs: ['ayaal ingott varunundo'],
      segments: [
        { token: 'ayaaḷ', gloss: 'he (casual, distant)' },
        { token: 'ingott', gloss: 'here (toward me)' },
        { token: 'varunnundo', gloss: 'is coming?' },
      ],
      audio: { slow: 'ayaal-varunnundo.slow', medium: 'ayaal-varunnundo.medium', normal: 'ayaal-varunnundo.normal' },
      tags: ['level:2'],
    },
    {
      id: 'addheham-varunnundo',
      manglish: 'addheham varunnundo',
      script: 'അദ്ദേഹം വരുന്നുണ്ടോ',
      meaning: 'is he coming? (respectful)',
      kind: 'sentence',
      segments: [
        { token: 'addheham', gloss: 'he (respectful)' },
        { token: 'varunnundo', gloss: 'is coming?' },
      ],
      audio: { slow: 'addheham-varunnundo.slow', medium: 'addheham-varunnundo.medium', normal: 'addheham-varunnundo.normal' },
      tags: ['level:2'],
    },
    {
      id: 'ayaal-pokunnundo',
      manglish: 'ayaaḷ pokunnundo',
      script: 'അയാൾ പോകുന്നുണ്ടോ',
      meaning: 'is he going? (casual)',
      kind: 'sentence',
      segments: [
        { token: 'ayaaḷ', gloss: 'he (casual, distant)' },
        { token: 'pokunnundo', gloss: 'is going?' },
      ],
      audio: { slow: 'ayaal-pokunnundo.slow', medium: 'ayaal-pokunnundo.medium', normal: 'ayaal-pokunnundo.normal' },
      tags: ['level:2'],
    },
    {
      id: 'addheham-pokunnundo',
      manglish: 'addheham pokunnundo',
      script: 'അദ്ദേഹം പോകുന്നുണ്ടോ',
      meaning: 'is he going? (respectful)',
      kind: 'sentence',
      segments: [
        { token: 'addheham', gloss: 'he (respectful)' },
        { token: 'pokunnundo', gloss: 'is going?' },
      ],
      audio: { slow: 'addheham-pokunnundo.slow', medium: 'addheham-pokunnundo.medium', normal: 'addheham-pokunnundo.normal' },
      tags: ['level:2'],
    },
  ],
  pairs: [],
  drills: [
    { kind: 'multipleChoice', itemId: 'ayaal', distractors: ['iyaal', 'addheham', 'avar'] },
    { kind: 'multipleChoice', itemId: 'iyaal', distractors: ['ayaal', 'addheham', 'avar'] },
    { kind: 'multipleChoice', itemId: 'addheham', distractors: ['ayaal', 'iyaal', 'avar'] },
    { kind: 'multipleChoice', itemId: 'avar', distractors: ['ayaal', 'iyaal', 'addheham'] },
    {
      kind: 'sentenceBuilder',
      sentenceId: 'ayaal-varunnundo',
      bank: ['ayaaḷ', 'ingott', 'varunnundo'],
      acceptedInputs: ['ayaal ingott varunundo'],
    },
    {
      kind: 'sentenceBuilder',
      sentenceId: 'addheham-varunnundo',
      bank: ['addheham', 'varunnundo'],
      acceptedInputs: ['addheham varunundo'],
    },
    {
      kind: 'sentenceBuilder',
      sentenceId: 'ayaal-pokunnundo',
      bank: ['ayaaḷ', 'pokunnundo'],
      acceptedInputs: ['ayal pokunundo'],
    },
    { kind: 'typing', itemId: 'ayaal', acceptedInputs: ['ayaal'] },
    { kind: 'typing', itemId: 'addheham', acceptedInputs: ['addheham'] },
  ],
}
