/**
 * Level 2 Unit 5 — The a/i distance paradigm (PLAN.md §5): a- words
 * point AWAY, i- words point NEAR. Same consonant frame, one vowel
 * decides the distance. Taught before the third-person ladder, so
 * iyaaḷ/ayaaḷ read as the familiar i-/a- plus -aaḷ.
 *
 * The id still says l3u2l1: the lesson was authored in Level 3 and the
 * native-speaker ruling moved it here. Lesson ids are learner-progress
 * and audio-manifest keys, so it is kept stable (PLAN.md §11).
 */

import type { Lesson } from '../../types'

export const lesson1Distance: Lesson = {
  id: 'l3u2l1',
  levelId: 'level2',
  unitId: 'unit5',
  title: 'Near and far: a vs i',
  reviewSlots: 2,
  sprite: { file: 'audio/l3u2l1.mp3' },
  items: [
    {
      id: 'avide',
      manglish: 'avide',
      script: 'അവിടെ',
      meaning: 'there',
      kind: 'word',
      pos: 'adverb',
      notes: ['a- points away: avide, there.'],
      audio: { slow: 'avide.slow', medium: 'avide.medium', normal: 'avide.normal' },
      tags: ['level:2'],
    },
    {
      id: 'ivide',
      manglish: 'ivide',
      script: 'ഇവിടെ',
      meaning: 'here',
      kind: 'word',
      pos: 'adverb',
      notes: ['i- points near: ivide, here.'],
      audio: { slow: 'ivide.slow', medium: 'ivide.medium', normal: 'ivide.normal' },
      tags: ['level:2'],
    },
    {
      id: 'ivan',
      manglish: 'ivan',
      script: 'ഇവൻ',
      meaning: 'this guy (near)',
      kind: 'word',
      pos: 'pronoun',
      notes: ['avan is that guy (away); ivan is this guy (near).'],
      audio: { slow: 'ivan.slow', medium: 'ivan.medium', normal: 'ivan.normal' },
      tags: ['level:2'],
    },
    {
      id: 'ival',
      manglish: 'ivaḷ',
      script: 'ഇവൾ',
      meaning: 'this girl (near)',
      kind: 'word',
      pos: 'pronoun',
      acceptedInputs: ['ival'],
      notes: ['avaḷ is that girl (away); ivaḷ is this girl (near).'],
      audio: { slow: 'ival.slow', medium: 'ival.medium', normal: 'ival.normal' },
      tags: ['level:2'],
    },
    {
      id: 'angane',
      manglish: 'angane',
      script: 'അങ്ങനെ',
      meaning: 'like that',
      kind: 'word',
      pos: 'adverb',
      notes: ['a- points away: angane, like that.'],
      audio: { slow: 'angane.slow', medium: 'angane.medium', normal: 'angane.normal' },
      tags: ['level:2'],
    },
    {
      id: 'ingane',
      manglish: 'ingane',
      script: 'ഇങ്ങനെ',
      meaning: 'like this',
      kind: 'word',
      pos: 'adverb',
      notes: ['i- points near: ingane, like this.'],
      audio: { slow: 'ingane.slow', medium: 'ingane.medium', normal: 'ingane.normal' },
      tags: ['level:2'],
    },
    {
      id: 'appo',
      manglish: 'appo',
      script: 'അപ്പോ',
      meaning: 'then; so',
      kind: 'word',
      pos: 'adverb',
      notes: ['a- points away: appo, then. Also the casual "so": appo sheri, so okay.'],
      audio: { slow: 'appo.slow', medium: 'appo.medium', normal: 'appo.normal' },
      tags: ['level:2'],
    },
    {
      id: 'ippo',
      manglish: 'ippo',
      script: 'ഇപ്പോ',
      meaning: 'now',
      kind: 'word',
      pos: 'adverb',
      notes: ['i- points near: ippo, now.'],
      audio: { slow: 'ippo.slow', medium: 'ippo.medium', normal: 'ippo.normal' },
      tags: ['level:2'],
    },
    {
      id: 'njan-angott-varuva',
      manglish: 'njan angott varuva',
      script: 'ഞാൻ അങ്ങോട്ട് വരുവാ',
      meaning: 'I am coming there.',
      kind: 'sentence',
      segments: [
        { token: 'njan', gloss: 'I' },
        { token: 'angott', gloss: 'there (toward that place)' },
        { token: 'varuva', gloss: 'coming' },
      ],
      audio: { slow: 'njan-angott-varuva.slow', medium: 'njan-angott-varuva.medium', normal: 'njan-angott-varuva.normal' },
      tags: ['level:2'],
    },
    {
      id: 'njangal',
      manglish: 'njangaḷ',
      script: 'ഞങ്ങൾ',
      meaning: 'we (not you)',
      kind: 'word',
      pos: 'pronoun',
      acceptedInputs: ['njangal'],
      notes: ['njangaḷ is me and them, without the person you are talking to.'],
      audio: { slow: 'njangal.slow', medium: 'njangal.medium', normal: 'njangal.normal' },
      tags: ['level:2'],
    },
    {
      id: 'ente',
      manglish: 'ente',
      script: 'എന്റെ',
      meaning: 'my',
      kind: 'word',
      pos: 'pronoun',
      notes: ['It means my, and attaches to anything: ente chaaya, my tea.'],
      audio: { slow: 'ente.slow', medium: 'ente.medium', normal: 'ente.normal' },
      tags: ['level:2'],
    },
    {
      id: 'ninte',
      manglish: 'ninte',
      script: 'നിന്റെ',
      meaning: 'your (casual)',
      kind: 'word',
      pos: 'pronoun',
      notes: ['It means your (casual): ninte chaaya, your tea.'],
      audio: { slow: 'ninte.slow', medium: 'ninte.medium', normal: 'ninte.normal' },
      tags: ['level:2'],
    },
  ],
  pairs: [],
  drills: [
    { kind: 'multipleChoice', itemId: 'avide', distractors: ['ivide', 'angane', 'appo'] },
    { kind: 'multipleChoice', itemId: 'ivide', distractors: ['avide', 'ingane', 'ippo'] },
    { kind: 'multipleChoice', itemId: 'ivan', distractors: ['ival', 'angane', 'ente'] },
    { kind: 'multipleChoice', itemId: 'ival', distractors: ['ivan', 'ingane', 'ninte'] },
    { kind: 'multipleChoice', itemId: 'angane', distractors: ['ingane', 'avide', 'appo'] },
    { kind: 'multipleChoice', itemId: 'ingane', distractors: ['angane', 'ivide', 'ippo'] },
    { kind: 'multipleChoice', itemId: 'appo', distractors: ['ippo', 'avide', 'angane'] },
    { kind: 'multipleChoice', itemId: 'ippo', distractors: ['appo', 'ivide', 'ingane'] },
    { kind: 'multipleChoice', itemId: 'njan-angott-varuva', distractors: ['avide', 'ivide', 'ippo'] },
    {
      kind: 'sentenceBuilder',
      sentenceId: 'njan-angott-varuva',
      bank: ['njan', 'angott', 'varuva'],
      acceptedInputs: ['njan angott varuva'],
    },
    { kind: 'multipleChoice', itemId: 'njangal', distractors: ['ente', 'ninte', 'ivan'] },
    { kind: 'multipleChoice', itemId: 'ente', distractors: ['ninte', 'njangal', 'ival'] },
    { kind: 'typing', itemId: 'ivide', acceptedInputs: ['ivide'] },
    { kind: 'typing', itemId: 'ippo', acceptedInputs: ['ippo'] },
  ],
}
