import type { Lesson } from '../types';

/**
 * Level 1 Unit 1 Lesson 3 — gemination and vowel length.
 * Both are duration features, so they get held-sound drills and duration
 * cues instead of tongue diagrams (PLAN.md §4). Comprehension-only.
 */
export const l1u1l3: Lesson = {
  id: 'l1u1l3',
  levelId: 'l1',
  unitId: 'l1u1',
  title: 'Doubled consonants and long vowels',
  comprehensionOnly: true,
  items: [
    {
      id: 'ippo',
      manglish: 'ippo',
      script: 'ഇപ്പോ',
      meaning: 'now',
      kind: 'word',
      audio: {
        slow: 'l1u1l3_ippo_slow',
        medium: 'l1u1l3_ippo_medium',
        normal: 'l1u1l3_ippo_normal',
        focus: ['l1u1l3_ippo_focus'],
      },
      acceptedInputs: ['ippo'],
      notes: ['Hold the pp twice as long as a single p. The doubled consonant is what makes the word.'],
      tags: ['sound:geminate'],
    },
    {
      id: 'nalla',
      manglish: 'nalla',
      script: 'നല്ല',
      meaning: 'good',
      kind: 'word',
      audio: {
        slow: 'l1u1l3_nalla_slow',
        medium: 'l1u1l3_nalla_medium',
        normal: 'l1u1l3_nalla_normal',
        focus: ['l1u1l3_nalla_focus'],
      },
      acceptedInputs: ['nalla'],
      notes: ['Hold the ll in the middle for a full beat longer than a single l.'],
      tags: ['sound:geminate'],
    },
    {
      id: 'kallam',
      manglish: 'kaḷḷam',
      script: 'കള്ളം',
      meaning: 'a lie',
      kind: 'word',
      audio: {
        slow: 'l1u1l3_kallam_slow',
        medium: 'l1u1l3_kallam_medium',
        normal: 'l1u1l3_kallam_normal',
        focus: ['l1u1l3_kallam_focus'],
      },
      acceptedInputs: ['kallam'],
      notes: ['Hold the ḷḷ twice as long as the single ḷ in kaḷam.'],
      tags: ['sound:geminate'],
    },
    {
      id: 'kalam',
      manglish: 'kaḷam',
      script: 'കളം',
      meaning: 'arena; field',
      kind: 'word',
      audio: {
        slow: 'l1u1l3_kalam_slow',
        medium: 'l1u1l3_kalam_medium',
        normal: 'l1u1l3_kalam_normal',
      },
      acceptedInputs: ['kalam'],
      tags: [],
    },
    {
      id: 'vaaram',
      manglish: 'vaaram',
      script: 'വാരം',
      meaning: 'week',
      kind: 'word',
      audio: {
        slow: 'l1u1l3_vaaram_slow',
        medium: 'l1u1l3_vaaram_medium',
        normal: 'l1u1l3_vaaram_normal',
        focus: ['l1u1l3_vaaram_focus'],
      },
      acceptedInputs: ['vaaram'],
      notes: ['Stretch the aa twice as long as the a in varam.'],
      tags: ['sound:vowel-length'],
    },
    {
      id: 'varam',
      manglish: 'varam',
      script: 'വരം',
      meaning: 'boon; blessing',
      kind: 'word',
      audio: {
        slow: 'l1u1l3_varam_slow',
        medium: 'l1u1l3_varam_medium',
        normal: 'l1u1l3_varam_normal',
      },
      acceptedInputs: ['varam'],
      tags: [],
    },
    {
      id: 'kudi',
      manglish: 'kudi',
      script: 'കുടി',
      meaning: 'a drink; drinking',
      kind: 'word',
      audio: {
        slow: 'l1u1l3_kudi_slow',
        medium: 'l1u1l3_kudi_medium',
        normal: 'l1u1l3_kudi_normal',
      },
      acceptedInputs: ['kudi'],
      tags: [],
    },
    {
      id: 'kuudi',
      manglish: 'kuudi',
      script: 'കൂടി',
      meaning: 'together; also',
      kind: 'word',
      audio: {
        slow: 'l1u1l3_kuudi_slow',
        medium: 'l1u1l3_kuudi_medium',
        normal: 'l1u1l3_kuudi_normal',
        focus: ['l1u1l3_kuudi_focus'],
      },
      acceptedInputs: ['kuudi'],
      notes: ['Stretch the uu twice as long as the u in kudi.'],
      tags: ['sound:vowel-length'],
    },
  ],
  minimalPairs: [
    {
      id: 'l1u1-p-kallam-kalam',
      aItemId: 'kallam',
      bItemId: 'kalam',
      segment: 'geminate',
      aClip: 'l1u1l3_kallam_normal',
      bClip: 'l1u1l3_kalam_normal',
    },
    {
      id: 'l1u1-p-varam-vaaram',
      aItemId: 'varam',
      bItemId: 'vaaram',
      segment: 'vowelLength',
      aClip: 'l1u1l3_varam_normal',
      bClip: 'l1u1l3_vaaram_normal',
    },
    {
      id: 'l1u1-p-kudi-kuudi',
      aItemId: 'kudi',
      bItemId: 'kuudi',
      segment: 'vowelLength',
      aClip: 'l1u1l3_kudi_normal',
      bClip: 'l1u1l3_kuudi_normal',
    },
  ],
  drills: [
    { kind: 'multipleChoice', itemId: 'ippo', distractors: ['good', 'arena; field', 'boon; blessing'] },
    { kind: 'multipleChoice', itemId: 'nalla', distractors: ['now', 'a lie', 'together; also'] },
    { kind: 'multipleChoice', itemId: 'kallam', distractors: ['arena; field', 'week', 'a drink; drinking'] },
    { kind: 'multipleChoice', itemId: 'kalam', distractors: ['a lie', 'boon; blessing', 'together; also'] },
    { kind: 'multipleChoice', itemId: 'vaaram', distractors: ['boon; blessing', 'now', 'a drink; drinking'] },
    { kind: 'multipleChoice', itemId: 'varam', distractors: ['week', 'good', 'together; also'] },
    { kind: 'multipleChoice', itemId: 'kudi', distractors: ['together; also', 'arena; field', 'now'] },
    { kind: 'multipleChoice', itemId: 'kuudi', distractors: ['a drink; drinking', 'week', 'a lie'] },
    { kind: 'minimalPair', pairId: 'l1u1-p-kallam-kalam' },
    { kind: 'minimalPair', pairId: 'l1u1-p-varam-vaaram' },
    { kind: 'minimalPair', pairId: 'l1u1-p-kudi-kuudi' },
  ],
  reviewSlots: 0,
  spriteId: 'l1u1l3',
};
