import type { Lesson } from '../types';

/**
 * Level 1 Unit 1 Lesson 2 — the three t-sounds.
 * Dental (th, tongue at the teeth), retroflex (t, tongue curled back),
 * and alveolar (ṟ, tongue tapping the gum ridge). Comprehension-only.
 */
export const l1u1l2: Lesson = {
  id: 'l1u1l2',
  levelId: 'l1',
  unitId: 'l1u1',
  title: 'The three t-sounds',
  comprehensionOnly: true,
  items: [
    {
      id: 'patthu',
      manglish: 'patthu',
      script: 'പത്ത്',
      meaning: 'ten',
      kind: 'word',
      articulation: {
        cue: 'Press the tongue tip against the back of the upper front teeth and release. Hold the contact for the doubled th.',
      },
      audio: {
        slow: 'l1u1l2_patthu_slow',
        medium: 'l1u1l2_patthu_medium',
        normal: 'l1u1l2_patthu_normal',
        focus: ['l1u1l2_patthu_focus'],
      },
      acceptedInputs: ['patthu'],
      tags: ['sound:coronal'],
    },
    {
      id: 'paattu',
      manglish: 'paattu',
      script: 'പാട്ട്',
      meaning: 'song',
      kind: 'word',
      articulation: {
        cue: 'Curl the tongue tip back so its underside touches the roof just behind the gum ridge, hold for the doubled tt, then release.',
      },
      audio: {
        slow: 'l1u1l2_paattu_slow',
        medium: 'l1u1l2_paattu_medium',
        normal: 'l1u1l2_paattu_normal',
        focus: ['l1u1l2_paattu_focus'],
      },
      acceptedInputs: ['paattu'],
      tags: ['sound:coronal'],
    },
    {
      id: 'kaarru',
      manglish: 'kaaṟṟu',
      script: 'കാറ്റ്',
      meaning: 'wind',
      kind: 'word',
      articulation: {
        cue: 'Tap the tongue tip on the gum ridge just behind the upper teeth, like the tt in "butter", and hold the tap for the doubled sound.',
      },
      audio: {
        slow: 'l1u1l2_kaarru_slow',
        medium: 'l1u1l2_kaarru_medium',
        normal: 'l1u1l2_kaarru_normal',
        focus: ['l1u1l2_kaarru_focus'],
      },
      acceptedInputs: ['kaarru', 'kaattu'],
      notes: [
        'The doubled ṟṟ is the റ്റ sound — people type it as rr, so kaaṟṟu shows up as kaarru.',
        'Colloquially typed "kaattu" too — the ṟṟ marks the doubled tongue-tap.',
      ],
      tags: ['sound:coronal'],
    },
    {
      id: 'ente',
      manglish: 'ente',
      script: 'എന്റെ',
      meaning: 'my',
      kind: 'word',
      articulation: {
        cue: 'The nṟ flicks the tongue tip on the gum ridge behind the upper teeth. It sounds like "nd" to English ears.',
      },
      audio: {
        slow: 'l1u1l2_ente_slow',
        medium: 'l1u1l2_ente_medium',
        normal: 'l1u1l2_ente_normal',
        focus: ['l1u1l2_ente_focus'],
      },
      acceptedInputs: ['ente'],
      tags: ['sound:coronal'],
    },
    {
      id: 'enthe',
      manglish: 'enthe',
      script: 'എന്തേ',
      meaning: 'why',
      kind: 'word',
      articulation: {
        cue: 'The n and th share one spot: tongue tip at the back of the upper front teeth.',
      },
      audio: {
        slow: 'l1u1l2_enthe_slow',
        medium: 'l1u1l2_enthe_medium',
        normal: 'l1u1l2_enthe_normal',
        focus: ['l1u1l2_enthe_focus'],
      },
      acceptedInputs: ['enthe'],
      tags: ['sound:coronal'],
    },
    {
      id: 'parrum',
      manglish: 'paṟṟum',
      script: 'പറ്റും',
      meaning: 'will work; will be possible',
      kind: 'word',
      articulation: {
        cue: 'Tap the tongue tip on the gum ridge behind the upper teeth for the doubled sound, quick, like the tt in "butter".',
      },
      audio: {
        slow: 'l1u1l2_parrum_slow',
        medium: 'l1u1l2_parrum_medium',
        normal: 'l1u1l2_parrum_normal',
        focus: ['l1u1l2_parrum_focus'],
      },
      acceptedInputs: ['parrum', 'pattum'],
      notes: ['Colloquially typed "pattum".'],
      tags: ['sound:coronal'],
    },
    {
      id: 'venda',
      manglish: 'venda',
      script: 'വേണ്ട',
      meaning: "don't want; not needed",
      kind: 'word',
      articulation: {
        cue: 'The nd curls the tongue back against the roof of the mouth, never at the teeth.',
      },
      audio: {
        slow: 'l1u1l2_venda_slow',
        medium: 'l1u1l2_venda_medium',
        normal: 'l1u1l2_venda_normal',
        focus: ['l1u1l2_venda_focus'],
      },
      acceptedInputs: ['venda'],
      notes: ['Say it to refuse: "venda, venda".'],
      tags: ['sound:coronal'],
    },
    {
      id: 'und',
      manglish: 'und',
      script: 'ഉണ്ട്',
      meaning: 'there is; have',
      kind: 'word',
      articulation: {
        cue: 'Curl the tongue tip back against the roof of the mouth for the nd: one quick backward flap, not at the teeth.',
      },
      audio: {
        slow: 'l1u1l2_und_slow',
        medium: 'l1u1l2_und_medium',
        normal: 'l1u1l2_und_normal',
        focus: ['l1u1l2_und_focus'],
      },
      acceptedInputs: ['und'],
      notes: ['One of the most common Malayalam words: "there is", "have".'],
      tags: ['sound:coronal'],
    },
  ],
  minimalPairs: [
    {
      id: 'l1u1-p-ente-enthe',
      aItemId: 'ente',
      bItemId: 'enthe',
      segment: 'coronal',
      aClip: 'l1u1l2_ente_normal',
      bClip: 'l1u1l2_enthe_normal',
    },
    {
      id: 'l1u1-p-patthu-paattu',
      aItemId: 'patthu',
      bItemId: 'paattu',
      segment: 'coronal',
      aClip: 'l1u1l2_patthu_normal',
      bClip: 'l1u1l2_paattu_normal',
    },
  ],
  drills: [
    { kind: 'multipleChoice', itemId: 'patthu', distractors: ['song', 'wind', "don't want; not needed"] },
    { kind: 'multipleChoice', itemId: 'paattu', distractors: ['ten', 'wind', 'there is; have'] },
    { kind: 'multipleChoice', itemId: 'kaarru', distractors: ['ten', 'my', 'why'] },
    { kind: 'multipleChoice', itemId: 'ente', distractors: ['why', 'song', 'there is; have'] },
    { kind: 'multipleChoice', itemId: 'enthe', distractors: ['my', 'wind', 'will work; will be possible'] },
    { kind: 'multipleChoice', itemId: 'parrum', distractors: ['ten', 'why', 'there is; have'] },
    { kind: 'multipleChoice', itemId: 'venda', distractors: ['my', 'song', 'will work; will be possible'] },
    { kind: 'multipleChoice', itemId: 'und', distractors: ['wind', 'ten', "don't want; not needed"] },
    { kind: 'minimalPair', pairId: 'l1u1-p-ente-enthe' },
    { kind: 'minimalPair', pairId: 'l1u1-p-patthu-paattu' },
  ],
  reviewSlots: 0,
  spriteId: 'l1u1l2',
};
