/**
 * Level 3 Unit 2 Lesson 2 — Question words (PLAN.md §5): the -aa
 * question endings and the e- words that open every conversation.
 */

import type { Lesson } from '../../types'

export const lesson2Questions: Lesson = {
  id: 'l3u2l2',
  levelId: 'level3',
  unitId: 'unit2',
  title: 'Question words',
  reviewSlots: 2,
  sprite: { file: 'audio/l3u2l2.mp3' },
  items: [
    {
      id: 'entha',
      manglish: 'entha',
      script: 'എന്താ',
      meaning: 'what?',
      kind: 'word',
      pos: 'pronoun',
      notes: ['It means what? The casual form is enna: enna und vishesham.'],
      audio: { slow: 'entha.slow', medium: 'entha.medium', normal: 'entha.normal' },
      tags: ['level:3'],
    },
    {
      id: 'etha',
      manglish: 'etha',
      script: 'ഏതാ',
      meaning: 'which?',
      kind: 'word',
      pos: 'pronoun',
      notes: ['It means which one? ithil etha ishttapette? — which among these did you like?'],
      audio: { slow: 'etha.slow', medium: 'etha.medium', normal: 'etha.normal' },
      tags: ['level:3'],
    },
    {
      id: 'engane',
      manglish: 'engane',
      script: 'എങ്ങനെ',
      meaning: 'how?',
      kind: 'word',
      pos: 'adverb',
      notes: ['It means how? The greeting engane und? is built on it.'],
      audio: { slow: 'engane.slow', medium: 'engane.medium', normal: 'engane.normal' },
      tags: ['level:3'],
    },
    {
      id: 'enthina',
      manglish: 'enthina',
      script: 'എന്തിനാ',
      meaning: 'why?',
      kind: 'word',
      pos: 'adverb',
      notes: ['It means why? (for what).'],
      audio: { slow: 'enthina.slow', medium: 'enthina.medium', normal: 'enthina.normal' },
      tags: ['level:3'],
    },
    {
      id: 'eppozha',
      manglish: 'eppozha',
      script: 'എപ്പോഴാ',
      meaning: 'when?',
      kind: 'word',
      pos: 'adverb',
      notes: [
        'eppozha and eppo are the same word: when?',
        'e- is the question marker, the way i- points near and a- points far.',
      ],
      audio: { slow: 'eppozha.slow', medium: 'eppozha.medium', normal: 'eppozha.normal' },
      tags: ['level:3'],
    },
    {
      id: 'evide',
      manglish: 'evide',
      script: 'എവിടെ',
      meaning: 'where?',
      kind: 'word',
      pos: 'adverb',
      notes: ['It means where? It is the question twin of avide (there) and ivide (here).'],
      audio: { slow: 'evide.slow', medium: 'evide.medium', normal: 'evide.normal' },
      tags: ['level:3'],
    },
    {
      id: 'evide-aa',
      manglish: 'evide aa',
      script: 'എവിടെ ആ',
      meaning: 'where is it?',
      kind: 'sentence',
      segments: [
        { token: 'evide', gloss: 'where?' },
        { token: 'aa', gloss: 'is' },
      ],
      audio: { slow: 'evide-aa.slow', medium: 'evide-aa.medium', normal: 'evide-aa.normal' },
      tags: ['level:3'],
    },
    {
      id: 'etha-bus',
      manglish: 'etha bus',
      meaning: 'which bus?',
      kind: 'sentence',
      notes: ['No script here: the English word has no settled Malayalam spelling.'],
      segments: [
        { token: 'etha', gloss: 'which?' },
        { token: 'bus', gloss: 'bus' },
      ],
      audio: { slow: 'etha-bus.slow', medium: 'etha-bus.medium', normal: 'etha-bus.normal' },
      tags: ['level:3'],
    },
    {
      id: 'nee-chaaya-kudikkumello-alle',
      manglish: 'nee chaaya kudikkumello, alle',
      meaning: 'you drink tea, right?',
      kind: 'sentence',
      acceptedInputs: ['nee chaaya kudikkumello alle', 'ni chaaya kudikkumello alle'],
      notes: [
        'The -umello tag asks for confirmation: kudikkumello, right?',
        'No script here: the written form spells the tag differently.',
      ],
      segments: [
        { token: 'nee', gloss: 'you (casual)' },
        { token: 'chaaya', gloss: 'tea' },
        { token: 'kudikkumello,', gloss: 'drinks, right?' },
        { token: 'alle', gloss: 'right? (tag)' },
      ],
      audio: { slow: 'nee-chaaya-kudikkumello-alle.slow', medium: 'nee-chaaya-kudikkumello-alle.medium', normal: 'nee-chaaya-kudikkumello-alle.normal' },
      tags: ['level:3'],
    },
  ],
  pairs: [],
  drills: [
    { kind: 'multipleChoice', itemId: 'entha', distractors: ['etha', 'engane', 'evide'] },
    { kind: 'multipleChoice', itemId: 'etha', distractors: ['entha', 'enthina', 'eppozha'] },
    { kind: 'multipleChoice', itemId: 'engane', distractors: ['entha', 'etha', 'evide'] },
    { kind: 'multipleChoice', itemId: 'enthina', distractors: ['entha', 'eppozha', 'engane'] },
    { kind: 'multipleChoice', itemId: 'eppozha', distractors: ['enthina', 'etha', 'evide'] },
    { kind: 'multipleChoice', itemId: 'evide', distractors: ['entha', 'engane', 'eppozha'] },
    { kind: 'multipleChoice', itemId: 'evide-aa', distractors: ['etha-bus', 'entha', 'engane'] },
    { kind: 'multipleChoice', itemId: 'etha-bus', distractors: ['evide-aa', 'etha', 'entha'] },
    { kind: 'multipleChoice', itemId: 'nee-chaaya-kudikkumello-alle', distractors: ['evide-aa', 'etha-bus', 'entha'] },
    {
      kind: 'sentenceBuilder',
      sentenceId: 'evide-aa',
      bank: ['evide', 'aa'],
      acceptedInputs: ['evide aa'],
    },
    {
      kind: 'sentenceBuilder',
      sentenceId: 'etha-bus',
      bank: ['etha', 'bus'],
      acceptedInputs: ['etha bus'],
    },
    {
      kind: 'sentenceBuilder',
      sentenceId: 'nee-chaaya-kudikkumello-alle',
      bank: ['nee', 'chaaya', 'kudikkumello,', 'alle'],
      acceptedInputs: ['nee chaaya kudikkumello alle', 'ni chaaya kudikkumello alle'],
    },
    { kind: 'typing', itemId: 'evide', acceptedInputs: ['evide'] },
    { kind: 'typing', itemId: 'engane', acceptedInputs: ['engane'] },
  ],
}

