/**
 * Level 3 Unit 2 Lesson 2 — Question words (PLAN.md §5): the -aa
 * question endings and the e- words that open every conversation.
 */

import type { Lesson } from '../../types'

export const lesson2Questions: Lesson = {
  id: 'l3u2l2',
  levelId: 'level3',
  unitId: 'unit2',
  title: 'Question words',
  reviewSlots: 2,
  sprite: { file: 'audio/l3u2l2.mp3' },
  items: [
    {
      id: 'enthaa',
      manglish: 'enthaa',
      script: 'എന്താ',
      meaning: 'what?',
      kind: 'word',
      pos: 'pronoun',
      notes: ['enthaa, what? The casual form is enna: enna und vishesham.'],
      audio: { slow: 'enthaa.slow', medium: 'enthaa.medium', normal: 'enthaa.normal' },
      tags: ['level:3'],
    },
    {
      id: 'ethaa',
      manglish: 'ethaa',
      script: 'ഏതാ',
      meaning: 'which?',
      kind: 'word',
      pos: 'pronoun',
      notes: ['ethaa, which one?'],
      audio: { slow: 'ethaa.slow', medium: 'ethaa.medium', normal: 'ethaa.normal' },
      tags: ['level:3'],
    },
    {
      id: 'engane',
      manglish: 'engane',
      script: 'എങ്ങനെ',
      meaning: 'how?',
      kind: 'word',
      pos: 'adverb',
      notes: ['engane, how? The greeting engane und? is built on it.'],
      audio: { slow: 'engane.slow', medium: 'engane.medium', normal: 'engane.normal' },
      tags: ['level:3'],
    },
    {
      id: 'enthinaa',
      manglish: 'enthinaa',
      script: 'എന്തിനാ',
      meaning: 'why?',
      kind: 'word',
      pos: 'adverb',
      notes: ['enthinaa, why? (for what).'],
      audio: { slow: 'enthinaa.slow', medium: 'enthinaa.medium', normal: 'enthinaa.normal' },
      tags: ['level:3'],
    },
    {
      id: 'eppozhaa',
      manglish: 'eppozhaa',
      script: 'എപ്പോഴാ',
      meaning: 'when?',
      kind: 'word',
      pos: 'adverb',
      notes: ['eppozhaa, when? Built on eppozhum (always) with the -aa question ending.'],
      audio: { slow: 'eppozhaa.slow', medium: 'eppozhaa.medium', normal: 'eppozhaa.normal' },
      tags: ['level:3'],
    },
    {
      id: 'evide',
      manglish: 'evide',
      script: 'എവിടെ',
      meaning: 'where?',
      kind: 'word',
      pos: 'adverb',
      notes: ['evide, where? The question twin of avide (there) and ivide (here).'],
      audio: { slow: 'evide.slow', medium: 'evide.medium', normal: 'evide.normal' },
      tags: ['level:3'],
    },
    {
      id: 'evide-aa',
      manglish: 'evide aa',
      script: 'എവിടെ ആ',
      meaning: 'where is it?',
      kind: 'sentence',
      segments: [
        { token: 'evide', gloss: 'where?' },
        { token: 'aa', gloss: 'is' },
      ],
      audio: { slow: 'evide-aa.slow', medium: 'evide-aa.medium', normal: 'evide-aa.normal' },
      tags: ['level:3'],
    },
    {
      id: 'ethaa-bus',
      manglish: 'ethaa bus',
      meaning: 'which bus?',
      kind: 'sentence',
      notes: ['No script here: the English word has no settled Malayalam spelling.'],
      segments: [
        { token: 'ethaa', gloss: 'which?' },
        { token: 'bus', gloss: 'bus' },
      ],
      audio: { slow: 'ethaa-bus.slow', medium: 'ethaa-bus.medium', normal: 'ethaa-bus.normal' },
      tags: ['level:3'],
    },
  ],
  pairs: [],
  drills: [
    { kind: 'multipleChoice', itemId: 'enthaa', distractors: ['ethaa', 'engane', 'evide'] },
    { kind: 'multipleChoice', itemId: 'ethaa', distractors: ['enthaa', 'enthinaa', 'eppozhaa'] },
    { kind: 'multipleChoice', itemId: 'engane', distractors: ['enthaa', 'ethaa', 'evide'] },
    { kind: 'multipleChoice', itemId: 'enthinaa', distractors: ['enthaa', 'eppozhaa', 'engane'] },
    { kind: 'multipleChoice', itemId: 'eppozhaa', distractors: ['enthinaa', 'ethaa', 'evide'] },
    { kind: 'multipleChoice', itemId: 'evide', distractors: ['enthaa', 'engane', 'eppozhaa'] },
    { kind: 'multipleChoice', itemId: 'evide-aa', distractors: ['ethaa-bus', 'enthaa', 'engane'] },
    { kind: 'multipleChoice', itemId: 'ethaa-bus', distractors: ['evide-aa', 'ethaa', 'enthaa'] },
    {
      kind: 'sentenceBuilder',
      sentenceId: 'evide-aa',
      bank: ['evide', 'aa'],
      acceptedInputs: ['evide aa'],
    },
    {
      kind: 'sentenceBuilder',
      sentenceId: 'ethaa-bus',
      bank: ['ethaa', 'bus'],
      acceptedInputs: ['ethaa bus'],
    },
    { kind: 'typing', itemId: 'evide', acceptedInputs: ['evide'] },
    { kind: 'typing', itemId: 'engane', acceptedInputs: ['engane'] },
  ],
}
