/**
 * Level 1 Unit 2 — Greetings & expressions (PLAN.md §5).
 * The everyday exchanges that open a conversation: each question pairs
 * with its natural reply, plus the small words that keep one going.
 * First lesson with speaking (typing) drills — the sounds checkpoint is done.
 */

import type { Lesson } from '../../types'

export const lesson1Greetings: Lesson = {
  id: 'l1u2l1',
  levelId: 'level1',
  unitId: 'unit2',
  title: 'Greetings & expressions',
  reviewSlots: 0,
  sprite: { file: 'audio/l1u2l1.mp3' },
  items: [
    {
      id: 'engane-und',
      manglish: 'engane und',
      script: 'എങ്ങനെ ഉണ്ട്',
      meaning: 'how is it? (also how are you?)',
      kind: 'phrase',
      notes: ['The go-to casual greeting, any time of day. It also asks about things: kaappi engane und?'],
      audio: { slow: 'engane-und.slow', medium: 'engane-und.medium', normal: 'engane-und.normal' },
      tags: ['level:1'],
    },
    {
      id: 'kaappi-engane-und-kollaamo',
      manglish: 'kaappi engane und, kollaamo',
      script: 'കാപ്പി എങ്ങനെ ഉണ്ട്, കൊല്ലാമോ',
      meaning: 'how is the coffee, is it good?',
      kind: 'sentence',
      segments: [
        { token: 'kaappi', gloss: 'coffee' },
        { token: 'engane', gloss: 'how' },
        { token: 'und,', gloss: 'is it?' },
        { token: 'kollaamo', gloss: 'is it good?' },
      ],
      audio: { slow: 'kaappi-engane-und-kollaamo.slow', medium: 'kaappi-engane-und-kollaamo.medium', normal: 'kaappi-engane-und-kollaamo.normal' },
      tags: ['level:1'],
    },
    {
      id: 'sukham',
      manglish: 'sukham',
      script: 'സുഖം',
      meaning: 'fine, well',
      kind: 'word',
      pos: 'noun',
      notes: ['The usual reply to engane und? — short answers, no njan needed.'],
      audio: { slow: 'sukham.slow', medium: 'sukham.medium', normal: 'sukham.normal' },
      tags: ['level:1'],
    },
    {
      id: 'ennaa-vishesham',
      manglish: 'enna und vishesham',
      script: 'എന്നാ ഉണ്ട് വിശേഷം',
      meaning: "what's up?",
      kind: 'phrase',
      notes: ['enna is the casual form of entha (what).'],
      audio: { slow: 'ennaa-vishesham.slow', medium: 'ennaa-vishesham.medium', normal: 'ennaa-vishesham.normal' },
      tags: ['level:1'],
    },
    {
      id: 'nannayitt-pokunnu',
      manglish: 'nannayitt pokunnu',
      script: 'നന്നായിട്ട് പോകുന്നു',
      meaning: "it's going well",
      kind: 'phrase',
      notes: ['A fixed expression, the answer to engane und?. The formal-looking pokunnu is exactly right here.'],
      audio: { slow: 'nannayitt-pokunnu.slow', medium: 'nannayitt-pokunnu.medium', normal: 'nannayitt-pokunnu.normal' },
      tags: ['level:1'],
    },
    {
      id: 'vishesham-onnum-illa',
      manglish: 'vishesham onnum illa',
      meaning: 'nothing much',
      kind: 'phrase',
      notes: [
        'The usual reply to enna und vishesham?',
        'No script here: the written form spells a long u that is short in speech.',
      ],
      audio: { slow: 'vishesham-onnum-illa.slow', medium: 'vishesham-onnum-illa.medium', normal: 'vishesham-onnum-illa.normal' },
      tags: ['level:1'],
    },
    {
      id: 'seri',
      manglish: 'sheri',
      script: 'ശെരി',
      meaning: 'okay, fine',
      kind: 'expression',
      acceptedInputs: ['seri'],
      audio: { slow: 'seri.slow', medium: 'seri.medium', normal: 'seri.normal' },
      tags: ['level:1'],
    },
    {
      id: 'nokkam',
      manglish: 'nokkaam',
      script: 'നോക്കാം',
      meaning: "let's see",
      kind: 'expression',
      acceptedInputs: ['nokkam', 'nokam'],
      notes: ['Said when you are not sure yet. The everyday present form is nokkuva.'],
      audio: { slow: 'nokkam.slow', medium: 'nokkam.medium', normal: 'nokkam.normal' },
      tags: ['level:1'],
    },
    {
      id: 'ayyo',
      manglish: 'ayyo',
      script: 'അയ്യോ',
      meaning: 'oh no!',
      kind: 'expression',
      audio: { slow: 'ayyo.slow', medium: 'ayyo.medium', normal: 'ayyo.normal' },
      tags: ['level:1'],
    },
    {
      id: 'pinnalla',
      manglish: 'pinnalla',
      script: 'പിന്നല്ല',
      meaning: 'of course, obviously',
      kind: 'expression',
      notes: ['Warm agreement: "is the food good?" — pinnalla!'],
      audio: { slow: 'pinnalla.slow', medium: 'pinnalla.medium', normal: 'pinnalla.normal' },
      tags: ['level:1'],
    },
    {
      id: 'alle',
      manglish: 'alle',
      script: 'അല്ലേ',
      meaning: "isn't it? (tag question)",
      kind: 'expression',
      notes: ['Tag questions keep the conversation moving — they ask for a quick yes.'],
      audio: { slow: 'alle.slow', medium: 'alle.medium', normal: 'alle.normal' },
      tags: ['level:1'],
    },
    {
      id: 'poyi-varatte',
      manglish: 'appo sheri, bye',
      meaning: 'okay then, bye.',
      kind: 'expression',
      notes: [
        'The colloquial goodbye: appo sheri (okay then), bye.',
        'No script here: the English word has no settled Malayalam spelling.',
      ],
      audio: { slow: 'poyi-varatte.slow', medium: 'poyi-varatte.medium', normal: 'poyi-varatte.normal' },
      tags: ['level:1'],
    },
  ],
  pairs: [],
  drills: [
    { kind: 'multipleChoice', itemId: 'engane-und', distractors: ['ennaa-vishesham', 'sukham', 'poyi-varatte'] },
    { kind: 'multipleChoice', itemId: 'ennaa-vishesham', distractors: ['engane-und', 'seri', 'nokkam'] },
    { kind: 'multipleChoice', itemId: 'sukham', distractors: ['ayyo', 'pinnalla', 'alle'] },
    { kind: 'multipleChoice', itemId: 'seri', distractors: ['nokkam', 'alle', 'ayyo'] },
    { kind: 'multipleChoice', itemId: 'nokkam', distractors: ['seri', 'pinnalla', 'ayyo'] },
    { kind: 'multipleChoice', itemId: 'ayyo', distractors: ['seri', 'alle', 'pinnalla'] },
    { kind: 'multipleChoice', itemId: 'pinnalla', distractors: ['nokkam', 'alle', 'ayyo'] },
    { kind: 'multipleChoice', itemId: 'alle', distractors: ['ayyo', 'seri', 'poyi-varatte'] },
    { kind: 'multipleChoice', itemId: 'poyi-varatte', distractors: ['engane-und', 'alle', 'nokkam'] },
    { kind: 'multipleChoice', itemId: 'kaappi-engane-und-kollaamo', distractors: ['engane-und', 'nannayitt-pokunnu', 'ennaa-vishesham'] },
    { kind: 'multipleChoice', itemId: 'nannayitt-pokunnu', distractors: ['sukham', 'pinnalla', 'seri'] },
    { kind: 'typing', itemId: 'seri' },
    { kind: 'typing', itemId: 'nokkam' },
    { kind: 'typing', itemId: 'ayyo', acceptedInputs: ['ayo'] },
    { kind: 'typing', itemId: 'alle', acceptedInputs: ['ale'] },
  ],
}
