import type { Lesson } from '../types';

/**
 * Level 3 Unit 1 Lesson 4 — the -nte suffix (PLAN.md §5): of, belonging.
 * ente and ninte opened the door; here the ending spreads across the
 * third person (avante, avaḷude, avarude) and onto English words
 * (businte), plus the question word aarude.
 */
export const l3u1l4: Lesson = {
  id: 'l3u1l4',
  levelId: 'l3',
  unitId: 'l3u1',
  title: 'Of and belonging',
  comprehensionOnly: false,
  items: [
    {
      id: 'avante',
      manglish: 'avante',
      script: 'അവന്റെ',
      meaning: 'his',
      kind: 'word',
      audio: {
        slow: 'l3u1l4_avante_slow',
        medium: 'l3u1l4_avante_medium',
        normal: 'l3u1l4_avante_normal',
      },
      acceptedInputs: ['avante'],
      notes: ['avan plus -nte: his. The same ending ente and ninte wear, on a third person.'],
      tags: [],
    },
    {
      id: 'avalude',
      manglish: 'avaḷude',
      script: 'അവളുടെ',
      meaning: 'her',
      kind: 'word',
      audio: {
        slow: 'l3u1l4_avalude_slow',
        medium: 'l3u1l4_avalude_medium',
        normal: 'l3u1l4_avalude_normal',
      },
      acceptedInputs: ['avalude'],
      notes: ['Words ending in -aḷ take -ude instead: avaḷude, her.'],
      tags: [],
    },
    {
      id: 'nammude',
      manglish: 'nammude',
      script: 'നമ്മുടെ',
      meaning: 'our (you and me)',
      kind: 'word',
      audio: {
        slow: 'l3u1l4_nammude_slow',
        medium: 'l3u1l4_nammude_medium',
        normal: 'l3u1l4_nammude_normal',
      },
      acceptedInputs: ['nammude'],
      notes: ['The our that includes the person you are talking to: nammude veedu, our house.'],
      tags: [],
    },
    {
      id: 'avarude',
      manglish: 'avarude',
      script: 'അവരുടെ',
      meaning: 'their',
      kind: 'word',
      audio: {
        slow: 'l3u1l4_avarude_slow',
        medium: 'l3u1l4_avarude_medium',
        normal: 'l3u1l4_avarude_normal',
      },
      acceptedInputs: ['avarude'],
      notes: ['avar plus -ude: their. The same shape as avaḷude.'],
      tags: [],
    },
    {
      id: 'aarude',
      manglish: 'aarude',
      script: 'ആരുടെ',
      meaning: 'whose',
      kind: 'word',
      audio: {
        slow: 'l3u1l4_aarude_slow',
        medium: 'l3u1l4_aarude_medium',
        normal: 'l3u1l4_aarude_normal',
      },
      acceptedInputs: ['aarude', 'arude'],
      notes: ['aaru, who, plus -ude: whose. athu aarude, whose is that?'],
      tags: [],
    },
    {
      id: 'veedu',
      manglish: 'veedu',
      script: 'വീട്',
      meaning: 'house',
      kind: 'word',
      audio: {
        slow: 'l3u1l4_veedu_slow',
        medium: 'l3u1l4_veedu_medium',
        normal: 'l3u1l4_veedu_normal',
      },
      acceptedInputs: ['veedu'],
      notes: ['House. At home it becomes veettil — the t doubles there.'],
      tags: [],
    },
    {
      id: 'chettante',
      manglish: 'chettante',
      script: 'ചേട്ടന്റെ',
      meaning: "the older brother's",
      kind: 'word',
      audio: {
        slow: 'l3u1l4_chettante_slow',
        medium: 'l3u1l4_chettante_medium',
        normal: 'l3u1l4_chettante_normal',
      },
      acceptedInputs: ['chettante'],
      notes: ['chettan ends in -n, so the ending sits straight on it: chettante veedu.'],
      tags: [],
    },
    {
      id: 'businte',
      manglish: 'businte',
      script: 'ബസ്സിന്റെ',
      meaning: "the bus's; of the bus",
      kind: 'word',
      audio: {
        slow: 'l3u1l4_businte_slow',
        medium: 'l3u1l4_businte_medium',
        normal: 'l3u1l4_businte_normal',
      },
      acceptedInputs: ['businte'],
      notes: ['English words take the ending too: businte. In script the s doubles: ബസ്സിന്റെ.'],
      tags: [],
    },
    {
      id: 'ente-veedu',
      manglish: 'ente veedu',
      script: 'എന്റെ വീട്',
      meaning: 'my house',
      kind: 'phrase',
      audio: {
        slow: 'l3u1l4_ente-veedu_slow',
        medium: 'l3u1l4_ente-veedu_medium',
        normal: 'l3u1l4_ente-veedu_normal',
      },
      acceptedInputs: ['ente veedu'],
      notes: ['The first possessive you learned, put to work.'],
      tags: [],
    },
    {
      id: 'avante-joli',
      manglish: 'avante joli',
      script: 'അവന്റെ ജോലി',
      meaning: 'his job',
      kind: 'phrase',
      audio: {
        slow: 'l3u1l4_avante-joli_slow',
        medium: 'l3u1l4_avante-joli_medium',
        normal: 'l3u1l4_avante-joli_normal',
      },
      acceptedInputs: ['avante joli'],
      notes: ['Of a person: avante joli, his job.'],
      tags: [],
    },
    {
      id: 'athu-aarude-aanu',
      manglish: 'athu aarude aanu',
      script: 'അത് ആരുടെ ആണ്',
      meaning: 'whose is that?',
      kind: 'sentence',
      audio: {
        slow: 'l3u1l4_athu-aarude-aanu_slow',
        medium: 'l3u1l4_athu-aarude-aanu_medium',
        normal: 'l3u1l4_athu-aarude-aanu_normal',
      },
      sentence: {
        bank: ['athu', 'aarude', 'aanu', 'veedu'],
        orders: ['athu aarude aanu', 'athu aarude'],
        parts: [
          { word: 'athu', meaning: 'that (thing)' },
          { word: 'aarude', meaning: 'whose' },
          { word: 'aanu', meaning: 'is' },
        ],
      },
      notes: ['Ask it full or short: athu aarude aanu, or just athu aarude.'],
      tags: [],
    },
    {
      id: 'avarude-veedu-avide-und',
      manglish: 'avarude veedu avide und',
      script: 'അവരുടെ വീട് അവിടെ ഉണ്ട്',
      meaning: 'their house is there',
      kind: 'sentence',
      audio: {
        slow: 'l3u1l4_avarude-veedu-avide-und_slow',
        medium: 'l3u1l4_avarude-veedu-avide-und_medium',
        normal: 'l3u1l4_avarude-veedu-avide-und_normal',
      },
      sentence: {
        bank: ['avarude', 'veedu', 'avide', 'und', 'nammude'],
        orders: ['avarude veedu avide und'],
        parts: [
          { word: 'avarude', meaning: 'their' },
          { word: 'veedu', meaning: 'house' },
          { word: 'avide', meaning: 'there' },
          { word: 'und', meaning: 'there is; have' },
        ],
      },
      notes: ['Four words, one possessive: their house, there, is.'],
      tags: [],
    },
    {
      id: 'avan-ente-friend-aanu',
      manglish: 'avan ente friend aanu',
      script: 'അവൻ എന്റെ ഫ്രണ്ട് ആണ്',
      meaning: 'he is my friend',
      kind: 'sentence',
      audio: {
        slow: 'l3u1l4_avan-ente-friend-aanu_slow',
        medium: 'l3u1l4_avan-ente-friend-aanu_medium',
        normal: 'l3u1l4_avan-ente-friend-aanu_normal',
      },
      sentence: {
        bank: ['avan', 'ente', 'friend', 'aanu', 'avante'],
        orders: ['avan ente friend aanu'],
        parts: [
          { word: 'avan', meaning: 'he' },
          { word: 'ente', meaning: 'my' },
          { word: 'friend', meaning: 'friend' },
          { word: 'aanu', meaning: 'is' },
        ],
      },
      notes: ['English nouns slot straight in: friend stays friend.'],
      tags: [],
    },
  ],
  minimalPairs: [],
  drills: [
    { kind: 'multipleChoice', itemId: 'avante', distractors: ['her', 'their', 'our (you and me)'] },
    { kind: 'multipleChoice', itemId: 'avalude', distractors: ['his', 'whose', 'their'] },
    { kind: 'multipleChoice', itemId: 'nammude', distractors: ['their', 'her', 'whose'] },
    { kind: 'multipleChoice', itemId: 'avarude', distractors: ['our (you and me)', 'his', 'my house'] },
    { kind: 'multipleChoice', itemId: 'aarude', distractors: ['his', 'her', 'their'] },
    { kind: 'multipleChoice', itemId: 'veedu', distractors: ["the bus's; of the bus", "the older brother's", 'my house'] },
    { kind: 'multipleChoice', itemId: 'chettante', distractors: ['his', 'her', 'whose'] },
    { kind: 'multipleChoice', itemId: 'businte', distractors: ['house', "the older brother's", 'their'] },
    { kind: 'multipleChoice', itemId: 'ente-veedu', distractors: ['his job', 'their house is there', 'her'] },
    { kind: 'multipleChoice', itemId: 'avante-joli', distractors: ['my house', 'whose', 'their'] },
    { kind: 'sentenceBuilder', itemId: 'athu-aarude-aanu', mode: 'bank' },
    { kind: 'sentenceBuilder', itemId: 'avarude-veedu-avide-und', mode: 'bank' },
    { kind: 'sentenceBuilder', itemId: 'avan-ente-friend-aanu', mode: 'bank' },
  ],
  reviewSlots: 0,
  spriteId: 'l3u1l4',
};
