import type { Lesson } from '../types';

/**
 * Level 3 Unit 1 Lesson 2 — the -kku suffix (PLAN.md §5): to, for.
 * The dative on people and jobs: enikk (to me), avanu (to him),
 * jolikku (to work) — fast speech drops the final u: jolikk.
 */
export const l3u1l2: Lesson = {
  id: 'l3u1l2',
  levelId: 'l3',
  unitId: 'l3u1',
  title: 'To and for',
  comprehensionOnly: false,
  items: [
    {
      id: 'joli',
      manglish: 'joli',
      script: 'ജോലി',
      meaning: 'work; a job',
      kind: 'word',
      audio: {
        slow: 'l3u1l2_joli_slow',
        medium: 'l3u1l2_joli_medium',
        normal: 'l3u1l2_joli_normal',
      },
      acceptedInputs: ['joli'],
      notes: ['Work, the job — the everyday word for how you spend the day.'],
      tags: [],
    },
    {
      id: 'jolikku',
      manglish: 'jolikku',
      script: 'ജോലിക്ക്',
      meaning: 'to work; for the job',
      kind: 'word',
      audio: {
        slow: 'l3u1l2_jolikku_slow',
        medium: 'l3u1l2_jolikku_medium',
        normal: 'l3u1l2_jolikku_normal',
        focus: ['l3u1l2_jolikku_focus'],
      },
      acceptedInputs: ['jolikku', 'jolikk'],
      articulation: {
        cue: 'Hold the doubled kk.',
      },
      notes: ['-kku on joli: going to work. Fast speech drops the last u: jolikk.'],
      tags: ['sound:geminate'],
    },
    {
      id: 'officekku',
      manglish: 'officekku',
      script: 'ഓഫീസ്ക്ക്',
      meaning: 'to the office',
      kind: 'word',
      audio: {
        slow: 'l3u1l2_officekku_slow',
        medium: 'l3u1l2_officekku_medium',
        normal: 'l3u1l2_officekku_normal',
      },
      acceptedInputs: ['officekku'],
      notes: ['The same -kku on the English office.'],
      tags: [],
    },
    {
      id: 'enikk',
      manglish: 'enikk',
      script: 'എനിക്ക്',
      meaning: 'to me',
      kind: 'word',
      audio: {
        slow: 'l3u1l2_enikk_slow',
        medium: 'l3u1l2_enikk_medium',
        normal: 'l3u1l2_enikk_normal',
        focus: ['l3u1l2_enikk_focus'],
      },
      acceptedInputs: ['enikk', 'enik'],
      articulation: {
        cue: 'Hold the doubled kk.',
      },
      notes: ['-kku on njan becomes enikk — the dative you met in enikk chaaya venam.'],
      tags: ['sound:geminate'],
    },
    {
      id: 'avanu',
      manglish: 'avanu',
      script: 'അവനു',
      meaning: 'to him',
      kind: 'word',
      audio: {
        slow: 'l3u1l2_avanu_slow',
        medium: 'l3u1l2_avanu_medium',
        normal: 'l3u1l2_avanu_normal',
      },
      acceptedInputs: ['avanu'],
      notes: ['The casual to-him: avan plus the dative.'],
      tags: [],
    },
    {
      id: 'njan-jolikku-pokuva',
      manglish: 'njan jolikku pokuva',
      script: 'ഞാൻ ജോലിക്ക് പോകുവാ',
      meaning: 'I am going to work',
      kind: 'sentence',
      audio: {
        slow: 'l3u1l2_njan-jolikku-pokuva_slow',
        medium: 'l3u1l2_njan-jolikku-pokuva_medium',
        normal: 'l3u1l2_njan-jolikku-pokuva_normal',
      },
      sentence: {
        bank: ['njan', 'jolikku', 'pokuva', 'joli'],
        orders: ['njan jolikku pokuva'],
        parts: [
          { word: 'njan', meaning: 'I' },
          { word: 'jolikku', meaning: 'to work; for the job' },
          { word: 'pokuva', meaning: 'going' },
        ],
      },
      notes: ['The everyday goodbye in the morning: njan jolikku pokuva.'],
      tags: [],
    },
    {
      id: 'avan-officekku-pokuva',
      manglish: 'avan officekku pokuva',
      script: 'അവൻ ഓഫീസ്ക്ക് പോകുവാ',
      meaning: 'he is going to the office',
      kind: 'sentence',
      audio: {
        slow: 'l3u1l2_avan-officekku-pokuva_slow',
        medium: 'l3u1l2_avan-officekku-pokuva_medium',
        normal: 'l3u1l2_avan-officekku-pokuva_normal',
      },
      sentence: {
        bank: ['avan', 'officekku', 'pokuva', 'jolikku'],
        orders: ['avan officekku pokuva'],
        parts: [
          { word: 'avan', meaning: 'he' },
          { word: 'officekku', meaning: 'to the office' },
          { word: 'pokuva', meaning: 'going' },
        ],
      },
      notes: ['Third person, same frame.'],
      tags: [],
    },
    {
      id: 'nammal-jolikku-pokuva',
      manglish: 'nammaḷ jolikku pokuva',
      script: 'നമ്മൾ ജോലിക്ക് പോകുവാ',
      meaning: 'we are going to work',
      kind: 'sentence',
      audio: {
        slow: 'l3u1l2_nammal-jolikku-pokuva_slow',
        medium: 'l3u1l2_nammal-jolikku-pokuva_medium',
        normal: 'l3u1l2_nammal-jolikku-pokuva_normal',
      },
      sentence: {
        bank: ['nammaḷ', 'jolikku', 'pokuva', 'officekku'],
        orders: ['nammaḷ jolikku pokuva'],
        parts: [
          { word: 'nammaḷ', meaning: 'we (you and me)' },
          { word: 'jolikku', meaning: 'to work; for the job' },
          { word: 'pokuva', meaning: 'going' },
        ],
      },
      notes: ['The inclusive we — you and me, heading to work.'],
      tags: [],
    },
  ],
  minimalPairs: [],
  drills: [
    { kind: 'multipleChoice', itemId: 'joli', distractors: ['to work; for the job', 'to the office', 'to me'] },
    { kind: 'multipleChoice', itemId: 'jolikku', distractors: ['work; a job', 'to the office', 'to me'] },
    { kind: 'multipleChoice', itemId: 'officekku', distractors: ['work; a job', 'to work; for the job', 'to me'] },
    { kind: 'multipleChoice', itemId: 'enikk', distractors: ['to him', 'to the office', 'work; a job'] },
    { kind: 'multipleChoice', itemId: 'avanu', distractors: ['to me', 'to work; for the job', 'to the office'] },
    { kind: 'sentenceBuilder', itemId: 'njan-jolikku-pokuva', mode: 'bank' },
    { kind: 'sentenceBuilder', itemId: 'avan-officekku-pokuva', mode: 'bank' },
    { kind: 'sentenceBuilder', itemId: 'nammal-jolikku-pokuva', mode: 'bank' },
  ],
  reviewSlots: 0,
  spriteId: 'l3u1l2',
};
