import type { Lesson } from '../types';

/**
 * Level 3 Unit 1 Lesson 5 — the -um suffix (PLAN.md §5): also, and.
 * The ending that makes a verb habitual makes "too" on people and
 * things (njanum, chaayayum, busum); two -um words in a row make
 * "and" (chaayayum kaappiyum).
 */
export const l3u1l5: Lesson = {
  id: 'l3u1l5',
  levelId: 'l3',
  unitId: 'l3u1',
  title: 'And also',
  comprehensionOnly: false,
  items: [
    {
      id: 'njanum',
      manglish: 'njanum',
      script: 'ഞാനും',
      meaning: 'me too',
      kind: 'word',
      audio: {
        slow: 'l3u1l5_njanum_slow',
        medium: 'l3u1l5_njanum_medium',
        normal: 'l3u1l5_njanum_normal',
      },
      acceptedInputs: ['njanum'],
      notes: [
        'njan plus -um: njanum, me too.',
        'The same -um makes a verb habitual (kudikkum, drinks); on a name or a thing it means too.',
      ],
      tags: [],
    },
    {
      id: 'avanum',
      manglish: 'avanum',
      script: 'അവനും',
      meaning: 'he too',
      kind: 'word',
      audio: {
        slow: 'l3u1l5_avanum_slow',
        medium: 'l3u1l5_avanum_medium',
        normal: 'l3u1l5_avanum_normal',
      },
      acceptedInputs: ['avanum'],
      notes: ['avan plus -um: he too.'],
      tags: [],
    },
    {
      id: 'nammalum',
      manglish: 'nammaḷum',
      script: 'നമ്മളും',
      meaning: 'we too (you and me)',
      kind: 'word',
      audio: {
        slow: 'l3u1l5_nammalum_slow',
        medium: 'l3u1l5_nammalum_medium',
        normal: 'l3u1l5_nammalum_normal',
      },
      acceptedInputs: ['nammalum'],
      notes: ['The inclusive we, with -um: nammaḷum, we too.'],
      tags: [],
    },
    {
      id: 'chaayayum',
      manglish: 'chaayayum',
      script: 'ചായയും',
      meaning: 'tea too',
      kind: 'word',
      audio: {
        slow: 'l3u1l5_chaayayum_slow',
        medium: 'l3u1l5_chaayayum_medium',
        normal: 'l3u1l5_chaayayum_normal',
      },
      acceptedInputs: ['chaayayum'],
      notes: ['Things take it just as easily: chaayayum, tea too.'],
      tags: [],
    },
    {
      id: 'kaappiyum',
      manglish: 'kaappiyum',
      script: 'കാപ്പിയും',
      meaning: 'coffee too',
      kind: 'word',
      audio: {
        slow: 'l3u1l5_kaappiyum_slow',
        medium: 'l3u1l5_kaappiyum_medium',
        normal: 'l3u1l5_kaappiyum_normal',
      },
      acceptedInputs: ['kaappiyum'],
      notes: ['kaappi plus -um. Coffee is kaappi through this whole course.'],
      tags: [],
    },
    {
      id: 'busum',
      manglish: 'busum',
      script: 'ബസ്സും',
      meaning: 'the bus too',
      kind: 'word',
      audio: {
        slow: 'l3u1l5_busum_slow',
        medium: 'l3u1l5_busum_medium',
        normal: 'l3u1l5_busum_normal',
      },
      acceptedInputs: ['busum'],
      notes: ['English words take -um too: busum. In script the s doubles: ബസ്സും.'],
      tags: [],
    },
    {
      id: 'chaayayum-kaappiyum',
      manglish: 'chaayayum kaappiyum',
      script: 'ചായയും കാപ്പിയും',
      meaning: 'tea and coffee',
      kind: 'phrase',
      audio: {
        slow: 'l3u1l5_chaayayum-kaappiyum_slow',
        medium: 'l3u1l5_chaayayum-kaappiyum_medium',
        normal: 'l3u1l5_chaayayum-kaappiyum_normal',
      },
      acceptedInputs: ['chaayayum kaappiyum'],
      notes: ['Two -um words in a row mean and: chaayayum kaappiyum.'],
      tags: [],
    },
    {
      id: 'chettanum-chechiyum',
      manglish: 'chettanum chechiyum',
      script: 'ചേട്ടനും ചേച്ചിയും',
      meaning: 'the older brother and the older sister',
      kind: 'phrase',
      audio: {
        slow: 'l3u1l5_chettanum-chechiyum_slow',
        medium: 'l3u1l5_chettanum-chechiyum_medium',
        normal: 'l3u1l5_chettanum-chechiyum_normal',
      },
      acceptedInputs: ['chettanum chechiyum'],
      notes: ['The same pattern on people: chettanum chechiyum.'],
      tags: [],
    },
    {
      id: 'njanum-pokuva',
      manglish: 'njanum pokuva',
      script: 'ഞാനും പോകുവാ',
      meaning: 'I am going too',
      kind: 'sentence',
      audio: {
        slow: 'l3u1l5_njanum-pokuva_slow',
        medium: 'l3u1l5_njanum-pokuva_medium',
        normal: 'l3u1l5_njanum-pokuva_normal',
      },
      sentence: {
        bank: ['njanum', 'pokuva', 'njan', 'avanum'],
        orders: ['njanum pokuva'],
        parts: [
          { word: 'njanum', meaning: 'me too' },
          { word: 'pokuva', meaning: 'going' },
        ],
      },
      notes: ['Tagging along, in one word: njanum pokuva.'],
      tags: [],
    },
    {
      id: 'avanum-varunnund',
      manglish: 'avanum varunnund',
      script: 'അവനും വരുന്നുണ്ട്',
      meaning: 'he is coming too',
      kind: 'sentence',
      audio: {
        slow: 'l3u1l5_avanum-varunnund_slow',
        medium: 'l3u1l5_avanum-varunnund_medium',
        normal: 'l3u1l5_avanum-varunnund_normal',
      },
      sentence: {
        bank: ['avanum', 'varunnund', 'avan', 'njanum'],
        orders: ['avanum varunnund'],
        parts: [
          { word: 'avanum', meaning: 'he too' },
          { word: 'varunnund', meaning: 'is coming' },
        ],
      },
      notes: ['The -um rides on the person, not the verb: avanum varunnund.'],
      tags: [],
    },
    {
      id: 'enikkum-chaaya-venam',
      manglish: 'enikkum chaaya venam',
      script: 'എനിക്കും ചായ വേണം',
      meaning: 'I want tea too',
      kind: 'sentence',
      audio: {
        slow: 'l3u1l5_enikkum-chaaya-venam_slow',
        medium: 'l3u1l5_enikkum-chaaya-venam_medium',
        normal: 'l3u1l5_enikkum-chaaya-venam_normal',
      },
      sentence: {
        bank: ['enikkum', 'chaaya', 'venam', 'enikk'],
        orders: ['enikkum chaaya venam'],
        parts: [
          { word: 'enikkum', meaning: 'to me too' },
          { word: 'chaaya', meaning: 'tea' },
          { word: 'venam', meaning: 'want; need' },
        ],
      },
      notes: ['enikk plus -um: me too, in the wanting sense.'],
      tags: [],
    },
    {
      id: 'njanum-avanum-pokuva',
      manglish: 'njanum avanum pokuva',
      script: 'ഞാനും അവനും പോകുവാ',
      meaning: 'he and I are going',
      kind: 'sentence',
      audio: {
        slow: 'l3u1l5_njanum-avanum-pokuva_slow',
        medium: 'l3u1l5_njanum-avanum-pokuva_medium',
        normal: 'l3u1l5_njanum-avanum-pokuva_normal',
      },
      sentence: {
        bank: ['njanum', 'avanum', 'pokuva', 'njan'],
        orders: ['njanum avanum pokuva'],
        parts: [
          { word: 'njanum', meaning: 'me too' },
          { word: 'avanum', meaning: 'he too' },
          { word: 'pokuva', meaning: 'going' },
        ],
      },
      notes: ['Both people wear -um; together they mean and.'],
      tags: [],
    },
  ],
  minimalPairs: [],
  drills: [
    { kind: 'multipleChoice', itemId: 'njanum', distractors: ['he too', 'we too (you and me)', 'tea too'] },
    { kind: 'multipleChoice', itemId: 'avanum', distractors: ['me too', 'coffee too', 'the bus too'] },
    { kind: 'multipleChoice', itemId: 'nammalum', distractors: ['me too', 'he too', 'tea and coffee'] },
    { kind: 'multipleChoice', itemId: 'chaayayum', distractors: ['coffee too', 'the bus too', 'he too'] },
    { kind: 'multipleChoice', itemId: 'kaappiyum', distractors: ['tea too', 'the bus too', 'we too (you and me)'] },
    { kind: 'multipleChoice', itemId: 'busum', distractors: ['tea too', 'coffee too', 'me too'] },
    { kind: 'multipleChoice', itemId: 'chaayayum-kaappiyum', distractors: ['the older brother and the older sister', 'tea too', 'coffee too'] },
    { kind: 'multipleChoice', itemId: 'chettanum-chechiyum', distractors: ['tea and coffee', 'he too', 'I want tea too'] },
    { kind: 'sentenceBuilder', itemId: 'njanum-pokuva', mode: 'bank' },
    { kind: 'sentenceBuilder', itemId: 'avanum-varunnund', mode: 'bank' },
    { kind: 'sentenceBuilder', itemId: 'enikkum-chaaya-venam', mode: 'bank' },
    { kind: 'sentenceBuilder', itemId: 'njanum-avanum-pokuva', mode: 'bank' },
  ],
  reviewSlots: 0,
  spriteId: 'l3u1l5',
};
