import type { Lesson } from '../types';

/**
 * Level 3 Unit 1 Lesson 6 — the last two case shapes (PLAN.md §5).
 * -aayi: something that just happened, and the everyday "done" (ready aayi).
 * -il ninn: from, the -il you know plus the clipped ninn (the longer
 * ninnu is still accepted as an answer).
 */
export const l3u1l6: Lesson = {
  id: 'l3u1l6',
  levelId: 'l3',
  unitId: 'l3u1',
  title: 'Becoming and from',
  comprehensionOnly: false,
  items: [
    {
      id: 'aayi',
      manglish: 'aayi',
      script: 'ആയി',
      meaning: 'became; done',
      kind: 'word',
      audio: {
        slow: 'l3u1l6_aayi_slow',
        medium: 'l3u1l6_aayi_medium',
        normal: 'l3u1l6_aayi_normal',
      },
      acceptedInputs: ['aayi', 'ayi'],
      notes: ['The just-happened done: it became that way — full aayi, ready aayi.'],
      tags: [],
    },
    {
      id: 'ready-aayi',
      manglish: 'ready aayi',
      script: 'റെഡി ആയി',
      meaning: 'it is ready',
      kind: 'word',
      audio: {
        slow: 'l3u1l6_ready-aayi_slow',
        medium: 'l3u1l6_ready-aayi_medium',
        normal: 'l3u1l6_ready-aayi_normal',
      },
      acceptedInputs: ['ready aayi'],
      notes: ['English ready plus aayi: the getting-ready is finished.'],
      tags: [],
    },
    {
      id: 'ee',
      manglish: 'ee',
      script: 'ഈ',
      meaning: 'this',
      kind: 'word',
      audio: {
        slow: 'l3u1l6_ee_slow',
        medium: 'l3u1l6_ee_medium',
        normal: 'l3u1l6_ee_normal',
      },
      acceptedInputs: ['ee'],
      notes: ['ee leans on a noun: ee bucket, this bucket.'],
      tags: [],
    },
    {
      id: 'chaaya-ready-aayi',
      manglish: 'chaaya ready aayi',
      script: 'ചായ റെഡി ആയി',
      meaning: 'the tea is ready',
      kind: 'sentence',
      audio: {
        slow: 'l3u1l6_chaaya-ready-aayi_slow',
        medium: 'l3u1l6_chaaya-ready-aayi_medium',
        normal: 'l3u1l6_chaaya-ready-aayi_normal',
      },
      sentence: {
        bank: ['chaaya', 'ready', 'aayi', 'full'],
        orders: ['chaaya ready aayi'],
        parts: [
          { word: 'chaaya', meaning: 'tea' },
          { word: 'ready', meaning: 'ready' },
          { word: 'aayi', meaning: 'became; done' },
        ],
      },
      notes: ['The call from the kitchen: chaaya ready aayi.'],
      tags: [],
    },
    {
      id: 'ee-bucket-full-aayi',
      manglish: 'ee bucket full aayi',
      script: 'ഈ ബക്കറ്റ് ഫുൾ ആയി',
      meaning: 'this bucket has been filled',
      kind: 'sentence',
      audio: {
        slow: 'l3u1l6_ee-bucket-full-aayi_slow',
        medium: 'l3u1l6_ee-bucket-full-aayi_medium',
        normal: 'l3u1l6_ee-bucket-full-aayi_normal',
      },
      sentence: {
        bank: ['ee', 'bucket', 'full', 'aayi', 'ready'],
        orders: ['ee bucket full aayi'],
        parts: [
          { word: 'ee', meaning: 'this' },
          { word: 'bucket', meaning: 'bucket' },
          { word: 'full', meaning: 'full' },
          { word: 'aayi', meaning: 'became; done' },
        ],
      },
      notes: ['The model aayi: the filling just happened — ee bucket full aayi.'],
      tags: [],
    },
    {
      id: 'njan-ready-aayi',
      manglish: 'njan ready aayi',
      script: 'ഞാൻ റെഡി ആയി',
      meaning: 'I am ready now',
      kind: 'sentence',
      audio: {
        slow: 'l3u1l6_njan-ready-aayi_slow',
        medium: 'l3u1l6_njan-ready-aayi_medium',
        normal: 'l3u1l6_njan-ready-aayi_normal',
      },
      sentence: {
        bank: ['njan', 'ready', 'aayi', 'avan'],
        orders: ['njan ready aayi'],
        parts: [
          { word: 'njan', meaning: 'I' },
          { word: 'ready', meaning: 'ready' },
          { word: 'aayi', meaning: 'became; done' },
        ],
      },
      notes: [
        'Ready aayi is ready now — the getting-ready is over.',
        'Njan ready aa just says it is so; aayi says it just got that way.',
      ],
      tags: [],
    },
    {
      id: 'officil-ninnu',
      manglish: 'officil ninn',
      script: 'ഓഫീസിൽ നിന്ന്',
      meaning: 'from the office',
      kind: 'word',
      audio: {
        slow: 'l3u1l6_officil-ninnu_slow',
        medium: 'l3u1l6_officil-ninnu_medium',
        normal: 'l3u1l6_officil-ninnu_normal',
      },
      acceptedInputs: ['officil ninn', 'officil ninnu'],
      notes: ['The -il you know plus ninn: out of the office. The longer ninnu still lands.'],
      tags: [],
    },
    {
      id: 'veettil-ninnu',
      manglish: 'veettil ninn',
      script: 'വീട്ടിൽ നിന്ന്',
      meaning: 'from home',
      kind: 'word',
      audio: {
        slow: 'l3u1l6_veettil-ninnu_slow',
        medium: 'l3u1l6_veettil-ninnu_medium',
        normal: 'l3u1l6_veettil-ninnu_normal',
      },
      acceptedInputs: ['veettil ninn', 'veettil ninnu'],
      notes: ['veettil, at home, plus ninn: from home.'],
      tags: [],
    },
    {
      id: 'busil-ninnu',
      manglish: 'busil ninn',
      script: 'ബസ്സിൽ നിന്ന്',
      meaning: 'from the bus',
      kind: 'word',
      audio: {
        slow: 'l3u1l6_busil-ninnu_slow',
        medium: 'l3u1l6_busil-ninnu_medium',
        normal: 'l3u1l6_busil-ninnu_normal',
      },
      acceptedInputs: ['busil ninn', 'busil ninnu'],
      notes: ['English words take the whole pair: busil ninn, down from the bus.'],
      tags: [],
    },
    {
      id: 'classil-ninnu',
      manglish: 'classil ninn',
      script: 'ക്ലാസ്സിൽ നിന്ന്',
      meaning: 'from class',
      kind: 'word',
      audio: {
        slow: 'l3u1l6_classil-ninnu_slow',
        medium: 'l3u1l6_classil-ninnu_medium',
        normal: 'l3u1l6_classil-ninnu_normal',
      },
      acceptedInputs: ['classil ninn', 'classil ninnu'],
      notes: ['Class takes the same pair, straight on the English word: classil ninn.'],
      tags: [],
    },
    {
      id: 'aarokke',
      manglish: 'aarokke',
      script: 'ആരൊക്കെ',
      meaning: 'who all',
      kind: 'word',
      audio: {
        slow: 'l3u1l6_aarokke_slow',
        medium: 'l3u1l6_aarokke_medium',
        normal: 'l3u1l6_aarokke_normal',
      },
      acceptedInputs: ['aarokke'],
      notes: ['aaru, who, plus -okke: aarokke, who all.'],
      tags: [],
    },
    {
      id: 'njan-officil-ninn-irangi',
      manglish: 'njan officil ninn irangi',
      script: 'ഞാൻ ഓഫീസിൽ നിന്ന് ഇറങ്ങി',
      meaning: 'I just left the office',
      kind: 'sentence',
      audio: {
        slow: 'l3u1l6_njan-officil-ninn-irangi_slow',
        medium: 'l3u1l6_njan-officil-ninn-irangi_medium',
        normal: 'l3u1l6_njan-officil-ninn-irangi_normal',
      },
      sentence: {
        bank: ['njan', 'officil', 'ninn', 'irangi', 'pokuva'],
        orders: ['njan officil ninn irangi'],
        parts: [
          { word: 'njan', meaning: 'I' },
          { word: 'officil', meaning: 'at the office' },
          { word: 'ninn', meaning: 'from' },
          { word: 'irangi', meaning: 'left; set off' },
        ],
      },
      notes: ['The from-frame you met at home, now at the office.'],
      tags: [],
    },
    {
      id: 'avan-busil-ninn-irangi',
      manglish: 'avan busil ninn irangi',
      script: 'അവൻ ബസ്സിൽ നിന്ന് ഇറങ്ങി',
      meaning: 'he got off the bus',
      kind: 'sentence',
      audio: {
        slow: 'l3u1l6_avan-busil-ninn-irangi_slow',
        medium: 'l3u1l6_avan-busil-ninn-irangi_medium',
        normal: 'l3u1l6_avan-busil-ninn-irangi_normal',
      },
      sentence: {
        bank: ['avan', 'busil', 'ninn', 'irangi', 'njan'],
        orders: ['avan busil ninn irangi'],
        parts: [
          { word: 'avan', meaning: 'he' },
          { word: 'busil', meaning: 'on the bus' },
          { word: 'ninn', meaning: 'from' },
          { word: 'irangi', meaning: 'left; set off' },
        ],
      },
      notes: ['Getting down is irangi too: off the bus, on the way.'],
      tags: [],
    },
    {
      id: 'ninte-veettil-ninn-aarokke-varunnund',
      manglish: 'ninte veettil ninn aarokke varunnund',
      script: 'നിന്റെ വീട്ടിൽ നിന്ന് ആരൊക്കെ വരുന്നുണ്ട്',
      meaning: 'who all are coming from your house?',
      kind: 'sentence',
      audio: {
        slow: 'l3u1l6_ninte-veettil-ninn-aarokke-varunnund_slow',
        medium: 'l3u1l6_ninte-veettil-ninn-aarokke-varunnund_medium',
        normal: 'l3u1l6_ninte-veettil-ninn-aarokke-varunnund_normal',
      },
      sentence: {
        bank: ['ninte', 'veettil', 'ninn', 'aarokke', 'varunnund', 'njan'],
        orders: ['ninte veettil ninn aarokke varunnund'],
        parts: [
          { word: 'ninte', meaning: 'your' },
          { word: 'veettil', meaning: 'home' },
          { word: 'ninn', meaning: 'from' },
          { word: 'aarokke', meaning: 'who all' },
          { word: 'varunnund', meaning: 'is coming' },
        ],
      },
      notes: ['Asking about a whole group: aarokke, who all.'],
      tags: [],
    },
  ],
  minimalPairs: [],
  drills: [
    { kind: 'multipleChoice', itemId: 'aayi', distractors: ['it is ready', 'from the office', 'from home'] },
    { kind: 'multipleChoice', itemId: 'ready-aayi', distractors: ['became; done', 'from the bus', 'from class'] },
    { kind: 'multipleChoice', itemId: 'ee', distractors: ['who all', 'from home', 'became; done'] },
    { kind: 'sentenceBuilder', itemId: 'chaaya-ready-aayi', mode: 'bank' },
    { kind: 'sentenceBuilder', itemId: 'ee-bucket-full-aayi', mode: 'bank' },
    { kind: 'sentenceBuilder', itemId: 'njan-ready-aayi', mode: 'bank' },
    { kind: 'multipleChoice', itemId: 'officil-ninnu', distractors: ['from home', 'from the bus', 'it is ready'] },
    { kind: 'multipleChoice', itemId: 'veettil-ninnu', distractors: ['from the office', 'from class', 'became; done'] },
    { kind: 'multipleChoice', itemId: 'busil-ninnu', distractors: ['from class', 'from the office', 'it is ready'] },
    { kind: 'multipleChoice', itemId: 'classil-ninnu', distractors: ['from the bus', 'from home', 'became; done'] },
    { kind: 'multipleChoice', itemId: 'aarokke', distractors: ['this', 'from class', 'it is ready'] },
    { kind: 'sentenceBuilder', itemId: 'njan-officil-ninn-irangi', mode: 'bank' },
    { kind: 'sentenceBuilder', itemId: 'avan-busil-ninn-irangi', mode: 'bank' },
    { kind: 'sentenceBuilder', itemId: 'ninte-veettil-ninn-aarokke-varunnund', mode: 'bank' },
  ],
  reviewSlots: 0,
  spriteId: 'l3u1l6',
};
