import type { Lesson } from '../types';

/**
 * Level 3 Unit 1 Lesson 1 — the -il suffix (PLAN.md §5): in, at, on.
 * The flagship pattern is English words taking Malayalam suffixes:
 * officil, shoppil, busil, classil — exactly how Kerala talks.
 */
export const l3u1l1: Lesson = {
  id: 'l3u1l1',
  levelId: 'l3',
  unitId: 'l3u1',
  title: 'In, at, on',
  comprehensionOnly: false,
  items: [
    {
      id: 'officil',
      manglish: 'officil',
      script: 'ഓഫീസിൽ',
      meaning: 'at the office',
      kind: 'word',
      audio: {
        slow: 'l3u1l1_officil_slow',
        medium: 'l3u1l1_officil_medium',
        normal: 'l3u1l1_officil_normal',
      },
      acceptedInputs: ['officil'],
      notes: ['The English word office takes the Malayalam -il: in or at.'],
      tags: [],
    },
    {
      id: 'shoppil',
      manglish: 'shoppil',
      script: 'ഷോപ്പിൽ',
      meaning: 'in the shop',
      kind: 'word',
      audio: {
        slow: 'l3u1l1_shoppil_slow',
        medium: 'l3u1l1_shoppil_medium',
        normal: 'l3u1l1_shoppil_normal',
        focus: ['l3u1l1_shoppil_focus'],
      },
      acceptedInputs: ['shoppil'],
      articulation: {
        cue: 'Hold the doubled pp before the -il.',
      },
      notes: ['Same suffix on shop — hold the doubled pp before it.'],
      tags: ['sound:geminate'],
    },
    {
      id: 'busil',
      manglish: 'busil',
      script: 'ബസ്സിൽ',
      meaning: 'on the bus',
      kind: 'word',
      audio: {
        slow: 'l3u1l1_busil_slow',
        medium: 'l3u1l1_busil_medium',
        normal: 'l3u1l1_busil_normal',
      },
      acceptedInputs: ['busil'],
      notes: ['On the bus is busil — vehicles take -il in everyday speech.'],
      tags: [],
    },
    {
      id: 'classil',
      manglish: 'classil',
      script: 'ക്ലാസ്സിൽ',
      meaning: 'in class',
      kind: 'word',
      audio: {
        slow: 'l3u1l1_classil_slow',
        medium: 'l3u1l1_classil_medium',
        normal: 'l3u1l1_classil_normal',
      },
      acceptedInputs: ['classil'],
      notes: ['In class, in the classroom — classil.'],
      tags: [],
    },
    {
      id: 'hottelil',
      manglish: 'hottelil',
      script: 'ഹോട്ടലിൽ',
      meaning: 'in the hotel',
      kind: 'word',
      audio: {
        slow: 'l3u1l1_hottelil_slow',
        medium: 'l3u1l1_hottelil_medium',
        normal: 'l3u1l1_hottelil_normal',
        focus: ['l3u1l1_hottelil_focus'],
      },
      acceptedInputs: ['hottelil', 'hotelil'],
      articulation: {
        cue: 'Hold the doubled tt before the -il.',
      },
      notes: ['Hotel keeps its double tt in Malayalam: hottel, then -il.'],
      tags: ['sound:geminate'],
    },
    {
      id: 'njan-officil-pokuva',
      manglish: 'njan officil pokuva',
      script: 'ഞാൻ ഓഫീസിൽ പോകുവാ',
      meaning: 'I am going to the office',
      kind: 'sentence',
      audio: {
        slow: 'l3u1l1_njan-officil-pokuva_slow',
        medium: 'l3u1l1_njan-officil-pokuva_medium',
        normal: 'l3u1l1_njan-officil-pokuva_normal',
      },
      sentence: {
        bank: ['njan', 'officil', 'pokuva', 'varuva'],
        orders: ['njan officil pokuva'],
        parts: [
          { word: 'njan', meaning: 'I' },
          { word: 'officil', meaning: 'at the office' },
          { word: 'pokuva', meaning: 'going' },
        ],
      },
      notes: ['The frame: person + place-il + verb. The -il does the going-to here.'],
      tags: [],
    },
    {
      id: 'njan-busil-varuva',
      manglish: 'njan busil varuva',
      script: 'ഞാൻ ബസ്സിൽ വരുവാ',
      meaning: 'I am coming by bus',
      kind: 'sentence',
      audio: {
        slow: 'l3u1l1_njan-busil-varuva_slow',
        medium: 'l3u1l1_njan-busil-varuva_medium',
        normal: 'l3u1l1_njan-busil-varuva_normal',
      },
      sentence: {
        bank: ['njan', 'busil', 'varuva', 'pokuva'],
        orders: ['njan busil varuva'],
        parts: [
          { word: 'njan', meaning: 'I' },
          { word: 'busil', meaning: 'on the bus' },
          { word: 'varuva', meaning: 'coming' },
        ],
      },
      notes: ['Busil means by bus here — the suffix covers how you travel.'],
      tags: [],
    },
    {
      id: 'njan-classil-irikkuva',
      manglish: 'njan classil irikkuva',
      script: 'ഞാൻ ക്ലാസ്സിൽ ഇരിക്കുവാ',
      meaning: 'I am sitting in class',
      kind: 'sentence',
      audio: {
        slow: 'l3u1l1_njan-classil-irikkuva_slow',
        medium: 'l3u1l1_njan-classil-irikkuva_medium',
        normal: 'l3u1l1_njan-classil-irikkuva_normal',
      },
      sentence: {
        bank: ['njan', 'classil', 'irikkuva', 'pokuva'],
        orders: ['njan classil irikkuva'],
        parts: [
          { word: 'njan', meaning: 'I' },
          { word: 'classil', meaning: 'in class' },
          { word: 'irikkuva', meaning: 'sitting' },
        ],
      },
      notes: ['Irikkuva from Level 2 does the sitting; -il does the where.'],
      tags: [],
    },
    {
      id: 'njan-shoppil-pokuva',
      manglish: 'njan shoppil pokuva',
      script: 'ഞാൻ ഷോപ്പിൽ പോകുവാ',
      meaning: 'I am going to the shop',
      kind: 'sentence',
      audio: {
        slow: 'l3u1l1_njan-shoppil-pokuva_slow',
        medium: 'l3u1l1_njan-shoppil-pokuva_medium',
        normal: 'l3u1l1_njan-shoppil-pokuva_normal',
      },
      sentence: {
        bank: ['njan', 'shoppil', 'pokuva', 'irikkuva'],
        orders: ['njan shoppil pokuva'],
        parts: [
          { word: 'njan', meaning: 'I' },
          { word: 'shoppil', meaning: 'in the shop' },
          { word: 'pokuva', meaning: 'going' },
        ],
      },
      notes: ['The same frame with a different place.'],
      tags: [],
    },
  ],
  minimalPairs: [],
  drills: [
    { kind: 'multipleChoice', itemId: 'officil', distractors: ['in the shop', 'on the bus', 'in class'] },
    { kind: 'multipleChoice', itemId: 'shoppil', distractors: ['at the office', 'on the bus', 'in the hotel'] },
    { kind: 'multipleChoice', itemId: 'busil', distractors: ['at the office', 'in the shop', 'in class'] },
    { kind: 'multipleChoice', itemId: 'classil', distractors: ['at the office', 'in the shop', 'in the hotel'] },
    { kind: 'multipleChoice', itemId: 'hottelil', distractors: ['at the office', 'in class', 'on the bus'] },
    { kind: 'sentenceBuilder', itemId: 'njan-officil-pokuva', mode: 'bank' },
    { kind: 'sentenceBuilder', itemId: 'njan-busil-varuva', mode: 'bank' },
    { kind: 'sentenceBuilder', itemId: 'njan-classil-irikkuva', mode: 'bank' },
    { kind: 'sentenceBuilder', itemId: 'njan-shoppil-pokuva', mode: 'bank' },
  ],
  reviewSlots: 0,
  spriteId: 'l3u1l1',
};
