import type { Lesson } from '../types';

/**
 * Level 3 Unit 1 Lesson 1 — the -il suffix (PLAN.md §5): in, at, on.
 * The flagship pattern is English words taking Malayalam suffixes:
 * officil, busil, classil, and the native kada — exactly how Kerala talks.
 */
export const l3u1l1: Lesson = {
  id: 'l3u1l1',
  levelId: 'l3',
  unitId: 'l3u1',
  title: 'In, at, on',
  comprehensionOnly: false,
  items: [
    {
      id: 'officil',
      manglish: 'officil',
      script: 'ഓഫീസിൽ',
      meaning: 'at the office',
      kind: 'word',
      audio: {
        slow: 'l3u1l1_officil_slow',
        medium: 'l3u1l1_officil_medium',
        normal: 'l3u1l1_officil_normal',
      },
      acceptedInputs: ['officil'],
      notes: ['The English word office takes the Malayalam -il: in or at.'],
      tags: [],
    },
    {
      id: 'kada',
      manglish: 'kada',
      script: 'കട',
      meaning: 'shop',
      kind: 'word',
      audio: {
        slow: 'l3u1l1_kada_slow',
        medium: 'l3u1l1_kada_medium',
        normal: 'l3u1l1_kada_normal',
      },
      acceptedInputs: ['kada'],
      notes: ['The native word for shop — the corner shop of every Kerala street.'],
      tags: [],
    },
    {
      id: 'kadayil',
      manglish: 'kadayil',
      script: 'കടയിൽ',
      meaning: 'in the shop',
      kind: 'word',
      audio: {
        slow: 'l3u1l1_kadayil_slow',
        medium: 'l3u1l1_kadayil_medium',
        normal: 'l3u1l1_kadayil_normal',
      },
      acceptedInputs: ['kadayil'],
      notes: ['Kada takes the -il: kadayil, in the shop.'],
      tags: [],
    },
    {
      id: 'busil',
      manglish: 'busil',
      script: 'ബസ്സിൽ',
      meaning: 'on the bus',
      kind: 'word',
      audio: {
        slow: 'l3u1l1_busil_slow',
        medium: 'l3u1l1_busil_medium',
        normal: 'l3u1l1_busil_normal',
      },
      acceptedInputs: ['busil'],
      notes: ['On the bus is busil — vehicles take -il in everyday speech.'],
      tags: [],
    },
    {
      id: 'classil',
      manglish: 'classil',
      script: 'ക്ലാസ്സിൽ',
      meaning: 'in class',
      kind: 'word',
      audio: {
        slow: 'l3u1l1_classil_slow',
        medium: 'l3u1l1_classil_medium',
        normal: 'l3u1l1_classil_normal',
      },
      acceptedInputs: ['classil'],
      notes: ['In class, in the classroom — classil.'],
      tags: [],
    },
    {
      id: 'hotelil',
      manglish: 'hotelil',
      script: 'ഹോട്ടലിൽ',
      meaning: 'in the hotel',
      kind: 'word',
      audio: {
        slow: 'l3u1l1_hotelil_slow',
        medium: 'l3u1l1_hotelil_medium',
        normal: 'l3u1l1_hotelil_normal',
        focus: ['l3u1l1_hotelil_focus'],
      },
      acceptedInputs: ['hotelil', 'hottelil'],
      articulation: {
        cue: 'Hold the doubled tt before the -il.',
      },
      notes: [
        'Hotel keeps its English single t in writing; the script doubles it.',
        'In Kerala a hotel means an eatery — think restaurant, not a place to sleep.',
      ],
      tags: ['sound:geminate'],
    },
    {
      id: 'njan-officil-pokuva',
      manglish: 'njan officil pokuva',
      script: 'ഞാൻ ഓഫീസിൽ പോകുവാ',
      meaning: 'I am going to the office',
      kind: 'sentence',
      audio: {
        slow: 'l3u1l1_njan-officil-pokuva_slow',
        medium: 'l3u1l1_njan-officil-pokuva_medium',
        normal: 'l3u1l1_njan-officil-pokuva_normal',
      },
      sentence: {
        bank: ['njan', 'officil', 'pokuva', 'varuva'],
        orders: ['njan officil pokuva'],
        parts: [
          { word: 'njan', meaning: 'I' },
          { word: 'officil', meaning: 'at the office' },
          { word: 'pokuva', meaning: 'going' },
        ],
      },
      notes: ['The frame: person + place-il + verb. The -il does the going-to here.'],
      tags: [],
    },
    {
      id: 'njan-angott-varuva',
      manglish: 'njan angott varuva',
      script: 'ഞാൻ അങ്ങോട്ട് വരുവാ',
      meaning: 'I am coming there',
      kind: 'sentence',
      audio: {
        slow: 'l3u1l1_njan-angott-varuva_slow',
        medium: 'l3u1l1_njan-angott-varuva_medium',
        normal: 'l3u1l1_njan-angott-varuva_normal',
      },
      sentence: {
        bank: ['njan', 'angott', 'varuva', 'pokuva'],
        orders: ['njan angott varuva'],
        parts: [
          { word: 'njan', meaning: 'I' },
          { word: 'angott', meaning: 'to there; that way' },
          { word: 'varuva', meaning: 'coming' },
        ],
      },
      notes: ['Angott points the way: coming there.'],
      tags: [],
    },
    {
      id: 'njan-classil-irikkuva',
      manglish: 'njan classil irikkuva',
      script: 'ഞാൻ ക്ലാസ്സിൽ ഇരിക്കുവാ',
      meaning: 'I am sitting in class',
      kind: 'sentence',
      audio: {
        slow: 'l3u1l1_njan-classil-irikkuva_slow',
        medium: 'l3u1l1_njan-classil-irikkuva_medium',
        normal: 'l3u1l1_njan-classil-irikkuva_normal',
      },
      sentence: {
        bank: ['njan', 'classil', 'irikkuva', 'pokuva'],
        orders: ['njan classil irikkuva'],
        parts: [
          { word: 'njan', meaning: 'I' },
          { word: 'classil', meaning: 'in class' },
          { word: 'irikkuva', meaning: 'sitting' },
        ],
      },
      notes: ['Irikkuva from Level 2 does the sitting; -il does the where.'],
      tags: [],
    },
    {
      id: 'njan-kadayil-pokuva',
      manglish: 'njan kadayil pokuva',
      script: 'ഞാൻ കടയിൽ പോകുവാ',
      meaning: 'I am going to the shop',
      kind: 'sentence',
      audio: {
        slow: 'l3u1l1_njan-kadayil-pokuva_slow',
        medium: 'l3u1l1_njan-kadayil-pokuva_medium',
        normal: 'l3u1l1_njan-kadayil-pokuva_normal',
      },
      sentence: {
        bank: ['njan', 'kadayil', 'pokuva', 'irikkuva'],
        orders: ['njan kadayil pokuva'],
        parts: [
          { word: 'njan', meaning: 'I' },
          { word: 'kadayil', meaning: 'in the shop' },
          { word: 'pokuva', meaning: 'going' },
        ],
      },
      notes: ['The same frame with the native shop.'],
      tags: [],
    },
  ],
  minimalPairs: [],
  drills: [
    { kind: 'multipleChoice', itemId: 'officil', distractors: ['shop', 'on the bus', 'in class'] },
    { kind: 'multipleChoice', itemId: 'kada', distractors: ['at the office', 'on the bus', 'in class'] },
    { kind: 'multipleChoice', itemId: 'kadayil', distractors: ['at the office', 'on the bus', 'in the hotel'] },
    { kind: 'multipleChoice', itemId: 'busil', distractors: ['at the office', 'in the shop', 'in class'] },
    { kind: 'multipleChoice', itemId: 'classil', distractors: ['at the office', 'in the shop', 'in the hotel'] },
    { kind: 'multipleChoice', itemId: 'hotelil', distractors: ['at the office', 'in class', 'on the bus'] },
    { kind: 'sentenceBuilder', itemId: 'njan-officil-pokuva', mode: 'bank' },
    { kind: 'sentenceBuilder', itemId: 'njan-angott-varuva', mode: 'bank' },
    { kind: 'sentenceBuilder', itemId: 'njan-classil-irikkuva', mode: 'bank' },
    { kind: 'sentenceBuilder', itemId: 'njan-kadayil-pokuva', mode: 'bank' },
  ],
  reviewSlots: 0,
  spriteId: 'l3u1l1',
};
