import type { Lesson } from '../types';

/**
 * Level 3 Unit 1 Lesson 3 — the -ilekk suffix (PLAN.md §5): heading to.
 * The directional form on English bases: hotelilekk, officeilekk —
 * plus the full frame person + place + verb.
 */
export const l3u1l3: Lesson = {
  id: 'l3u1l3',
  levelId: 'l3',
  unitId: 'l3u1',
  title: 'Heading to',
  comprehensionOnly: false,
  items: [
    {
      id: 'hottelilekk',
      manglish: 'hottelilekk',
      script: 'ഹോട്ടലിലേക്ക്',
      meaning: 'to the hotel',
      kind: 'word',
      audio: {
        slow: 'l3u1l3_hottelilekk_slow',
        medium: 'l3u1l3_hottelilekk_medium',
        normal: 'l3u1l3_hottelilekk_normal',
      },
      acceptedInputs: ['hottelilekk', 'hotelilekk'],
      notes: ['-ilekk points the direction: heading to the hotel.'],
      tags: [],
    },
    {
      id: 'officeilekk',
      manglish: 'officeilekk',
      script: 'ഓഫീസിലേക്ക്',
      meaning: 'to the office',
      kind: 'word',
      audio: {
        slow: 'l3u1l3_officeilekk_slow',
        medium: 'l3u1l3_officeilekk_medium',
        normal: 'l3u1l3_officeilekk_normal',
      },
      acceptedInputs: ['officeilekk'],
      notes: ['Same suffix on office: officeilekk.'],
      tags: [],
    },
    {
      id: 'shoppilekk',
      manglish: 'shoppilekk',
      script: 'ഷോപ്പിലേക്ക്',
      meaning: 'to the shop',
      kind: 'word',
      audio: {
        slow: 'l3u1l3_shoppilekk_slow',
        medium: 'l3u1l3_shoppilekk_medium',
        normal: 'l3u1l3_shoppilekk_normal',
      },
      acceptedInputs: ['shoppilekk'],
      notes: ['And on shop: shoppilekk.'],
      tags: [],
    },
    {
      id: 'busilekk',
      manglish: 'busilekk',
      script: 'ബസ്സിലേക്ക്',
      meaning: 'to the bus',
      kind: 'word',
      audio: {
        slow: 'l3u1l3_busilekk_slow',
        medium: 'l3u1l3_busilekk_medium',
        normal: 'l3u1l3_busilekk_normal',
      },
      acceptedInputs: ['busilekk'],
      notes: ['To the bus — when you are walking toward it.'],
      tags: [],
    },
    {
      id: 'njan-hottelilekk-pokuva',
      manglish: 'njan hottelilekk pokuva',
      script: 'ഞാൻ ഹോട്ടലിലേക്ക് പോകുവാ',
      meaning: 'I am going to the hotel',
      kind: 'sentence',
      audio: {
        slow: 'l3u1l3_njan-hottelilekk-pokuva_slow',
        medium: 'l3u1l3_njan-hottelilekk-pokuva_medium',
        normal: 'l3u1l3_njan-hottelilekk-pokuva_normal',
      },
      sentence: {
        bank: ['njan', 'hottelilekk', 'pokuva', 'hottelil'],
        orders: ['njan hottelilekk pokuva'],
        parts: [
          { word: 'njan', meaning: 'I' },
          { word: 'hottelilekk', meaning: 'to the hotel' },
          { word: 'pokuva', meaning: 'going' },
        ],
      },
      notes: ['The frame again, with the directional suffix.'],
      tags: [],
    },
    {
      id: 'avan-officeilekk-pokuva',
      manglish: 'avan officeilekk pokuva',
      script: 'അവൻ ഓഫീസിലേക്ക് പോകുവാ',
      meaning: 'he is going to the office',
      kind: 'sentence',
      audio: {
        slow: 'l3u1l3_avan-officeilekk-pokuva_slow',
        medium: 'l3u1l3_avan-officeilekk-pokuva_medium',
        normal: 'l3u1l3_avan-officeilekk-pokuva_normal',
      },
      sentence: {
        bank: ['avan', 'officeilekk', 'pokuva', 'officekku'],
        orders: ['avan officeilekk pokuva'],
        parts: [
          { word: 'avan', meaning: 'he' },
          { word: 'officeilekk', meaning: 'to the office' },
          { word: 'pokuva', meaning: 'going' },
        ],
      },
      notes: ['-ilekk and -kku both say to — -ilekk points the direction, -kku is the dative.'],
      tags: [],
    },
    {
      id: 'nammal-hottelilekk-pokuva',
      manglish: 'nammaḷ hottelilekk pokuva',
      script: 'നമ്മൾ ഹോട്ടലിലേക്ക് പോകുവാ',
      meaning: 'we are going to the hotel',
      kind: 'sentence',
      audio: {
        slow: 'l3u1l3_nammal-hottelilekk-pokuva_slow',
        medium: 'l3u1l3_nammal-hottelilekk-pokuva_medium',
        normal: 'l3u1l3_nammal-hottelilekk-pokuva_normal',
      },
      sentence: {
        bank: ['nammaḷ', 'hottelilekk', 'pokuva', 'shoppilekk'],
        orders: ['nammaḷ hottelilekk pokuva'],
        parts: [
          { word: 'nammaḷ', meaning: 'we (you and me)' },
          { word: 'hottelilekk', meaning: 'to the hotel' },
          { word: 'pokuva', meaning: 'going' },
        ],
      },
      notes: ['Planning the evening with the inclusive we.'],
      tags: [],
    },
    {
      id: 'njan-busilekk-pokuva',
      manglish: 'njan busilekk pokuva',
      script: 'ഞാൻ ബസ്സിലേക്ക് പോകുവാ',
      meaning: 'I am going to the bus',
      kind: 'sentence',
      audio: {
        slow: 'l3u1l3_njan-busilekk-pokuva_slow',
        medium: 'l3u1l3_njan-busilekk-pokuva_medium',
        normal: 'l3u1l3_njan-busilekk-pokuva_normal',
      },
      sentence: {
        bank: ['njan', 'busilekk', 'pokuva', 'busil'],
        orders: ['njan busilekk pokuva'],
        parts: [
          { word: 'njan', meaning: 'I' },
          { word: 'busilekk', meaning: 'to the bus' },
          { word: 'pokuva', meaning: 'going' },
        ],
      },
      notes: ['Heading toward the bus, not riding it — busil was the riding.'],
      tags: [],
    },
    {
      id: 'avan-shoppilekk-pokuva',
      manglish: 'avan shoppilekk pokuva',
      script: 'അവൻ ഷോപ്പിലേക്ക് പോകുവാ',
      meaning: 'he is going to the shop',
      kind: 'sentence',
      audio: {
        slow: 'l3u1l3_avan-shoppilekk-pokuva_slow',
        medium: 'l3u1l3_avan-shoppilekk-pokuva_medium',
        normal: 'l3u1l3_avan-shoppilekk-pokuva_normal',
      },
      sentence: {
        bank: ['avan', 'shoppilekk', 'pokuva', 'officil'],
        orders: ['avan shoppilekk pokuva'],
        parts: [
          { word: 'avan', meaning: 'he' },
          { word: 'shoppilekk', meaning: 'to the shop' },
          { word: 'pokuva', meaning: 'going' },
        ],
      },
      notes: ['One more frame, one more place.'],
      tags: [],
    },
  ],
  minimalPairs: [],
  drills: [
    { kind: 'multipleChoice', itemId: 'hottelilekk', distractors: ['to the office', 'to the shop', 'to the bus'] },
    { kind: 'multipleChoice', itemId: 'officeilekk', distractors: ['to the hotel', 'to the shop', 'to the bus'] },
    { kind: 'multipleChoice', itemId: 'shoppilekk', distractors: ['to the hotel', 'to the office', 'to the bus'] },
    { kind: 'multipleChoice', itemId: 'busilekk', distractors: ['to the hotel', 'to the office', 'to the shop'] },
    { kind: 'sentenceBuilder', itemId: 'njan-hottelilekk-pokuva', mode: 'bank' },
    { kind: 'sentenceBuilder', itemId: 'avan-officeilekk-pokuva', mode: 'bank' },
    { kind: 'sentenceBuilder', itemId: 'nammal-hottelilekk-pokuva', mode: 'bank' },
    { kind: 'sentenceBuilder', itemId: 'njan-busilekk-pokuva', mode: 'bank' },
    { kind: 'sentenceBuilder', itemId: 'avan-shoppilekk-pokuva', mode: 'bank' },
  ],
  reviewSlots: 0,
  spriteId: 'l3u1l3',
};
