import type { Lesson } from '../types';

/**
 * Level 3 Unit 1 Lesson 6 — the last two case shapes (PLAN.md §5).
 * -aayi: becoming something and the everyday "done" (ready aayi).
 * -il ninnu: from, the -il you know plus ninnu, matching the ninn
 * short form already taught in njan veettil ninn irangi.
 */
export const l3u1l6: Lesson = {
  id: 'l3u1l6',
  levelId: 'l3',
  unitId: 'l3u1',
  title: 'Becoming and from',
  comprehensionOnly: false,
  items: [
    {
      id: 'aayi',
      manglish: 'aayi',
      script: 'ആയി',
      meaning: 'became; done',
      kind: 'word',
      audio: {
        slow: 'l3u1l6_aayi_slow',
        medium: 'l3u1l6_aayi_medium',
        normal: 'l3u1l6_aayi_normal',
      },
      acceptedInputs: ['aayi', 'ayi'],
      notes: ['Became, turned into, and the everyday all-purpose done: aayi.'],
      tags: [],
    },
    {
      id: 'ready-aayi',
      manglish: 'ready aayi',
      script: 'റെഡി ആയി',
      meaning: 'it is ready',
      kind: 'word',
      audio: {
        slow: 'l3u1l6_ready-aayi_slow',
        medium: 'l3u1l6_ready-aayi_medium',
        normal: 'l3u1l6_ready-aayi_normal',
      },
      acceptedInputs: ['ready aayi'],
      notes: ['English ready plus aayi: the getting-ready is finished.'],
      tags: [],
    },
    {
      id: 'chaaya-ready-aayi',
      manglish: 'chaaya ready aayi',
      script: 'ചായ റെഡി ആയി',
      meaning: 'the tea is ready',
      kind: 'sentence',
      audio: {
        slow: 'l3u1l6_chaaya-ready-aayi_slow',
        medium: 'l3u1l6_chaaya-ready-aayi_medium',
        normal: 'l3u1l6_chaaya-ready-aayi_normal',
      },
      sentence: {
        bank: ['chaaya', 'ready', 'aayi', 'teacher'],
        orders: ['chaaya ready aayi'],
        parts: [
          { word: 'chaaya', meaning: 'tea' },
          { word: 'ready', meaning: 'ready' },
          { word: 'aayi', meaning: 'became; done' },
        ],
      },
      notes: ['The call from the kitchen: chaaya ready aayi.'],
      tags: [],
    },
    {
      id: 'avan-teacher-aayi',
      manglish: 'avan teacher aayi',
      script: 'അവൻ ടീച്ചർ ആയി',
      meaning: 'he became a teacher',
      kind: 'sentence',
      audio: {
        slow: 'l3u1l6_avan-teacher-aayi_slow',
        medium: 'l3u1l6_avan-teacher-aayi_medium',
        normal: 'l3u1l6_avan-teacher-aayi_normal',
      },
      sentence: {
        bank: ['avan', 'teacher', 'aayi', 'chaaya'],
        orders: ['avan teacher aayi'],
        parts: [
          { word: 'avan', meaning: 'he' },
          { word: 'teacher', meaning: 'teacher' },
          { word: 'aayi', meaning: 'became; done' },
        ],
      },
      notes: ['Becoming something: the new role takes aayi. English words slot straight in.'],
      tags: [],
    },
    {
      id: 'njan-ready-aayi',
      manglish: 'njan ready aayi',
      script: 'ഞാൻ റെഡി ആയി',
      meaning: 'I am ready now',
      kind: 'sentence',
      audio: {
        slow: 'l3u1l6_njan-ready-aayi_slow',
        medium: 'l3u1l6_njan-ready-aayi_medium',
        normal: 'l3u1l6_njan-ready-aayi_normal',
      },
      sentence: {
        bank: ['njan', 'ready', 'aayi', 'teacher'],
        orders: ['njan ready aayi'],
        parts: [
          { word: 'njan', meaning: 'I' },
          { word: 'ready', meaning: 'ready' },
          { word: 'aayi', meaning: 'became; done' },
        ],
      },
      notes: [
        'Ready aayi is ready now — the getting-ready is over.',
        'Njan ready aa just says it is so; aayi says it just got that way.',
      ],
      tags: [],
    },
    {
      id: 'officil-ninnu',
      manglish: 'officil ninnu',
      script: 'ഓഫീസിൽ നിന്ന്',
      meaning: 'from the office',
      kind: 'word',
      audio: {
        slow: 'l3u1l6_officil-ninnu_slow',
        medium: 'l3u1l6_officil-ninnu_medium',
        normal: 'l3u1l6_officil-ninnu_normal',
      },
      acceptedInputs: ['officil ninnu', 'officil ninn'],
      notes: ['The -il you know plus ninnu: out of the office. Fast speech clips it to ninn.'],
      tags: [],
    },
    {
      id: 'veettil-ninnu',
      manglish: 'veettil ninnu',
      script: 'വീട്ടിൽ നിന്ന്',
      meaning: 'from home',
      kind: 'word',
      audio: {
        slow: 'l3u1l6_veettil-ninnu_slow',
        medium: 'l3u1l6_veettil-ninnu_medium',
        normal: 'l3u1l6_veettil-ninnu_normal',
      },
      acceptedInputs: ['veettil ninnu', 'veettil ninn'],
      notes: ['veettil, at home, plus ninnu: from home.'],
      tags: [],
    },
    {
      id: 'busil-ninnu',
      manglish: 'busil ninnu',
      script: 'ബസ്സിൽ നിന്ന്',
      meaning: 'from the bus',
      kind: 'word',
      audio: {
        slow: 'l3u1l6_busil-ninnu_slow',
        medium: 'l3u1l6_busil-ninnu_medium',
        normal: 'l3u1l6_busil-ninnu_normal',
      },
      acceptedInputs: ['busil ninnu', 'busil ninn'],
      notes: ['English words take the whole pair: busil ninnu, down from the bus.'],
      tags: [],
    },
    {
      id: 'classil-ninnu',
      manglish: 'classil ninnu',
      script: 'ക്ലാസ്സിൽ നിന്ന്',
      meaning: 'from class',
      kind: 'word',
      audio: {
        slow: 'l3u1l6_classil-ninnu_slow',
        medium: 'l3u1l6_classil-ninnu_medium',
        normal: 'l3u1l6_classil-ninnu_normal',
      },
      acceptedInputs: ['classil ninnu', 'classil ninn'],
      notes: ['Class takes the same pair, straight on the English word.'],
      tags: [],
    },
    {
      id: 'njan-officil-ninn-irangi',
      manglish: 'njan officil ninn irangi',
      script: 'ഞാൻ ഓഫീസിൽ നിന്ന് ഇറങ്ങി',
      meaning: 'I just left the office',
      kind: 'sentence',
      audio: {
        slow: 'l3u1l6_njan-officil-ninn-irangi_slow',
        medium: 'l3u1l6_njan-officil-ninn-irangi_medium',
        normal: 'l3u1l6_njan-officil-ninn-irangi_normal',
      },
      sentence: {
        bank: ['njan', 'officil', 'ninn', 'irangi', 'pokuva'],
        orders: ['njan officil ninn irangi'],
        parts: [
          { word: 'njan', meaning: 'I' },
          { word: 'officil', meaning: 'at the office' },
          { word: 'ninn', meaning: 'from' },
          { word: 'irangi', meaning: 'left; set off' },
        ],
      },
      notes: ['The from-frame you met at home, now at the office.'],
      tags: [],
    },
    {
      id: 'avan-busil-ninn-irangi',
      manglish: 'avan busil ninn irangi',
      script: 'അവൻ ബസ്സിൽ നിന്ന് ഇറങ്ങി',
      meaning: 'he got off the bus',
      kind: 'sentence',
      audio: {
        slow: 'l3u1l6_avan-busil-ninn-irangi_slow',
        medium: 'l3u1l6_avan-busil-ninn-irangi_medium',
        normal: 'l3u1l6_avan-busil-ninn-irangi_normal',
      },
      sentence: {
        bank: ['avan', 'busil', 'ninn', 'irangi', 'njan'],
        orders: ['avan busil ninn irangi'],
        parts: [
          { word: 'avan', meaning: 'he' },
          { word: 'busil', meaning: 'on the bus' },
          { word: 'ninn', meaning: 'from' },
          { word: 'irangi', meaning: 'left; set off' },
        ],
      },
      notes: ['Getting down is irangi too: off the bus, on the way.'],
      tags: [],
    },
    {
      id: 'njan-veettil-ninn-varunnund',
      manglish: 'njan veettil ninn varunnund',
      script: 'ഞാൻ വീട്ടിൽ നിന്ന് വരുന്നുണ്ട്',
      meaning: 'I am coming from home',
      kind: 'sentence',
      audio: {
        slow: 'l3u1l6_njan-veettil-ninn-varunnund_slow',
        medium: 'l3u1l6_njan-veettil-ninn-varunnund_medium',
        normal: 'l3u1l6_njan-veettil-ninn-varunnund_normal',
      },
      sentence: {
        bank: ['njan', 'veettil', 'ninn', 'varunnund', 'pokuva'],
        orders: ['njan veettil ninn varunnund'],
        parts: [
          { word: 'njan', meaning: 'I' },
          { word: 'veettil', meaning: 'home' },
          { word: 'ninn', meaning: 'from' },
          { word: 'varunnund', meaning: 'is coming' },
        ],
      },
      notes: ['Coming from: varunnund carries the am-coming.'],
      tags: [],
    },
    {
      id: 'avan-officil-ninn-varunnund',
      manglish: 'avan officil ninn varunnund',
      script: 'അവൻ ഓഫീസിൽ നിന്ന് വരുന്നുണ്ട്',
      meaning: 'he is coming from the office',
      kind: 'sentence',
      audio: {
        slow: 'l3u1l6_avan-officil-ninn-varunnund_slow',
        medium: 'l3u1l6_avan-officil-ninn-varunnund_medium',
        normal: 'l3u1l6_avan-officil-ninn-varunnund_normal',
      },
      sentence: {
        bank: ['avan', 'officil', 'ninn', 'varunnund', 'irangi'],
        orders: ['avan officil ninn varunnund'],
        parts: [
          { word: 'avan', meaning: 'he' },
          { word: 'officil', meaning: 'at the office' },
          { word: 'ninn', meaning: 'from' },
          { word: 'varunnund', meaning: 'is coming' },
        ],
      },
      notes: ['Same frame, different verb: coming, not leaving.'],
      tags: [],
    },
  ],
  minimalPairs: [],
  drills: [
    { kind: 'multipleChoice', itemId: 'aayi', distractors: ['it is ready', 'from the office', 'from home'] },
    { kind: 'multipleChoice', itemId: 'ready-aayi', distractors: ['became; done', 'from the bus', 'from class'] },
    { kind: 'multipleChoice', itemId: 'officil-ninnu', distractors: ['from home', 'from the bus', 'it is ready'] },
    { kind: 'multipleChoice', itemId: 'veettil-ninnu', distractors: ['from the office', 'from class', 'became; done'] },
    { kind: 'multipleChoice', itemId: 'busil-ninnu', distractors: ['from class', 'from the office', 'it is ready'] },
    { kind: 'multipleChoice', itemId: 'classil-ninnu', distractors: ['from the bus', 'from home', 'became; done'] },
    { kind: 'sentenceBuilder', itemId: 'chaaya-ready-aayi', mode: 'bank' },
    { kind: 'sentenceBuilder', itemId: 'avan-teacher-aayi', mode: 'bank' },
    { kind: 'sentenceBuilder', itemId: 'njan-ready-aayi', mode: 'bank' },
    { kind: 'sentenceBuilder', itemId: 'njan-officil-ninn-irangi', mode: 'bank' },
    { kind: 'sentenceBuilder', itemId: 'avan-busil-ninn-irangi', mode: 'bank' },
    { kind: 'sentenceBuilder', itemId: 'njan-veettil-ninn-varunnund', mode: 'bank' },
    { kind: 'sentenceBuilder', itemId: 'avan-officil-ninn-varunnund', mode: 'bank' },
  ],
  reviewSlots: 0,
  spriteId: 'l3u1l6',
};
