import type { Lesson } from '../types';

/**
 * Level 3 Unit 2 Lesson 1 — the ... aanu ...ath question (PLAN.md §5,
 * native-speaker ruling 2026-10-07). The question word sits right before
 * aanu and the verb waits at the end as -ath: nee eth schoolil aanu
 * padichath, chechi raavile enth aanu kazhichath, ee tv evide ninn aanu
 * medichath — plus the coming-from question avan evide ninn aanu
 * varunnath and its answer avan officil ninn aanu varunnath, taught as
 * a pair. The older bare forms (avan officil ninn varunnund) are retired.
 */
export const l3u2l1: Lesson = {
  id: 'l3u2l1',
  levelId: 'l3',
  unitId: 'l3u2',
  title: 'Which, what, where',
  comprehensionOnly: false,
  items: [
    {
      id: 'eth',
      manglish: 'eth',
      script: 'ഏത്',
      meaning: 'which',
      kind: 'word',
      audio: {
        slow: 'l3u2l1_eth_slow',
        medium: 'l3u2l1_eth_medium',
        normal: 'l3u2l1_eth_normal',
      },
      acceptedInputs: ['eth'],
      notes: ['eth leans on a noun: eth schoolil, which school. Alone it is etha, which one.'],
      tags: [],
    },
    {
      id: 'schoolil',
      manglish: 'schoolil',
      script: 'സ്കൂളിൽ',
      meaning: 'at school',
      kind: 'word',
      audio: {
        slow: 'l3u2l1_schoolil_slow',
        medium: 'l3u2l1_schoolil_medium',
        normal: 'l3u2l1_schoolil_normal',
      },
      acceptedInputs: ['schoolil'],
      notes: ['School takes the -il you know: schoolil, at school.'],
      tags: [],
    },
    {
      id: 'padichath',
      manglish: 'padichath',
      script: 'പഠിച്ചത്',
      meaning: 'studied',
      kind: 'word',
      audio: {
        slow: 'l3u2l1_padichath_slow',
        medium: 'l3u2l1_padichath_medium',
        normal: 'l3u2l1_padichath_normal',
      },
      acceptedInputs: ['padichath'],
      notes: ['The verb made into a thing: padichath, the studying that happened.'],
      tags: [],
    },
    {
      id: 'raavile',
      manglish: 'raavile',
      script: 'രാവിലെ',
      meaning: 'in the morning',
      kind: 'word',
      audio: {
        slow: 'l3u2l1_raavile_slow',
        medium: 'l3u2l1_raavile_medium',
        normal: 'l3u2l1_raavile_normal',
      },
      acceptedInputs: ['raavile'],
      notes: ['The morning slot: raavile, in the morning.'],
      tags: [],
    },
    {
      id: 'kazhichath',
      manglish: 'kazhichath',
      script: 'കഴിച്ചത്',
      meaning: 'ate',
      kind: 'word',
      audio: {
        slow: 'l3u2l1_kazhichath_slow',
        medium: 'l3u2l1_kazhichath_medium',
        normal: 'l3u2l1_kazhichath_normal',
      },
      acceptedInputs: ['kazhichath'],
      notes: ['The same -ath move as padichath: kazhichath, the eating.'],
      tags: [],
    },
    {
      id: 'medichath',
      manglish: 'medichath',
      script: 'മേടിച്ചത്',
      meaning: 'bought',
      kind: 'word',
      audio: {
        slow: 'l3u2l1_medichath_slow',
        medium: 'l3u2l1_medichath_medium',
        normal: 'l3u2l1_medichath_normal',
      },
      acceptedInputs: ['medichath'],
      notes: ['The same -ath move: medichath, the buying.'],
      tags: [],
    },
    {
      id: 'varunnath',
      manglish: 'varunnath',
      script: 'വരുന്നത്',
      meaning: 'coming',
      kind: 'word',
      audio: {
        slow: 'l3u2l1_varunnath_slow',
        medium: 'l3u2l1_varunnath_medium',
        normal: 'l3u2l1_varunnath_normal',
      },
      acceptedInputs: ['varunnath'],
      notes: ['The -ath form of varunnund: varunnath, the coming.'],
      tags: [],
    },
    {
      id: 'nee-eth-schoolil-aanu-padichath',
      manglish: 'nee eth schoolil aanu padichath',
      script: 'നീ ഏത് സ്കൂളിൽ ആണ് പഠിച്ചത്',
      meaning: 'which school did you go to?',
      kind: 'sentence',
      audio: {
        slow: 'l3u2l1_nee-eth-schoolil-aanu-padichath_slow',
        medium: 'l3u2l1_nee-eth-schoolil-aanu-padichath_medium',
        normal: 'l3u2l1_nee-eth-schoolil-aanu-padichath_normal',
      },
      sentence: {
        bank: ['nee', 'eth', 'schoolil', 'aanu', 'padichath', 'varunnath'],
        orders: ['nee eth schoolil aanu padichath'],
        parts: [
          { word: 'nee', meaning: 'you' },
          { word: 'eth', meaning: 'which' },
          { word: 'schoolil', meaning: 'at school' },
          { word: 'aanu', meaning: 'is' },
          { word: 'padichath', meaning: 'studied' },
        ],
      },
      notes: ['The shape of the question: eth schoolil sits right before aanu, and the verb waits at the end.'],
      tags: [],
    },
    {
      id: 'chechi-raavile-enth-aanu-kazhichath',
      manglish: 'chechi raavile enth aanu kazhichath',
      script: 'ചേച്ചി രാവിലെ എന്ത് ആണ് കഴിച്ചത്',
      meaning: 'what did you eat in the morning, chechi?',
      kind: 'sentence',
      audio: {
        slow: 'l3u2l1_chechi-raavile-enth-aanu-kazhichath_slow',
        medium: 'l3u2l1_chechi-raavile-enth-aanu-kazhichath_medium',
        normal: 'l3u2l1_chechi-raavile-enth-aanu-kazhichath_normal',
      },
      sentence: {
        bank: ['chechi', 'raavile', 'enth', 'aanu', 'kazhichath', 'padichath'],
        orders: ['chechi raavile enth aanu kazhichath'],
        parts: [
          { word: 'chechi', meaning: 'chechi (older sister — the everyday address for women)' },
          { word: 'raavile', meaning: 'in the morning' },
          { word: 'enth', meaning: 'what' },
          { word: 'aanu', meaning: 'is' },
          { word: 'kazhichath', meaning: 'ate' },
        ],
      },
      notes: [
        'enth is the entha you know, standing right before aanu.',
        'Addressed to chechi: the name opens the question.',
      ],
      tags: [],
    },
    {
      id: 'ee-tv-evide-ninn-aanu-medichath',
      manglish: 'ee tv evide ninn aanu medichath',
      script: 'ഈ ടീവി എവിടെ നിന്ന് ആണ് മേടിച്ചത്',
      meaning: 'where did you buy this TV from?',
      kind: 'sentence',
      audio: {
        slow: 'l3u2l1_ee-tv-evide-ninn-aanu-medichath_slow',
        medium: 'l3u2l1_ee-tv-evide-ninn-aanu-medichath_medium',
        normal: 'l3u2l1_ee-tv-evide-ninn-aanu-medichath_normal',
      },
      sentence: {
        bank: ['ee', 'tv', 'evide', 'ninn', 'aanu', 'medichath', 'kazhichath'],
        orders: ['ee tv evide ninn aanu medichath'],
        parts: [
          { word: 'ee', meaning: 'this' },
          { word: 'tv', meaning: 'TV' },
          { word: 'evide', meaning: 'where' },
          { word: 'ninn', meaning: 'from' },
          { word: 'aanu', meaning: 'is' },
          { word: 'medichath', meaning: 'bought' },
        ],
      },
      notes: ['evide ninn, where from, rides before aanu; medichath closes the question.'],
      tags: [],
    },
    {
      id: 'avan-evide-ninn-aanu-varunnath',
      manglish: 'avan evide ninn aanu varunnath',
      script: 'അവൻ എവിടെ നിന്ന് ആണ് വരുന്നത്',
      meaning: 'where is he coming from?',
      kind: 'sentence',
      audio: {
        slow: 'l3u2l1_avan-evide-ninn-aanu-varunnath_slow',
        medium: 'l3u2l1_avan-evide-ninn-aanu-varunnath_medium',
        normal: 'l3u2l1_avan-evide-ninn-aanu-varunnath_normal',
      },
      sentence: {
        bank: ['avan', 'evide', 'ninn', 'aanu', 'varunnath', 'medichath'],
        orders: ['avan evide ninn aanu varunnath'],
        parts: [
          { word: 'avan', meaning: 'he' },
          { word: 'evide', meaning: 'where' },
          { word: 'ninn', meaning: 'from' },
          { word: 'aanu', meaning: 'is' },
          { word: 'varunnath', meaning: 'coming' },
        ],
      },
      notes: ['The question half of the pair: where is he coming from.'],
      tags: [],
    },
    {
      id: 'avan-officil-ninn-aanu-varunnath',
      manglish: 'avan officil ninn aanu varunnath',
      script: 'അവൻ ഓഫീസിൽ നിന്ന് ആണ് വരുന്നത്',
      meaning: 'he is coming from the office',
      kind: 'sentence',
      audio: {
        slow: 'l3u2l1_avan-officil-ninn-aanu-varunnath_slow',
        medium: 'l3u2l1_avan-officil-ninn-aanu-varunnath_medium',
        normal: 'l3u2l1_avan-officil-ninn-aanu-varunnath_normal',
      },
      sentence: {
        bank: ['avan', 'officil', 'ninn', 'aanu', 'varunnath', 'evide'],
        orders: ['avan officil ninn aanu varunnath'],
        parts: [
          { word: 'avan', meaning: 'he' },
          { word: 'officil', meaning: 'at the office' },
          { word: 'ninn', meaning: 'from' },
          { word: 'aanu', meaning: 'is' },
          { word: 'varunnath', meaning: 'coming' },
        ],
      },
      notes: ['The answer half: the emphasis lands on officil — the office is where he is coming from.'],
      tags: [],
    },
  ],
  minimalPairs: [],
  drills: [
    { kind: 'multipleChoice', itemId: 'eth', distractors: ['at school', 'in the morning', 'bought'] },
    { kind: 'multipleChoice', itemId: 'schoolil', distractors: ['which', 'in the morning', 'studied'] },
    { kind: 'multipleChoice', itemId: 'padichath', distractors: ['which', 'ate', 'at school'] },
    { kind: 'multipleChoice', itemId: 'raavile', distractors: ['bought', 'which', 'coming'] },
    { kind: 'multipleChoice', itemId: 'kazhichath', distractors: ['studied', 'bought', 'which'] },
    { kind: 'multipleChoice', itemId: 'medichath', distractors: ['ate', 'coming', 'studied'] },
    { kind: 'multipleChoice', itemId: 'varunnath', distractors: ['which', 'bought', 'in the morning'] },
    { kind: 'sentenceBuilder', itemId: 'nee-eth-schoolil-aanu-padichath', mode: 'bank' },
    { kind: 'sentenceBuilder', itemId: 'chechi-raavile-enth-aanu-kazhichath', mode: 'bank' },
    { kind: 'sentenceBuilder', itemId: 'ee-tv-evide-ninn-aanu-medichath', mode: 'bank' },
    { kind: 'sentenceBuilder', itemId: 'avan-evide-ninn-aanu-varunnath', mode: 'bank' },
    { kind: 'sentenceBuilder', itemId: 'avan-officil-ninn-aanu-varunnath', mode: 'bank' },
  ],
  reviewSlots: 0,
  spriteId: 'l3u2l1',
};
