/**
 * Level 2 Unit 7 — Title substitution (PLAN.md §5): addressing people
 * by title the way Kerala does. The vocative drops the final -n
 * (chettan becomes chetta!) and always takes a comma; titles are
 * never the subject of a sentence.
 */

import type { Lesson } from '../../types'

export const lesson6Titles: Lesson = {
  id: 'l2u1l6',
  levelId: 'level2',
  unitId: 'unit7',
  title: 'Chettan and chechi',
  reviewSlots: 2,
  sprite: { file: 'audio/l2u1l6.mp3' },
  items: [
    {
      id: 'chettan',
      manglish: 'chettan',
      script: 'ചേട്ടൻ',
      meaning: 'older brother; a man older than you',
      kind: 'word',
      pos: 'noun',
      notes: [
        'To call him, the final -n drops: chettan becomes chetta!',
        'The vocative chetta always takes a comma in a sentence.',
      ],
      audio: { slow: 'chettan.slow', medium: 'chettan.medium', normal: 'chettan.normal' },
      tags: ['level:2'],
    },
    {
      id: 'chechi',
      manglish: 'chechi',
      script: 'ചേച്ചി',
      meaning: 'older sister; a woman older than you',
      kind: 'word',
      pos: 'noun',
      notes: [
        'It is the everyday title for a woman a little older than you.',
        'The vocative keeps its form: chechi! And it takes a comma in a sentence.',
      ],
      audio: { slow: 'chechi.slow', medium: 'chechi.medium', normal: 'chechi.normal' },
      tags: ['level:2'],
    },
    {
      id: 'chetta-ith-kando',
      manglish: 'chetta, ith kando',
      meaning: 'chetta, did you see this?',
      kind: 'sentence',
      notes: ['The vocative takes a comma: chetta is addressed, never the subject.'],
      segments: [
        { token: 'chetta,', gloss: 'chetta (addressing him)' },
        { token: 'ith', gloss: 'this' },
        { token: 'kando', gloss: 'did you see?' },
      ],
      audio: { slow: 'chetta-ith-kando.slow', medium: 'chetta-ith-kando.medium', normal: 'chetta-ith-kando.normal' },
      tags: ['level:2'],
    },
    {
      id: 'chechi-engane-und',
      manglish: 'chechi, engane und',
      script: 'ചേച്ചി, എങ്ങനെ ഉണ്ട്',
      meaning: 'chechi, how are you?',
      kind: 'sentence',
      segments: [
        { token: 'chechi,', gloss: 'chechi (addressing her)' },
        { token: 'engane und', gloss: 'how are you?' },
      ],
      audio: { slow: 'chechi-engane-und.slow', medium: 'chechi-engane-und.medium', normal: 'chechi-engane-und.normal' },
      tags: ['level:2'],
    },
    {
      id: 'chetta-varunnundo',
      manglish: 'chetta, varunnundo',
      meaning: 'chetta, are you coming?',
      kind: 'sentence',
      segments: [
        { token: 'chetta,', gloss: 'chetta (addressing him)' },
        { token: 'varunnundo', gloss: 'are you coming?' },
      ],
      audio: { slow: 'chetta-varunnundo.slow', medium: 'chetta-varunnundo.medium', normal: 'chetta-varunnundo.normal' },
      tags: ['level:2'],
    },
    {
      id: 'chechi-ith-kando',
      manglish: 'chechi, ith kando',
      script: 'ചേച്ചി, ഇത് കണ്ടോ',
      meaning: 'chechi, did you see this?',
      kind: 'sentence',
      segments: [
        { token: 'chechi,', gloss: 'chechi (addressing her)' },
        { token: 'ith', gloss: 'this' },
        { token: 'kando', gloss: 'did you see?' },
      ],
      audio: { slow: 'chechi-ith-kando.slow', medium: 'chechi-ith-kando.medium', normal: 'chechi-ith-kando.normal' },
      tags: ['level:2'],
    },
    {
      id: 'chetta-sheri-alle',
      manglish: 'chetta, sheri alle',
      meaning: 'chetta, right?',
      kind: 'sentence',
      segments: [
        { token: 'chetta,', gloss: 'chetta (addressing him)' },
        { token: 'sheri', gloss: 'right' },
        { token: 'alle', gloss: 'right? (tag)' },
      ],
      audio: { slow: 'chetta-sheri-alle.slow', medium: 'chetta-sheri-alle.medium', normal: 'chetta-sheri-alle.normal' },
      tags: ['level:2'],
    },
    {
      id: 'chechi-sheri-alle',
      manglish: 'chechi, sheri alle',
      script: 'ചേച്ചി, ശെരി അല്ലേ',
      meaning: 'chechi, right?',
      kind: 'sentence',
      segments: [
        { token: 'chechi,', gloss: 'chechi (addressing her)' },
        { token: 'sheri', gloss: 'right' },
        { token: 'alle', gloss: 'right? (tag)' },
      ],
      audio: { slow: 'chechi-sheri-alle.slow', medium: 'chechi-sheri-alle.medium', normal: 'chechi-sheri-alle.normal' },
      tags: ['level:2'],
    },
    {
      id: 'chechi-pokunnundo',
      manglish: 'chechi, pokunnundo',
      script: 'ചേച്ചി, പോകുന്നുണ്ടോ',
      meaning: 'chechi, are you going?',
      kind: 'sentence',
      segments: [
        { token: 'chechi,', gloss: 'chechi (addressing her)' },
        { token: 'pokunnundo', gloss: 'are you going?' },
      ],
      audio: { slow: 'chechi-pokunnundo.slow', medium: 'chechi-pokunnundo.medium', normal: 'chechi-pokunnundo.normal' },
      tags: ['level:2'],
    },
    {
      id: 'chechi-chaaya-veno',
      manglish: 'chechi, chaaya veno',
      script: 'ചേച്ചി, ചായ വേണോ',
      meaning: 'chechi, do you want tea?',
      kind: 'sentence',
      segments: [
        { token: 'chechi,', gloss: 'chechi (addressing her)' },
        { token: 'chaaya', gloss: 'tea' },
        { token: 'veno', gloss: 'do you want?' },
      ],
      audio: { slow: 'chechi-chaaya-veno.slow', medium: 'chechi-chaaya-veno.medium', normal: 'chechi-chaaya-veno.normal' },
      tags: ['level:2'],
    },
    {
      id: 'chetta-chaaya-veno',
      manglish: 'chetta, chaaya veno',
      meaning: 'chetta, do you want tea?',
      kind: 'sentence',
      segments: [
        { token: 'chetta,', gloss: 'chetta (addressing him)' },
        { token: 'chaaya', gloss: 'tea' },
        { token: 'veno', gloss: 'do you want?' },
      ],
      audio: { slow: 'chetta-chaaya-veno.slow', medium: 'chetta-chaaya-veno.medium', normal: 'chetta-chaaya-veno.normal' },
      tags: ['level:2'],
    },
  ],
  pairs: [],
  drills: [
    { kind: 'multipleChoice', itemId: 'chettan', distractors: ['chechi', 'chetta-ith-kando', 'chechi-engane-und'] },
    { kind: 'multipleChoice', itemId: 'chechi', distractors: ['chettan', 'chetta-varunnundo', 'chechi-pokunnundo'] },
    { kind: 'multipleChoice', itemId: 'chetta-ith-kando', distractors: ['chechi-ith-kando', 'chechi-engane-und', 'chetta-varunnundo'] },
    { kind: 'multipleChoice', itemId: 'chechi-chaaya-veno', distractors: ['chetta-chaaya-veno', 'chechi-sheri-alle', 'chetta-sheri-alle'] },
    {
      kind: 'sentenceBuilder',
      sentenceId: 'chetta-ith-kando',
      bank: ['chetta,', 'ith', 'kando'],
      acceptedInputs: ['chetta ith kando'],
    },
    {
      kind: 'sentenceBuilder',
      sentenceId: 'chechi-engane-und',
      bank: ['chechi,', 'engane', 'und'],
      acceptedInputs: ['chechi engane und'],
    },
    {
      kind: 'sentenceBuilder',
      sentenceId: 'chetta-varunnundo',
      bank: ['chetta,', 'varunnundo'],
      acceptedInputs: ['chetta varunundo'],
    },
    {
      kind: 'sentenceBuilder',
      sentenceId: 'chechi-chaaya-veno',
      bank: ['chechi,', 'chaaya', 'veno'],
      acceptedInputs: ['chechi chaaya veno'],
    },
    { kind: 'typing', itemId: 'chettan', acceptedInputs: ['chettan'] },
    { kind: 'typing', itemId: 'chechi', acceptedInputs: ['chechi'] },
  ],
}
