/**
 * Level 3 Unit 1 Lesson 6 — From and as (PLAN.md §5): -il ninn for
 * where something comes from, and -aayi for something that just
 * happened. The where-from question is taught with its answer in the
 * aanu ... ath shape the question-word lesson takes further. The short
 * colloquial ninn is the one already heard in njan veettil ninn irangi.
 */

import type { Lesson } from '../../types'

export const lesson6CasesFrom: Lesson = {
  id: 'l3u1l6',
  levelId: 'level3',
  unitId: 'unit6',
  title: 'From and as: ninn, -aayi',
  reviewSlots: 2,
  sprite: { file: 'audio/l3u1l6.mp3' },
  items: [
    {
      id: 'ninn',
      manglish: 'ninn',
      script: 'നിന്ന്',
      meaning: 'from',
      kind: 'word',
      pos: 'particle',
      acceptedInputs: ['ninnu'],
      notes: [
        'ninn is the everyday "from". It comes after the -il form of the place: veettil ninn, from home.',
        'You already heard it in njan veettil ninn irangi (I just left home).',
      ],
      audio: { slow: 'ninn.slow', medium: 'ninn.medium', normal: 'ninn.normal' },
      tags: ['level:3'],
    },
    {
      id: 'veettil-ninn',
      manglish: 'veettil ninn',
      script: 'വീട്ടിൽ നിന്ന്',
      meaning: 'from home (veettil + ninn)',
      acceptedInputs: ['veettil ninnu'],
      kind: 'word',
      pos: 'noun',
      notes: ['The frame is [place with -il] + ninn: veettil (at home) + ninn = from home.'],
      audio: { slow: 'veettil-ninn.slow', medium: 'veettil-ninn.medium', normal: 'veettil-ninn.normal' },
      tags: ['level:3'],
    },
    {
      id: 'officil-ninn',
      manglish: 'officil ninn',
      meaning: 'from the office (officil + ninn)',
      acceptedInputs: ['officil ninnu'],
      kind: 'word',
      pos: 'noun',
      notes: [
        'English words take the pair just as they take -il: officil ninn, from the office.',
        'No script here: the English word has no settled Malayalam spelling.',
      ],
      audio: { slow: 'officil-ninn.slow', medium: 'officil-ninn.medium', normal: 'officil-ninn.normal' },
      tags: ['level:3'],
    },
    {
      id: 'busil-ninn',
      manglish: 'busil ninn',
      meaning: 'from the bus (busil + ninn)',
      acceptedInputs: ['busil ninnu'],
      kind: 'word',
      pos: 'noun',
      notes: ['No script here: the English word has no settled Malayalam spelling.'],
      audio: { slow: 'busil-ninn.slow', medium: 'busil-ninn.medium', normal: 'busil-ninn.normal' },
      tags: ['level:3'],
    },
    {
      id: 'kadayil-ninn',
      manglish: 'kadayil ninn',
      script: 'കടയിൽ നിന്ന്',
      meaning: 'from the shop (kadayil + ninn)',
      acceptedInputs: ['kadayil ninnu'],
      kind: 'word',
      pos: 'noun',
      notes: ['kadayil (at the shop) + ninn = from the shop.'],
      audio: { slow: 'kadayil-ninn.slow', medium: 'kadayil-ninn.medium', normal: 'kadayil-ninn.normal' },
      tags: ['level:3'],
    },
    {
      id: 'ninte-veettil-ninn-aarokke-varunnund',
      manglish: 'ninte veettil ninn aarokke varunnund',
      script: 'നിന്റെ വീട്ടിൽ നിന്ന് ആരൊക്കെ വരുന്നുണ്ട്',
      meaning: 'who all are coming from your house?',
      kind: 'sentence',
      notes: [
        'aarokke is who all: aar (who) + okke (all together).',
        'The frame is the same one: [place with -il] + ninn + [verb]. Only the question word changes.',
      ],
      segments: [
        { token: 'ninte', gloss: 'your (casual)' },
        { token: 'veettil', gloss: 'at home' },
        { token: 'ninn', gloss: 'from' },
        { token: 'aarokke', gloss: 'who all' },
        { token: 'varunnund', gloss: 'are coming' },
      ],
      audio: { slow: 'ninte-veettil-ninn-aarokke-varunnund.slow', medium: 'ninte-veettil-ninn-aarokke-varunnund.medium', normal: 'ninte-veettil-ninn-aarokke-varunnund.normal' },
      tags: ['level:3'],
    },
    {
      id: 'avan-kadayil-ninn-varunnund',
      manglish: 'avan kadayil ninn varunnund',
      script: 'അവൻ കടയിൽ നിന്ന് വരുന്നുണ്ട്',
      meaning: 'he is coming from the shop.',
      kind: 'sentence',
      segments: [
        { token: 'avan', gloss: 'he' },
        { token: 'kadayil', gloss: 'at the shop' },
        { token: 'ninn', gloss: 'from' },
        { token: 'varunnund', gloss: 'is coming' },
      ],
      audio: { slow: 'avan-kadayil-ninn-varunnund.slow', medium: 'avan-kadayil-ninn-varunnund.medium', normal: 'avan-kadayil-ninn-varunnund.normal' },
      tags: ['level:3'],
    },
    {
      id: 'nee-evide-ninn-aanu-varunnath',
      manglish: 'nee evide ninn aanu varunnath',
      script: 'നീ എവിടെ നിന്ന് ആണ് വരുന്നത്',
      meaning: 'where are you coming from?',
      kind: 'sentence',
      notes: ['The question and its answer are a pair: nee evide ninn aanu varunnath? — njan officil ninn aanu varunnath.'],
      segments: [
        { token: 'nee', gloss: 'you (casual)' },
        { token: 'evide', gloss: 'where?' },
        { token: 'ninn', gloss: 'from' },
        { token: 'aanu', gloss: 'is (the emphasis word)' },
        { token: 'varunnath', gloss: 'coming (the coming)' },
      ],
      audio: { slow: 'nee-evide-ninn-aanu-varunnath.slow', medium: 'nee-evide-ninn-aanu-varunnath.medium', normal: 'nee-evide-ninn-aanu-varunnath.normal' },
      tags: ['level:3'],
    },
    {
      id: 'njan-officil-ninn-aanu-varunnath',
      manglish: 'njan officil ninn aanu varunnath',
      meaning: 'I am coming from the office.',
      kind: 'sentence',
      notes: [
        'The answer repeats the question and fills in the place: the emphasis lands on the office.',
        'No script here: the English word has no settled Malayalam spelling.',
      ],
      segments: [
        { token: 'njan', gloss: 'I' },
        { token: 'officil', gloss: 'at the office' },
        { token: 'ninn', gloss: 'from' },
        { token: 'aanu', gloss: 'is (the emphasis word)' },
        { token: 'varunnath', gloss: 'coming (the coming)' },
      ],
      audio: { slow: 'njan-officil-ninn-aanu-varunnath.slow', medium: 'njan-officil-ninn-aanu-varunnath.medium', normal: 'njan-officil-ninn-aanu-varunnath.normal' },
      tags: ['level:3'],
    },
    {
      id: 'avan-busil-ninn-irangi',
      manglish: 'avan busil ninn irangi',
      meaning: 'he got off the bus.',
      kind: 'sentence',
      notes: [
        'irangi is the past of iranguva (to get down): busil ninn irangi, got down from the bus.',
        'No script here: the English word has no settled Malayalam spelling.',
      ],
      segments: [
        { token: 'avan', gloss: 'he' },
        { token: 'busil', gloss: 'on the bus' },
        { token: 'ninn', gloss: 'from' },
        { token: 'irangi', gloss: 'got down' },
      ],
      audio: { slow: 'avan-busil-ninn-irangi.slow', medium: 'avan-busil-ninn-irangi.medium', normal: 'avan-busil-ninn-irangi.normal' },
      tags: ['level:3'],
    },
    {
      id: 'avan-evide-ninn-aanu-varunnath',
      manglish: 'avan evide ninn aanu varunnath',
      script: 'അവൻ എവിടെ നിന്ന് ആണ് വരുന്നത്',
      meaning: 'where is he coming from?',
      kind: 'sentence',
      notes: [
        'The question puts aanu before the verb and closes with -ath: evide ninn aanu varunnath, where is it that he is coming from?',
        'The answer comes back in the same shape with the place filled in: avan officil ninn aanu varunnath.',
      ],
      segments: [
        { token: 'avan', gloss: 'he' },
        { token: 'evide', gloss: 'where?' },
        { token: 'ninn', gloss: 'from' },
        { token: 'aanu', gloss: 'is (the emphasis word)' },
        { token: 'varunnath', gloss: 'coming (the coming)' },
      ],
      audio: { slow: 'avan-evide-ninn-aanu-varunnath.slow', medium: 'avan-evide-ninn-aanu-varunnath.medium', normal: 'avan-evide-ninn-aanu-varunnath.normal' },
      tags: ['level:3'],
    },
    {
      id: 'avan-officil-ninn-aanu-varunnath',
      manglish: 'avan officil ninn aanu varunnath',
      meaning: 'he is coming from the office.',
      kind: 'sentence',
      notes: ['The answer to avan evide ninn aanu varunnath? — the emphasis lands on the office.', 'No script here: the English word has no settled Malayalam spelling.'],
      segments: [
        { token: 'avan', gloss: 'he' },
        { token: 'officil', gloss: 'at the office' },
        { token: 'ninn', gloss: 'from' },
        { token: 'aanu', gloss: 'is (the emphasis word)' },
        { token: 'varunnath', gloss: 'coming (the coming)' },
      ],
      audio: { slow: 'avan-officil-ninn-aanu-varunnath.slow', medium: 'avan-officil-ninn-aanu-varunnath.medium', normal: 'avan-officil-ninn-aanu-varunnath.normal' },
      tags: ['level:3'],
    },
    {
      id: 'njan-veettil-ninn-iranguva',
      manglish: 'njan veettil ninn iranguva',
      script: 'ഞാൻ വീട്ടിൽ നിന്ന് ഇറങ്ങുവാ',
      meaning: 'I am leaving home.',
      kind: 'sentence',
      notes: [
        'iranguva is the leaving word (setting off), and it already carries now — ippo is redundant beside it.',
        'The frame is [who] + [place with -il] + ninn + [verb].',
      ],
      segments: [
        { token: 'njan', gloss: 'I' },
        { token: 'veettil', gloss: 'at home' },
        { token: 'ninn', gloss: 'from' },
        { token: 'iranguva', gloss: 'setting off' },
      ],
      audio: { slow: 'njan-veettil-ninn-iranguva.slow', medium: 'njan-veettil-ninn-iranguva.medium', normal: 'njan-veettil-ninn-iranguva.normal' },
      tags: ['level:3'],
    },
    {
      id: 'sheri-aayi',
      manglish: 'sheri aayi',
      script: 'ശെരി ആയി',
      meaning: "it's fixed; it's okay now.",
      kind: 'phrase',
      notes: [
        '-aayi is for something that just happened: sheri (fine) + aayi = it has just become fine.',
        'So sheri aayi is "it is fixed now" or "it is okay now" — said the moment a problem clears.',
      ],
      audio: { slow: 'sheri-aayi.slow', medium: 'sheri-aayi.medium', normal: 'sheri-aayi.normal' },
      tags: ['level:3'],
    },
    {
      id: 'njan-ready-aayi',
      manglish: 'njan ready aayi',
      meaning: 'I have got ready.',
      kind: 'sentence',
      notes: [
        '-aayi attaches to English words: ready + aayi = became ready, got ready.',
        'No script here: the English word has no settled Malayalam spelling.',
      ],
      segments: [
        { token: 'njan', gloss: 'I' },
        { token: 'ready', gloss: 'ready' },
        { token: 'aayi', gloss: 'became' },
      ],
      audio: { slow: 'njan-ready-aayi.slow', medium: 'njan-ready-aayi.medium', normal: 'njan-ready-aayi.normal' },
      tags: ['level:3'],
    },
    {
      id: 'ee-bucket-full-aayi',
      manglish: 'ee bucket full aayi',
      meaning: 'this bucket has been filled.',
      kind: 'sentence',
      notes: [
        '-aayi is for something that just happened: the bucket was empty, and now it is full.',
        'It is not for slow changes: becoming a teacher takes years, so aayi would not fit there.',
        'No script here: the English words have no settled Malayalam spelling.',
      ],
      segments: [
        { token: 'ee', gloss: 'this' },
        { token: 'bucket', gloss: 'bucket' },
        { token: 'full', gloss: 'full' },
        { token: 'aayi', gloss: 'has become' },
      ],
      audio: { slow: 'ee-bucket-full-aayi.slow', medium: 'ee-bucket-full-aayi.medium', normal: 'ee-bucket-full-aayi.normal' },
      tags: ['level:3'],
    },
  ],
  pairs: [],
  drills: [
    { kind: 'multipleChoice', itemId: 'ninn', distractors: ['veettil-ninn', 'kadayil-ninn', 'officil-ninn'] },
    { kind: 'multipleChoice', itemId: 'veettil-ninn', distractors: ['kadayil-ninn', 'officil-ninn', 'busil-ninn'] },
    { kind: 'multipleChoice', itemId: 'officil-ninn', distractors: ['busil-ninn', 'veettil-ninn', 'kadayil-ninn'] },
    { kind: 'multipleChoice', itemId: 'sheri-aayi', distractors: ['njan-ready-aayi', 'ee-bucket-full-aayi', 'ninn'] },
    {
      kind: 'sentenceBuilder',
      sentenceId: 'ninte-veettil-ninn-aarokke-varunnund',
      bank: ['ninte', 'veettil', 'ninn', 'aarokke', 'varunnund'],
      acceptedInputs: ['ninte veettil ninn aarokke varunnund', 'ninte veettil ninn aarokke varunund', 'ninte veettil ninnu aarokke varunnund'],
    },
    {
      kind: 'sentenceBuilder',
      sentenceId: 'avan-kadayil-ninn-varunnund',
      bank: ['avan', 'kadayil', 'ninn', 'varunnund'],
      acceptedInputs: ['avan kadayil ninn varunnund', 'avan kadayil ninn varunund', 'avan kadayil ninnu varunnund'],
    },
    {
      kind: 'sentenceBuilder',
      sentenceId: 'nee-evide-ninn-aanu-varunnath',
      bank: ['nee', 'evide', 'ninn', 'aanu', 'varunnath'],
      acceptedInputs: ['nee evide ninn aanu varunnath', 'nee evide ninnu aanu varunnath', 'ni evide ninn aanu varunnath'],
    },
    {
      kind: 'multipleChoice',
      itemId: 'njan-officil-ninn-aanu-varunnath',
      distractors: ['avan-officil-ninn-aanu-varunnath', 'avan-kadayil-ninn-varunnund', 'ee-bucket-full-aayi'],
    },
    {
      kind: 'sentenceBuilder',
      sentenceId: 'avan-busil-ninn-irangi',
      bank: ['avan', 'busil', 'ninn', 'irangi'],
      acceptedInputs: ['avan busil ninn irangi', 'avan busil ninnu irangi'],
    },
    {
      kind: 'sentenceBuilder',
      sentenceId: 'avan-evide-ninn-aanu-varunnath',
      bank: ['avan', 'evide', 'ninn', 'aanu', 'varunnath'],
      acceptedInputs: ['avan evide ninn aanu varunnath', 'avan evide ninnu aanu varunnath'],
    },
    {
      kind: 'sentenceBuilder',
      sentenceId: 'avan-officil-ninn-aanu-varunnath',
      bank: ['avan', 'officil', 'ninn', 'aanu', 'varunnath'],
      acceptedInputs: ['avan officil ninn aanu varunnath', 'avan officil ninnu aanu varunnath'],
    },
    {
      kind: 'sentenceBuilder',
      sentenceId: 'njan-veettil-ninn-iranguva',
      bank: ['njan', 'veettil', 'ninn', 'iranguva'],
      acceptedInputs: ['njan veettil ninn iranguva', 'njan veettil ninnu iranguva'],
    },
    { kind: 'multipleChoice', itemId: 'njan-veettil-ninn-iranguva', distractors: ['njan-ready-aayi', 'sheri-aayi', 'njan-officil-ninn-aanu-varunnath'] },
    { kind: 'multipleChoice', itemId: 'njan-ready-aayi', distractors: ['ee-bucket-full-aayi', 'sheri-aayi', 'njan-veettil-ninn-iranguva'] },
    {
      kind: 'sentenceBuilder',
      sentenceId: 'ee-bucket-full-aayi',
      bank: ['ee', 'bucket', 'full', 'aayi'],
      acceptedInputs: ['ee bucket full aayi'],
    },
    { kind: 'typing', itemId: 'ninn', acceptedInputs: ['ninn', 'ninnu'] },
    { kind: 'typing', itemId: 'veettil-ninn', acceptedInputs: ['veettil ninn', 'veettil nin', 'veettil ninnu'] },
  ],
}
