/**
 * Level 3 Unit 1 Lesson 1 — The -il case (PLAN.md §5): where things
 * are and where you are going. The flagship pattern is suffix
 * assimilation onto English words, exactly how Kerala speaks.
 */

import type { Lesson } from '../../types'

export const lesson1CasesIl: Lesson = {
  id: 'l3u1l1',
  levelId: 'level3',
  unitId: 'unit1',
  title: 'Where: -il',
  reviewSlots: 2,
  sprite: { file: 'audio/l3u1l1.mp3' },
  items: [
    {
      id: 'veettil',
      manglish: 'veettil',
      script: 'വീട്ടിൽ',
      meaning: 'at home (veedu + il)',
      kind: 'word',
      pos: 'noun',
      notes: ['-il attaches to words: veedu (home) + il = veettil, with the d doubling.'],
      audio: { slow: 'veettil.slow', medium: 'veettil.medium', normal: 'veettil.normal' },
      tags: ['level:3'],
    },
    {
      id: 'officil',
      manglish: 'officil',
      meaning: 'at the office (office + il)',
      kind: 'word',
      pos: 'noun',
      notes: [
        '-il attaches to English words too: office + il = officil.',
        'No script here: the English word has no settled Malayalam spelling.',
      ],
      audio: { slow: 'officil.slow', medium: 'officil.medium', normal: 'officil.normal' },
      tags: ['level:3'],
    },
    {
      id: 'kada',
      manglish: 'kada',
      script: 'കട',
      meaning: 'shop',
      kind: 'word',
      pos: 'noun',
      notes: ['The everyday word for a small shop. With -il: kadayil.'],
      audio: { slow: 'kada.slow', medium: 'kada.medium', normal: 'kada.normal' },
      tags: ['level:3'],
    },
    {
      id: 'kadayil',
      manglish: 'kadayil',
      script: 'കടയിൽ',
      meaning: 'at the shop (kada + il)',
      kind: 'word',
      pos: 'noun',
      notes: ['-il attaches to kada: kada (shop) + il = kadayil.'],
      audio: { slow: 'kadayil.slow', medium: 'kadayil.medium', normal: 'kadayil.normal' },
      tags: ['level:3'],
    },
    {
      id: 'busil',
      manglish: 'busil',
      meaning: 'on the bus (bus + il)',
      kind: 'word',
      pos: 'noun',
      notes: ['No script here: the English word has no settled Malayalam spelling.'],
      audio: { slow: 'busil.slow', medium: 'busil.medium', normal: 'busil.normal' },
      tags: ['level:3'],
    },
    {
      id: 'njan-officil-pokuva',
      manglish: 'njan officil pokuva',
      meaning: 'I am going to the office.',
      kind: 'sentence',
      notes: ['-il covers "to" with going verbs: officil pokuva, going to the office.'],
      segments: [
        { token: 'njan', gloss: 'I' },
        { token: 'officil', gloss: 'to the office' },
        { token: 'pokuva', gloss: 'going' },
      ],
      audio: { slow: 'njan-officil-pokuva.slow', medium: 'njan-officil-pokuva.medium', normal: 'njan-officil-pokuva.normal' },
      tags: ['level:3'],
    },
    {
      id: 'njan-veettil-und',
      manglish: 'njan veettil und',
      script: 'ഞാൻ വീട്ടിൽ ഉണ്ട്',
      meaning: 'I am at home.',
      kind: 'sentence',
      segments: [
        { token: 'njan', gloss: 'I' },
        { token: 'veettil', gloss: 'at home' },
        { token: 'und', gloss: 'am (at a place)' },
      ],
      audio: { slow: 'njan-veettil-und.slow', medium: 'njan-veettil-und.medium', normal: 'njan-veettil-und.normal' },
      tags: ['level:3'],
    },
    {
      id: 'avan-kadayil-und',
      manglish: 'avan kadayil und',
      script: 'അവൻ കടയിൽ ഉണ്ട്',
      meaning: 'he is at the shop.',
      kind: 'sentence',
      segments: [
        { token: 'avan', gloss: 'he' },
        { token: 'kadayil', gloss: 'at the shop' },
        { token: 'und', gloss: 'is (at a place)' },
      ],
      audio: { slow: 'avan-kadayil-und.slow', medium: 'avan-kadayil-und.medium', normal: 'avan-kadayil-und.normal' },
      tags: ['level:3'],
    },
    {
      id: 'njan-busil-und',
      manglish: 'njan busil und',
      meaning: 'I am on the bus.',
      kind: 'sentence',
      notes: ['No script here: the English word has no settled Malayalam spelling.'],
      segments: [
        { token: 'njan', gloss: 'I' },
        { token: 'busil', gloss: 'on the bus' },
        { token: 'und', gloss: 'am (at a place)' },
      ],
      audio: { slow: 'njan-busil-und.slow', medium: 'njan-busil-und.medium', normal: 'njan-busil-und.normal' },
      tags: ['level:3'],
    },
    {
      id: 'njan-busil-keran-pokuva',
      manglish: 'njan busil keran pokuva',
      meaning: 'I am going to board the bus.',
      kind: 'sentence',
      notes: [
        'keran is the "to" form of keruka, to climb on.',
        'No script here: the English word has no settled Malayalam spelling.',
      ],
      segments: [
        { token: 'njan', gloss: 'I' },
        { token: 'busil', gloss: 'the bus (bus + il)' },
        { token: 'keran', gloss: 'to climb on' },
        { token: 'pokuva', gloss: 'going' },
      ],
      audio: { slow: 'njan-busil-keran-pokuva.slow', medium: 'njan-busil-keran-pokuva.medium', normal: 'njan-busil-keran-pokuva.normal' },
      tags: ['level:3'],
    },
    {
      id: 'chaaya-veettil-und',
      manglish: 'chaaya veettil und',
      script: 'ചായ വീട്ടിൽ ഉണ്ട്',
      meaning: 'there is tea at home.',
      kind: 'sentence',
      segments: [
        { token: 'chaaya', gloss: 'tea' },
        { token: 'veettil', gloss: 'at home' },
        { token: 'und', gloss: 'there is' },
      ],
      audio: { slow: 'chaaya-veettil-und.slow', medium: 'chaaya-veettil-und.medium', normal: 'chaaya-veettil-und.normal' },
      tags: ['level:3'],
    },
    {
      id: 'chechi-officil-und',
      manglish: 'chechi officil und',
      meaning: 'chechi is at the office.',
      kind: 'sentence',
      notes: ['No script here: the English words have no settled Malayalam spelling.'],
      segments: [
        { token: 'chechi', gloss: 'aunty' },
        { token: 'officil', gloss: 'at the office' },
        { token: 'und', gloss: 'is (at a place)' },
      ],
      audio: { slow: 'chechi-officil-und.slow', medium: 'chechi-officil-und.medium', normal: 'chechi-officil-und.normal' },
      tags: ['level:3'],
    },
  ],
  pairs: [],
  drills: [
    { kind: 'multipleChoice', itemId: 'veettil', distractors: ['officil', 'kadayil', 'busil'] },
    { kind: 'multipleChoice', itemId: 'officil', distractors: ['veettil', 'kadayil', 'busil'] },
    { kind: 'multipleChoice', itemId: 'kada', distractors: ['kadayil', 'veettil', 'officil'] },
    { kind: 'multipleChoice', itemId: 'kadayil', distractors: ['kada', 'veettil', 'officil'] },
    { kind: 'multipleChoice', itemId: 'busil', distractors: ['veettil', 'officil', 'kadayil'] },
    {
      kind: 'sentenceBuilder',
      sentenceId: 'njan-officil-pokuva',
      bank: ['njan', 'officil', 'pokuva'],
      acceptedInputs: ['njan officil pokuva'],
    },
    {
      kind: 'sentenceBuilder',
      sentenceId: 'njan-veettil-und',
      bank: ['njan', 'veettil', 'und'],
      acceptedInputs: ['njan veettil und'],
    },
    {
      kind: 'sentenceBuilder',
      sentenceId: 'chaaya-veettil-und',
      bank: ['chaaya', 'veettil', 'und'],
      acceptedInputs: ['chaaya veettil und'],
    },
    {
      kind: 'sentenceBuilder',
      sentenceId: 'njan-busil-und',
      bank: ['njan', 'busil', 'und'],
      acceptedInputs: ['njan busil und'],
    },
    { kind: 'multipleChoice', itemId: 'njan-busil-keran-pokuva', distractors: ['njan-busil-und', 'njan-officil-pokuva', 'njan-veettil-und'] },
    {
      kind: 'sentenceBuilder',
      sentenceId: 'njan-busil-keran-pokuva',
      bank: ['njan', 'busil', 'keran', 'pokuva'],
      acceptedInputs: ['njan busil keran pokuva'],
    },
    { kind: 'typing', itemId: 'officil', acceptedInputs: ['officil'] },
  ],
}
