/**
 * Level 3 Unit 1 Lesson 2 — The -ilekk case (PLAN.md §5): the pointed
 * "to", attached to English words the way Kerala speaks.
 */

import type { Lesson } from '../../types'

export const lesson2CasesIlekk: Lesson = {
  id: 'l3u1l2',
  levelId: 'level3',
  unitId: 'unit2',
  title: 'To: -ilekk',
  reviewSlots: 2,
  sprite: { file: 'audio/l3u1l2.mp3' },
  items: [
    {
      id: 'veettilekk',
      manglish: 'veettilekk',
      script: 'വീട്ടിലേക്ക്',
      meaning: 'to home (veedu + ilekk)',
      kind: 'word',
      pos: 'noun',
      notes: ['-ilekk is the pointed "to": veedu (home) + ilekk = veettilekk.'],
      audio: { slow: 'veettilekk.slow', medium: 'veettilekk.medium', normal: 'veettilekk.normal' },
      tags: ['level:3'],
    },
    {
      id: 'hotelilekk',
      manglish: 'hotelilekk',
      meaning: 'to the hotel (hotel + ilekk)',
      kind: 'word',
      pos: 'noun',
      notes: [
        'In Kerala, hotel colloquially means a restaurant or eatery, not a place to sleep.',
        'No script here: the English word has no settled Malayalam spelling.',
      ],
      audio: { slow: 'hotelilekk.slow', medium: 'hotelilekk.medium', normal: 'hotelilekk.normal' },
      tags: ['level:3'],
    },
    {
      id: 'officilekk',
      manglish: 'officilekk',
      meaning: 'to the office (office + ilekk)',
      kind: 'word',
      pos: 'noun',
      notes: ['No script here: the English word has no settled Malayalam spelling.'],
      audio: { slow: 'officilekk.slow', medium: 'officilekk.medium', normal: 'officilekk.normal' },
      tags: ['level:3'],
    },
    {
      id: 'kadayilekk',
      manglish: 'kadayilekk',
      script: 'കടയിലേക്ക്',
      meaning: 'to the shop (kada + ilekk)',
      kind: 'word',
      pos: 'noun',
      notes: ['-ilekk is the pointed "to": kada (shop) + ilekk = kadayilekk.'],
      audio: { slow: 'kadayilekk.slow', medium: 'kadayilekk.medium', normal: 'kadayilekk.normal' },
      tags: ['level:3'],
    },
    {
      id: 'njan-hotelilekk-pokuva',
      manglish: 'njan hotelilekk pokuva',
      meaning: 'I am going to the hotel.',
      kind: 'sentence',
      notes: [
        '-ilekk is the pointed "to": hotelilekk, to the hotel.',
        'No script here: the English word has no settled Malayalam spelling.',
      ],
      segments: [
        { token: 'njan', gloss: 'I' },
        { token: 'hotelilekk', gloss: 'to the hotel' },
        { token: 'pokuva', gloss: 'going' },
      ],
      audio: { slow: 'njan-hotelilekk-pokuva.slow', medium: 'njan-hotelilekk-pokuva.medium', normal: 'njan-hotelilekk-pokuva.normal' },
      tags: ['level:3'],
    },
    {
      id: 'njan-officilekk-pokuva',
      manglish: 'njan officilekk pokuva',
      meaning: 'I am going to the office.',
      kind: 'sentence',
      notes: ['No script here: the English word has no settled Malayalam spelling.'],
      segments: [
        { token: 'njan', gloss: 'I' },
        { token: 'officilekk', gloss: 'to the office' },
        { token: 'pokuva', gloss: 'going' },
      ],
      audio: { slow: 'njan-officilekk-pokuva.slow', medium: 'njan-officilekk-pokuva.medium', normal: 'njan-officilekk-pokuva.normal' },
      tags: ['level:3'],
    },
    {
      id: 'njan-veettilekk-pokuva',
      manglish: 'njan veettilekk pokuva',
      script: 'ഞാൻ വീട്ടിലേക്ക് പോകുവാ',
      meaning: 'I am going home (with -ilekk).',
      kind: 'sentence',
      segments: [
        { token: 'njan', gloss: 'I' },
        { token: 'veettilekk', gloss: 'to home' },
        { token: 'pokuva', gloss: 'going' },
      ],
      audio: { slow: 'njan-veettilekk-pokuva.slow', medium: 'njan-veettilekk-pokuva.medium', normal: 'njan-veettilekk-pokuva.normal' },
      tags: ['level:3'],
    },
    {
      id: 'avan-hotelilekk-varunnundo',
      manglish: 'avan hotelilekk varunnundo',
      meaning: 'is he coming to the hotel?',
      kind: 'sentence',
      notes: ['No script here: the English word has no settled Malayalam spelling.'],
      segments: [
        { token: 'avan', gloss: 'he' },
        { token: 'hotelilekk', gloss: 'to the hotel' },
        { token: 'varunnundo', gloss: 'is coming?' },
      ],
      audio: { slow: 'avan-hotelilekk-varunnundo.slow', medium: 'avan-hotelilekk-varunnundo.medium', normal: 'avan-hotelilekk-varunnundo.normal' },
      tags: ['level:3'],
    },
    {
      id: 'njan-kadayilekk-pokuva',
      manglish: 'njan kadayilekk pokuva',
      script: 'ഞാൻ കടയിലേക്ക് പോകുവാ',
      meaning: 'I am going to the shop.',
      kind: 'sentence',
      segments: [
        { token: 'njan', gloss: 'I' },
        { token: 'kadayilekk', gloss: 'to the shop' },
        { token: 'pokuva', gloss: 'going' },
      ],
      audio: { slow: 'njan-kadayilekk-pokuva.slow', medium: 'njan-kadayilekk-pokuva.medium', normal: 'njan-kadayilekk-pokuva.normal' },
      tags: ['level:3'],
    },
    {
      id: 'avan-hotelilekk-pokuva',
      manglish: 'avan hotelilekk pokuva',
      meaning: 'he is going to the hotel.',
      kind: 'sentence',
      notes: ['No script here: the English words have no settled Malayalam spelling.'],
      segments: [
        { token: 'avan', gloss: 'he' },
        { token: 'hotelilekk', gloss: 'to the hotel' },
        { token: 'pokuva', gloss: 'going' },
      ],
      audio: { slow: 'avan-hotelilekk-pokuva.slow', medium: 'avan-hotelilekk-pokuva.medium', normal: 'avan-hotelilekk-pokuva.normal' },
      tags: ['level:3'],
    },
    {
      id: 'chetta-hotelilekk-pokunnundo',
      manglish: 'chetta, hotelilekk pokunnundo',
      meaning: 'chetta, are you going to the hotel?',
      kind: 'sentence',
      notes: ['The vocative takes a comma: chetta is addressed, never the subject.'],
      segments: [
        { token: 'chetta,', gloss: 'chetta (addressing him)' },
        { token: 'hotelilekk', gloss: 'to the hotel' },
        { token: 'pokunnundo', gloss: 'are you going?' },
      ],
      audio: { slow: 'chetta-hotelilekk-pokunnundo.slow', medium: 'chetta-hotelilekk-pokunnundo.medium', normal: 'chetta-hotelilekk-pokunnundo.normal' },
      tags: ['level:3'],
    },
  ],
  pairs: [],
  drills: [
    { kind: 'multipleChoice', itemId: 'veettilekk', distractors: ['hotelilekk', 'officilekk', 'njan-hotelilekk-pokuva'] },
    { kind: 'multipleChoice', itemId: 'hotelilekk', distractors: ['veettilekk', 'officilekk', 'njan-officilekk-pokuva'] },
    { kind: 'multipleChoice', itemId: 'officilekk', distractors: ['veettilekk', 'hotelilekk', 'kadayilekk'] },
    { kind: 'multipleChoice', itemId: 'kadayilekk', distractors: ['veettilekk', 'hotelilekk', 'officilekk'] },
    { kind: 'multipleChoice', itemId: 'chetta-hotelilekk-pokunnundo', distractors: ['avan-hotelilekk-pokuva', 'avan-hotelilekk-varunnundo', 'njan-hotelilekk-pokuva'] },
    {
      kind: 'sentenceBuilder',
      sentenceId: 'njan-hotelilekk-pokuva',
      bank: ['njan', 'hotelilekk', 'pokuva'],
      acceptedInputs: ['njan hotelilekk pokuva'],
    },
    {
      kind: 'sentenceBuilder',
      sentenceId: 'njan-veettilekk-pokuva',
      bank: ['njan', 'veettilekk', 'pokuva'],
      acceptedInputs: ['njan veettilekk pokuva'],
    },
    {
      kind: 'sentenceBuilder',
      sentenceId: 'avan-hotelilekk-varunnundo',
      bank: ['avan', 'hotelilekk', 'varunnundo'],
      acceptedInputs: ['avan hotelilekk varunundo'],
    },
    {
      kind: 'sentenceBuilder',
      sentenceId: 'chetta-hotelilekk-pokunnundo',
      bank: ['chetta,', 'hotelilekk', 'pokunnundo'],
      acceptedInputs: ['chetta hotelilekk pokunundo'],
    },
    { kind: 'typing', itemId: 'hotelilekk', acceptedInputs: ['hotelilekk'] },
  ],
}
