/**
 * Level 3 Unit 1 Lesson 1 — The -il case (PLAN.md §5): where things
 * are and where you are going. The flagship pattern is suffix
 * assimilation onto English words, exactly how Kerala speaks.
 */

import type { Lesson } from '../../types'

export const lesson1CasesIl: Lesson = {
  id: 'l3u1l1',
  levelId: 'level3',
  unitId: 'unit1',
  title: 'Where: -il',
  reviewSlots: 2,
  sprite: { file: 'audio/l3u1l1.mp3' },
  items: [
    {
      id: 'veettil',
      manglish: 'veettil',
      script: 'വീട്ടിൽ',
      meaning: 'at home (veedu + il)',
      kind: 'word',
      pos: 'noun',
      notes: ['-il attaches to words: veedu (home) + il = veettil, with the d doubling.'],
      audio: { slow: 'veettil.slow', medium: 'veettil.medium', normal: 'veettil.normal' },
      tags: ['level:3'],
    },
    {
      id: 'officil',
      manglish: 'officil',
      meaning: 'at the office (office + il)',
      kind: 'word',
      pos: 'noun',
      notes: [
        '-il attaches to English words too: office + il = officil.',
        'No script here: the English word has no settled Malayalam spelling.',
      ],
      audio: { slow: 'officil.slow', medium: 'officil.medium', normal: 'officil.normal' },
      tags: ['level:3'],
    },
    {
      id: 'shoppil',
      manglish: 'shoppil',
      meaning: 'at the shop (shop + il)',
      kind: 'word',
      pos: 'noun',
      notes: ['No script here: the English word has no settled Malayalam spelling.'],
      audio: { slow: 'shoppil.slow', medium: 'shoppil.medium', normal: 'shoppil.normal' },
      tags: ['level:3'],
    },
    {
      id: 'busil',
      manglish: 'busil',
      meaning: 'on the bus (bus + il)',
      kind: 'word',
      pos: 'noun',
      notes: ['No script here: the English word has no settled Malayalam spelling.'],
      audio: { slow: 'busil.slow', medium: 'busil.medium', normal: 'busil.normal' },
      tags: ['level:3'],
    },
    {
      id: 'njan-officil-pokuva',
      manglish: 'njan officil pokuva',
      meaning: 'I am going to the office.',
      kind: 'sentence',
      notes: ['-il covers "to" with going verbs: officil pokuva, going to the office.'],
      segments: [
        { token: 'njan', gloss: 'I' },
        { token: 'officil', gloss: 'to the office' },
        { token: 'pokuva', gloss: 'going' },
      ],
      audio: { slow: 'njan-officil-pokuva.slow', medium: 'njan-officil-pokuva.medium', normal: 'njan-officil-pokuva.normal' },
      tags: ['level:3'],
    },
    {
      id: 'njan-veettil-und',
      manglish: 'njan veettil und',
      script: 'ഞാൻ വീട്ടിൽ ഉണ്ട്',
      meaning: 'I am at home.',
      kind: 'sentence',
      segments: [
        { token: 'njan', gloss: 'I' },
        { token: 'veettil', gloss: 'at home' },
        { token: 'und', gloss: 'am (at a place)' },
      ],
      audio: { slow: 'njan-veettil-und.slow', medium: 'njan-veettil-und.medium', normal: 'njan-veettil-und.normal' },
      tags: ['level:3'],
    },
    {
      id: 'avan-shoppil-und',
      manglish: 'avan shoppil und',
      meaning: 'he is at the shop.',
      kind: 'sentence',
      notes: ['No script here: the English word has no settled Malayalam spelling.'],
      segments: [
        { token: 'avan', gloss: 'he' },
        { token: 'shoppil', gloss: 'at the shop' },
        { token: 'und', gloss: 'is (at a place)' },
      ],
      audio: { slow: 'avan-shoppil-und.slow', medium: 'avan-shoppil-und.medium', normal: 'avan-shoppil-und.normal' },
      tags: ['level:3'],
    },
    {
      id: 'njan-busil-und',
      manglish: 'njan busil und',
      meaning: 'I am on the bus.',
      kind: 'sentence',
      notes: ['No script here: the English word has no settled Malayalam spelling.'],
      segments: [
        { token: 'njan', gloss: 'I' },
        { token: 'busil', gloss: 'on the bus' },
        { token: 'und', gloss: 'am (at a place)' },
      ],
      audio: { slow: 'njan-busil-und.slow', medium: 'njan-busil-und.medium', normal: 'njan-busil-und.normal' },
      tags: ['level:3'],
    },
    {
      id: 'chaaya-veettil-und',
      manglish: 'chaaya veettil und',
      script: 'ചായ വീട്ടിൽ ഉണ്ട്',
      meaning: 'there is tea at home.',
      kind: 'sentence',
      segments: [
        { token: 'chaaya', gloss: 'tea' },
        { token: 'veettil', gloss: 'at home' },
        { token: 'und', gloss: 'there is' },
      ],
      audio: { slow: 'chaaya-veettil-und.slow', medium: 'chaaya-veettil-und.medium', normal: 'chaaya-veettil-und.normal' },
      tags: ['level:3'],
    },
    {
      id: 'aunty-officil-und',
      manglish: 'aunty officil und',
      meaning: 'aunty is at the office.',
      kind: 'sentence',
      notes: ['No script here: the English words have no settled Malayalam spelling.'],
      segments: [
        { token: 'aunty', gloss: 'aunty' },
        { token: 'officil', gloss: 'at the office' },
        { token: 'und', gloss: 'is (at a place)' },
      ],
      audio: { slow: 'aunty-officil-und.slow', medium: 'aunty-officil-und.medium', normal: 'aunty-officil-und.normal' },
      tags: ['level:3'],
    },
  ],
  pairs: [],
  drills: [
    { kind: 'multipleChoice', itemId: 'veettil', distractors: ['officil', 'shoppil', 'busil'] },
    { kind: 'multipleChoice', itemId: 'officil', distractors: ['veettil', 'shoppil', 'busil'] },
    { kind: 'multipleChoice', itemId: 'shoppil', distractors: ['veettil', 'officil', 'busil'] },
    { kind: 'multipleChoice', itemId: 'busil', distractors: ['veettil', 'officil', 'shoppil'] },
    {
      kind: 'sentenceBuilder',
      sentenceId: 'njan-officil-pokuva',
      bank: ['njan', 'officil', 'pokuva'],
      acceptedInputs: ['njan officil pokuva'],
    },
    {
      kind: 'sentenceBuilder',
      sentenceId: 'njan-veettil-und',
      bank: ['njan', 'veettil', 'und'],
      acceptedInputs: ['njan veettil und'],
    },
    {
      kind: 'sentenceBuilder',
      sentenceId: 'chaaya-veettil-und',
      bank: ['chaaya', 'veettil', 'und'],
      acceptedInputs: ['chaaya veettil und'],
    },
    {
      kind: 'sentenceBuilder',
      sentenceId: 'njan-busil-und',
      bank: ['njan', 'busil', 'und'],
      acceptedInputs: ['njan busil und'],
    },
    { kind: 'typing', itemId: 'officil', acceptedInputs: ['officil'] },
  ],
}
