/**
 * Level 3 Unit 1 Lesson 3 — The -kku case (PLAN.md §5): to/for with
 * the dative, and -kku on English words (jolikku). Frames:
 * [word] + [suffix] + [verb].
 */

import type { Lesson } from '../../types'

export const lesson3CasesKku: Lesson = {
  id: 'l3u1l3',
  levelId: 'level3',
  unitId: 'unit3',
  title: 'To and for: -kku',
  reviewSlots: 2,
  sprite: { file: 'audio/l3u1l3.mp3' },
  items: [
    {
      id: 'jolikku',
      manglish: 'jolikku',
      script: 'ജോലിക്ക്',
      meaning: 'to work (joli + kku)',
      kind: 'word',
      pos: 'noun',
      notes: ['-kku attaches to words: joli (work) + kku = jolikku. Fast speech drops to jolikk.'],
      audio: { slow: 'jolikku.slow', medium: 'jolikku.medium', normal: 'jolikku.normal' },
      tags: ['level:3'],
    },
    {
      id: 'enikk',
      manglish: 'enikk',
      script: 'എനിക്ക്',
      meaning: 'to me',
      kind: 'word',
      pos: 'pronoun',
      notes: ['The dative: wanting takes enikk (to me), never njan.'],
      audio: { slow: 'enikk.slow', medium: 'enikk.medium', normal: 'enikk.normal' },
      tags: ['level:3'],
    },
    {
      id: 'ninakk',
      manglish: 'ninakk',
      script: 'നിനക്ക്',
      meaning: 'to you (casual)',
      kind: 'word',
      pos: 'pronoun',
      notes: ['It is the dative of nee (you): ninakk, to you. Wanting takes ninakk, never nee.'],
      audio: { slow: 'ninakk.slow', medium: 'ninakk.medium', normal: 'ninakk.normal' },
      tags: ['level:3'],
    },
    {
      id: 'avanu',
      manglish: 'avanu',
      script: 'അവന്',
      meaning: 'to him',
      kind: 'word',
      pos: 'pronoun',
      notes: ['It is the dative of avan (he): avanu, to him.'],
      audio: { slow: 'avanu.slow', medium: 'avanu.medium', normal: 'avanu.normal' },
      tags: ['level:3'],
    },
    {
      id: 'avanu-chaaya-ishttamilla',
      manglish: 'avanu chaaya ishttamilla',
      script: 'അവന് ചായ ഇഷ്ടമില്ല',
      meaning: 'he does not like tea.',
      kind: 'sentence',
      notes: ['The dative experiencer: avanu (to him) + ishttamilla (is not liked) = he does not like it.'],
      segments: [
        { token: 'avanu', gloss: 'to him' },
        { token: 'chaaya', gloss: 'tea' },
        { token: 'ishttamilla', gloss: 'is not liked' },
      ],
      audio: { slow: 'avanu-chaaya-ishttamilla.slow', medium: 'avanu-chaaya-ishttamilla.medium', normal: 'avanu-chaaya-ishttamilla.normal' },
      tags: ['level:3'],
    },
    {
      id: 'njan-jolikku-pokuva',
      manglish: 'njan jolikku pokuva',
      script: 'ഞാൻ ജോലിക്ക് പോകുവാ',
      meaning: 'I am going to work.',
      kind: 'sentence',
      notes: ['This is the frame: [who] + [place with -kku] + [verb].'],
      segments: [
        { token: 'njan', gloss: 'I' },
        { token: 'jolikku', gloss: 'to work' },
        { token: 'pokuva', gloss: 'going' },
      ],
      audio: { slow: 'njan-jolikku-pokuva.slow', medium: 'njan-jolikku-pokuva.medium', normal: 'njan-jolikku-pokuva.normal' },
      tags: ['level:3'],
    },
    {
      id: 'ninakk-chaaya-veno',
      manglish: 'ninakk chaaya veno',
      script: 'നിനക്ക് ചായ വേണോ',
      meaning: 'do you want tea? (casual)',
      kind: 'sentence',
      segments: [
        { token: 'ninakk', gloss: 'to you (casual)' },
        { token: 'chaaya', gloss: 'tea' },
        { token: 'veno', gloss: 'do you want?' },
      ],
      audio: { slow: 'ninakk-chaaya-veno.slow', medium: 'ninakk-chaaya-veno.medium', normal: 'ninakk-chaaya-veno.normal' },
      tags: ['level:3'],
    },
    {
      id: 'chetta-jolikku-pokunnundo',
      manglish: 'chetta, jolikku pokunnundo',
      meaning: 'chetta, are you going to work?',
      kind: 'sentence',
      notes: ['The vocative takes a comma: chetta is addressed, never the subject.'],
      segments: [
        { token: 'chetta,', gloss: 'chetta (addressing him)' },
        { token: 'jolikku', gloss: 'to work' },
        { token: 'pokunnundo', gloss: 'are you going?' },
      ],
      audio: { slow: 'chetta-jolikku-pokunnundo.slow', medium: 'chetta-jolikku-pokunnundo.medium', normal: 'chetta-jolikku-pokunnundo.normal' },
      tags: ['level:3'],
    },
    {
      id: 'avan-jolikku-pokuva',
      manglish: 'avan jolikku pokuva',
      script: 'അവൻ ജോലിക്ക് പോകുവാ',
      meaning: 'he is going to work.',
      kind: 'sentence',
      segments: [
        { token: 'avan', gloss: 'he' },
        { token: 'jolikku', gloss: 'to work' },
        { token: 'pokuva', gloss: 'going' },
      ],
      audio: { slow: 'avan-jolikku-pokuva.slow', medium: 'avan-jolikku-pokuva.medium', normal: 'avan-jolikku-pokuva.normal' },
      tags: ['level:3'],
    },
    {
      id: 'enikk-sheri-aa',
      manglish: 'enikk sheri aa',
      script: 'എനിക്ക് ശെരി ആ',
      meaning: 'fine by me.',
      kind: 'sentence',
      segments: [
        { token: 'enikk', gloss: 'to me' },
        { token: 'sheri', gloss: 'fine' },
        { token: 'aa', gloss: 'is' },
      ],
      audio: { slow: 'enikk-sheri-aa.slow', medium: 'enikk-sheri-aa.medium', normal: 'enikk-sheri-aa.normal' },
      tags: ['level:3'],
    },
    {
      id: 'ninakk-sheri-aano',
      manglish: 'ninakk sheri aano',
      script: 'നിനക്ക് ശെരി ആണോ',
      meaning: 'is that fine with you? (casual)',
      kind: 'sentence',
      segments: [
        { token: 'ninakk', gloss: 'to you (casual)' },
        { token: 'sheri', gloss: 'fine' },
        { token: 'aano', gloss: 'is it?' },
      ],
      audio: { slow: 'ninakk-sheri-aano.slow', medium: 'ninakk-sheri-aano.medium', normal: 'ninakk-sheri-aano.normal' },
      tags: ['level:3'],
    },
    {
      id: 'enikk-venam',
      manglish: 'enikk venam',
      script: 'എനിക്ക് വേണം',
      meaning: 'I want it.',
      kind: 'sentence',
      segments: [
        { token: 'enikk', gloss: 'to me' },
        { token: 'venam', gloss: 'want' },
      ],
      audio: { slow: 'enikk-venam.slow', medium: 'enikk-venam.medium', normal: 'enikk-venam.normal' },
      tags: ['level:3'],
    },
  ],
  pairs: [],
  drills: [
    { kind: 'multipleChoice', itemId: 'jolikku', distractors: ['enikk', 'ninakk', 'njan-jolikku-pokuva'] },
    { kind: 'multipleChoice', itemId: 'enikk', distractors: ['ninakk', 'jolikku', 'ninakk-chaaya-veno'] },
    { kind: 'multipleChoice', itemId: 'ninakk', distractors: ['enikk', 'jolikku', 'enikk-venam'] },
    { kind: 'multipleChoice', itemId: 'avanu', distractors: ['enikk', 'ninakk', 'jolikku'] },
    { kind: 'multipleChoice', itemId: 'avanu-chaaya-ishttamilla', distractors: ['ninakk-chaaya-veno', 'enikk-venam', 'ninakk-sheri-aano'] },
    {
      kind: 'sentenceBuilder',
      sentenceId: 'avanu-chaaya-ishttamilla',
      bank: ['avanu', 'chaaya', 'ishttamilla'],
      acceptedInputs: ['avanu chaaya ishttamilla'],
    },
    { kind: 'multipleChoice', itemId: 'ninakk-sheri-aano', distractors: ['enikk-sheri-aa', 'ninakk-chaaya-veno', 'enikk-venam'] },
    {
      kind: 'sentenceBuilder',
      sentenceId: 'njan-jolikku-pokuva',
      bank: ['njan', 'jolikku', 'pokuva'],
      acceptedInputs: ['njan jolikku pokuva'],
    },
    {
      kind: 'sentenceBuilder',
      sentenceId: 'ninakk-chaaya-veno',
      bank: ['ninakk', 'chaaya', 'veno'],
      acceptedInputs: ['ninakk chaaya veno'],
    },
    {
      kind: 'sentenceBuilder',
      sentenceId: 'chetta-jolikku-pokunnundo',
      bank: ['chetta,', 'jolikku', 'pokunnundo'],
      acceptedInputs: ['chetta jolikku pokunundo'],
    },
    {
      kind: 'sentenceBuilder',
      sentenceId: 'enikk-sheri-aa',
      bank: ['enikk', 'sheri', 'aa'],
      acceptedInputs: ['enikk sheri aa'],
    },
    { kind: 'typing', itemId: 'enikk', acceptedInputs: ['enikk'] },
    { kind: 'typing', itemId: 'ninakk', acceptedInputs: ['ninakk'] },
  ],
}
