/**
 * Level 3 Unit 1 Lesson 4 — The -nte case (PLAN.md §5): of and whose.
 * Frames: [owner + nte] + [thing] + [aanu]. -nte attaches to English
 * words and to names exactly as it does to Malayalam ones.
 */

import type { Lesson } from '../../types'

export const lesson4CasesNte: Lesson = {
  id: 'l3u1l4',
  levelId: 'level3',
  unitId: 'unit4',
  title: 'Of: -nte',
  reviewSlots: 2,
  sprite: { file: 'audio/l3u1l4.mp3' },
  items: [
    {
      id: 'chettante',
      manglish: 'chettante',
      script: 'ചേട്ടന്റെ',
      meaning: "elder brother's (chettan + nte)",
      kind: 'word',
      pos: 'noun',
      notes: ['To say whose something is, add -nte to the owner: chettan (elder brother) + nte = chettante.'],
      audio: { slow: 'chettante.slow', medium: 'chettante.medium', normal: 'chettante.normal' },
      tags: ['level:3'],
    },
    {
      id: 'avante',
      manglish: 'avante',
      script: 'അവന്റെ',
      meaning: 'his (avan + nte)',
      kind: 'word',
      pos: 'pronoun',
      notes: ['The same suffix on avan (he): avante, his. It sits before the thing owned.'],
      audio: { slow: 'avante.slow', medium: 'avante.medium', normal: 'avante.normal' },
      tags: ['level:3'],
    },
    {
      id: 'njangalude',
      manglish: 'njangaḷude',
      script: 'ഞങ്ങളുടെ',
      meaning: 'our (njangaḷ + ude)',
      kind: 'word',
      pos: 'pronoun',
      acceptedInputs: ['njangalude'],
      notes: ['After a word ending in ḷ the suffix sounds as -ude: njangaḷ (we) + ude = njangaḷude.'],
      audio: { slow: 'njangalude.slow', medium: 'njangalude.medium', normal: 'njangalude.normal' },
      tags: ['level:3'],
    },
    {
      id: 'kadayude',
      manglish: 'kadayude',
      script: 'കടയുടെ',
      meaning: 'of the shop (kada + yude)',
      kind: 'word',
      pos: 'noun',
      notes: ['kada ends in a vowel, so the suffix glides in as -yude: kada + yude = kadayude.'],
      audio: { slow: 'kadayude.slow', medium: 'kadayude.medium', normal: 'kadayude.normal' },
      tags: ['level:3'],
    },
    {
      id: 'officinte',
      manglish: 'officinte',
      meaning: 'of the office (office + nte)',
      kind: 'word',
      pos: 'noun',
      notes: [
        '-nte attaches to English words too: office + nte = officinte.',
        'No script here: the English word has no settled Malayalam spelling.',
      ],
      audio: { slow: 'officinte.slow', medium: 'officinte.medium', normal: 'officinte.normal' },
      tags: ['level:3'],
    },
    {
      id: 'businte',
      manglish: 'businte',
      meaning: 'of the bus (bus + nte)',
      kind: 'word',
      pos: 'noun',
      notes: ['No script here: the English word has no settled Malayalam spelling.'],
      audio: { slow: 'businte.slow', medium: 'businte.medium', normal: 'businte.normal' },
      tags: ['level:3'],
    },
    {
      id: 'ithu-ente-veedu-aanu',
      manglish: 'ithu ente veedu aanu',
      script: 'ഇത് എന്റെ വീട് ആണ്',
      meaning: 'this is my house.',
      kind: 'sentence',
      notes: ['This is the frame: [this] + [owner with -nte] + [thing] + [aanu].'],
      segments: [
        { token: 'ithu', gloss: 'this' },
        { token: 'ente', gloss: 'my' },
        { token: 'veedu', gloss: 'house' },
        { token: 'aanu', gloss: 'is' },
      ],
      audio: { slow: 'ithu-ente-veedu-aanu.slow', medium: 'ithu-ente-veedu-aanu.medium', normal: 'ithu-ente-veedu-aanu.normal' },
      tags: ['level:3'],
    },
    {
      id: 'ithu-ente-chettante-veedu-aanu',
      manglish: 'ithu ente chettante veedu aanu',
      script: 'ഇത് എന്റെ ചേട്ടന്റെ വീട് ആണ്',
      meaning: "this is my elder brother's house.",
      kind: 'sentence',
      segments: [
        { token: 'ithu', gloss: 'this' },
        { token: 'ente', gloss: 'my' },
        { token: 'chettante', gloss: "elder brother's" },
        { token: 'veedu', gloss: 'house' },
        { token: 'aanu', gloss: 'is' },
      ],
      audio: { slow: 'ithu-ente-chettante-veedu-aanu.slow', medium: 'ithu-ente-chettante-veedu-aanu.medium', normal: 'ithu-ente-chettante-veedu-aanu.normal' },
      tags: ['level:3'],
    },
    {
      id: 'ithu-avante-veedu-aanu',
      manglish: 'ithu avante veedu aanu',
      script: 'ഇത് അവന്റെ വീട് ആണ്',
      meaning: 'this is his house.',
      kind: 'sentence',
      segments: [
        { token: 'ithu', gloss: 'this' },
        { token: 'avante', gloss: 'his' },
        { token: 'veedu', gloss: 'house' },
        { token: 'aanu', gloss: 'is' },
      ],
      audio: { slow: 'ithu-avante-veedu-aanu.slow', medium: 'ithu-avante-veedu-aanu.medium', normal: 'ithu-avante-veedu-aanu.normal' },
      tags: ['level:3'],
    },
    {
      id: 'avan-ente-chettan-aanu',
      manglish: 'avan ente chettan aanu',
      script: 'അവൻ എന്റെ ചേട്ടൻ ആണ്',
      meaning: 'he is my elder brother.',
      kind: 'sentence',
      segments: [
        { token: 'avan', gloss: 'he' },
        { token: 'ente', gloss: 'my' },
        { token: 'chettan', gloss: 'elder brother' },
        { token: 'aanu', gloss: 'is' },
      ],
      audio: { slow: 'avan-ente-chettan-aanu.slow', medium: 'avan-ente-chettan-aanu.medium', normal: 'avan-ente-chettan-aanu.normal' },
      tags: ['level:3'],
    },
    {
      id: 'avante-veedu-evide-aanu',
      manglish: 'avante veedu evide aanu',
      script: 'അവന്റെ വീട് എവിടെ ആണ്',
      meaning: 'where is his house?',
      kind: 'sentence',
      segments: [
        { token: 'avante', gloss: 'his' },
        { token: 'veedu', gloss: 'house' },
        { token: 'evide', gloss: 'where?' },
        { token: 'aanu', gloss: 'is' },
      ],
      audio: { slow: 'avante-veedu-evide-aanu.slow', medium: 'avante-veedu-evide-aanu.medium', normal: 'avante-veedu-evide-aanu.normal' },
      tags: ['level:3'],
    },
    {
      id: 'ithu-njangalude-kada-aanu',
      manglish: 'ithu njangaḷude kada aanu',
      script: 'ഇത് ഞങ്ങളുടെ കട ആണ്',
      meaning: 'this is our shop.',
      kind: 'sentence',
      segments: [
        { token: 'ithu', gloss: 'this' },
        { token: 'njangaḷude', gloss: 'our' },
        { token: 'kada', gloss: 'shop' },
        { token: 'aanu', gloss: 'is' },
      ],
      audio: { slow: 'ithu-njangalude-kada-aanu.slow', medium: 'ithu-njangalude-kada-aanu.medium', normal: 'ithu-njangalude-kada-aanu.normal' },
      tags: ['level:3'],
    },
  ],
  pairs: [],
  drills: [
    { kind: 'multipleChoice', itemId: 'chettante', distractors: ['avante', 'njangalude', 'kadayude'] },
    { kind: 'multipleChoice', itemId: 'avante', distractors: ['chettante', 'njangalude', 'kadayude'] },
    { kind: 'multipleChoice', itemId: 'njangalude', distractors: ['chettante', 'avante', 'kadayude'] },
    { kind: 'multipleChoice', itemId: 'kadayude', distractors: ['chettante', 'avante', 'njangalude'] },
    { kind: 'multipleChoice', itemId: 'officinte', distractors: ['businte', 'kadayude', 'avante'] },
    {
      kind: 'sentenceBuilder',
      sentenceId: 'ithu-ente-veedu-aanu',
      bank: ['ithu', 'ente', 'veedu', 'aanu'],
      acceptedInputs: ['ithu ente veedu aanu'],
    },
    {
      kind: 'sentenceBuilder',
      sentenceId: 'ithu-ente-chettante-veedu-aanu',
      bank: ['ithu', 'ente', 'chettante', 'veedu', 'aanu'],
      acceptedInputs: ['ithu ente chettante veedu aanu'],
    },
    {
      kind: 'sentenceBuilder',
      sentenceId: 'ithu-avante-veedu-aanu',
      bank: ['ithu', 'avante', 'veedu', 'aanu'],
      acceptedInputs: ['ithu avante veedu aanu'],
    },
    {
      kind: 'sentenceBuilder',
      sentenceId: 'avan-ente-chettan-aanu',
      bank: ['avan', 'ente', 'chettan', 'aanu'],
      acceptedInputs: ['avan ente chettan aanu'],
    },
    {
      kind: 'sentenceBuilder',
      sentenceId: 'ithu-njangalude-kada-aanu',
      bank: ['ithu', 'njangaḷude', 'kada', 'aanu'],
      acceptedInputs: ['ithu njangalude kada aanu'],
    },
    { kind: 'multipleChoice', itemId: 'avante-veedu-evide-aanu', distractors: ['ithu-avante-veedu-aanu', 'ithu-ente-veedu-aanu', 'avan-ente-chettan-aanu'] },
    { kind: 'typing', itemId: 'chettante', acceptedInputs: ['chettante', 'chettande'] },
    { kind: 'typing', itemId: 'njangalude', acceptedInputs: ['njangaḷude', 'njangalude', 'njangaḷde'] },
  ],
}
