/**
 * Level 3 Unit 1 Lesson 6 — From and as (PLAN.md §5): -il ninn for
 * where something comes from, and -aayi for what someone becomes.
 * The short colloquial ninn is the one already heard in
 * njan veettil ninn irangi.
 */

import type { Lesson } from '../../types'

export const lesson6CasesFrom: Lesson = {
  id: 'l3u1l6',
  levelId: 'level3',
  unitId: 'unit6',
  title: 'From and as: ninn, -aayi',
  reviewSlots: 2,
  sprite: { file: 'audio/l3u1l6.mp3' },
  items: [
    {
      id: 'ninn',
      manglish: 'ninn',
      script: 'നിന്ന്',
      meaning: 'from',
      kind: 'word',
      pos: 'particle',
      notes: [
        'ninn is the everyday "from". It comes after the -il form of the place: veettil ninn, from home.',
        'You already heard it in njan veettil ninn irangi (I just left home).',
      ],
      audio: { slow: 'ninn.slow', medium: 'ninn.medium', normal: 'ninn.normal' },
      tags: ['level:3'],
    },
    {
      id: 'veettil-ninn',
      manglish: 'veettil ninn',
      script: 'വീട്ടിൽ നിന്ന്',
      meaning: 'from home (veettil + ninn)',
      kind: 'word',
      pos: 'noun',
      notes: ['The frame is [place with -il] + ninn: veettil (at home) + ninn = from home.'],
      audio: { slow: 'veettil-ninn.slow', medium: 'veettil-ninn.medium', normal: 'veettil-ninn.normal' },
      tags: ['level:3'],
    },
    {
      id: 'officil-ninn',
      manglish: 'officil ninn',
      meaning: 'from the office (officil + ninn)',
      kind: 'word',
      pos: 'noun',
      notes: [
        'English words take the pair just as they take -il: officil ninn, from the office.',
        'No script here: the English word has no settled Malayalam spelling.',
      ],
      audio: { slow: 'officil-ninn.slow', medium: 'officil-ninn.medium', normal: 'officil-ninn.normal' },
      tags: ['level:3'],
    },
    {
      id: 'busil-ninn',
      manglish: 'busil ninn',
      meaning: 'from the bus (busil + ninn)',
      kind: 'word',
      pos: 'noun',
      notes: ['No script here: the English word has no settled Malayalam spelling.'],
      audio: { slow: 'busil-ninn.slow', medium: 'busil-ninn.medium', normal: 'busil-ninn.normal' },
      tags: ['level:3'],
    },
    {
      id: 'kadayil-ninn',
      manglish: 'kadayil ninn',
      script: 'കടയിൽ നിന്ന്',
      meaning: 'from the shop (kadayil + ninn)',
      kind: 'word',
      pos: 'noun',
      notes: ['kadayil (at the shop) + ninn = from the shop.'],
      audio: { slow: 'kadayil-ninn.slow', medium: 'kadayil-ninn.medium', normal: 'kadayil-ninn.normal' },
      tags: ['level:3'],
    },
    {
      id: 'njan-veettil-ninn-varuva',
      manglish: 'njan veettil ninn varuva',
      script: 'ഞാൻ വീട്ടിൽ നിന്ന് വരുവാ',
      meaning: 'I am coming from home.',
      kind: 'sentence',
      notes: ['This is the frame: [who] + [place with -il] + ninn + [verb].'],
      segments: [
        { token: 'njan', gloss: 'I' },
        { token: 'veettil', gloss: 'at home' },
        { token: 'ninn', gloss: 'from' },
        { token: 'varuva', gloss: 'coming' },
      ],
      audio: { slow: 'njan-veettil-ninn-varuva.slow', medium: 'njan-veettil-ninn-varuva.medium', normal: 'njan-veettil-ninn-varuva.normal' },
      tags: ['level:3'],
    },
    {
      id: 'avan-kadayil-ninn-varunnund',
      manglish: 'avan kadayil ninn varunnund',
      script: 'അവൻ കടയിൽ നിന്ന് വരുന്നുണ്ട്',
      meaning: 'he is coming from the shop.',
      kind: 'sentence',
      segments: [
        { token: 'avan', gloss: 'he' },
        { token: 'kadayil', gloss: 'at the shop' },
        { token: 'ninn', gloss: 'from' },
        { token: 'varunnund', gloss: 'is coming' },
      ],
      audio: { slow: 'avan-kadayil-ninn-varunnund.slow', medium: 'avan-kadayil-ninn-varunnund.medium', normal: 'avan-kadayil-ninn-varunnund.normal' },
      tags: ['level:3'],
    },
    {
      id: 'njan-officil-ninn-varunnund',
      manglish: 'njan officil ninn varunnund',
      meaning: 'I am coming from the office.',
      kind: 'sentence',
      notes: ['No script here: the English word has no settled Malayalam spelling.'],
      segments: [
        { token: 'njan', gloss: 'I' },
        { token: 'officil', gloss: 'at the office' },
        { token: 'ninn', gloss: 'from' },
        { token: 'varunnund', gloss: 'am coming' },
      ],
      audio: { slow: 'njan-officil-ninn-varunnund.slow', medium: 'njan-officil-ninn-varunnund.medium', normal: 'njan-officil-ninn-varunnund.normal' },
      tags: ['level:3'],
    },
    {
      id: 'avan-busil-ninn-irangi',
      manglish: 'avan busil ninn irangi',
      meaning: 'he got off the bus.',
      kind: 'sentence',
      notes: [
        'irangi is the past of iranguva (to get down): busil ninn irangi, got down from the bus.',
        'No script here: the English word has no settled Malayalam spelling.',
      ],
      segments: [
        { token: 'avan', gloss: 'he' },
        { token: 'busil', gloss: 'on the bus' },
        { token: 'ninn', gloss: 'from' },
        { token: 'irangi', gloss: 'got down' },
      ],
      audio: { slow: 'avan-busil-ninn-irangi.slow', medium: 'avan-busil-ninn-irangi.medium', normal: 'avan-busil-ninn-irangi.normal' },
      tags: ['level:3'],
    },
    {
      id: 'avan-evide-ninn-varunnund',
      manglish: 'avan evide ninn varunnund',
      script: 'അവൻ എവിടെ നിന്ന് വരുന്നുണ്ട്',
      meaning: 'where is he coming from?',
      kind: 'sentence',
      notes: ['evide (where) + ninn asks about the starting point: evide ninn, from where.'],
      segments: [
        { token: 'avan', gloss: 'he' },
        { token: 'evide', gloss: 'where?' },
        { token: 'ninn', gloss: 'from' },
        { token: 'varunnund', gloss: 'is coming' },
      ],
      audio: { slow: 'avan-evide-ninn-varunnund.slow', medium: 'avan-evide-ninn-varunnund.medium', normal: 'avan-evide-ninn-varunnund.normal' },
      tags: ['level:3'],
    },
    {
      id: 'njan-ippo-veettil-ninn-pokuva',
      manglish: 'njan ippo veettil ninn pokuva',
      script: 'ഞാൻ ഇപ്പോ വീട്ടിൽ നിന്ന് പോകുവാ',
      meaning: 'I am leaving home now.',
      kind: 'sentence',
      segments: [
        { token: 'njan', gloss: 'I' },
        { token: 'ippo', gloss: 'now' },
        { token: 'veettil', gloss: 'at home' },
        { token: 'ninn', gloss: 'from' },
        { token: 'pokuva', gloss: 'going' },
      ],
      audio: { slow: 'njan-ippo-veettil-ninn-pokuva.slow', medium: 'njan-ippo-veettil-ninn-pokuva.medium', normal: 'njan-ippo-veettil-ninn-pokuva.normal' },
      tags: ['level:3'],
    },
    {
      id: 'sheri-aayi',
      manglish: 'sheri aayi',
      script: 'ശെരി ആയി',
      meaning: 'okay, that is done.',
      kind: 'phrase',
      notes: ['-aayi is "became": sheri (fine) + aayi = it became fine, which is how people say done.'],
      audio: { slow: 'sheri-aayi.slow', medium: 'sheri-aayi.medium', normal: 'sheri-aayi.normal' },
      tags: ['level:3'],
    },
    {
      id: 'njan-ready-aayi',
      manglish: 'njan ready aayi',
      meaning: 'I have got ready.',
      kind: 'sentence',
      notes: [
        '-aayi attaches to English words: ready + aayi = became ready, got ready.',
        'No script here: the English word has no settled Malayalam spelling.',
      ],
      segments: [
        { token: 'njan', gloss: 'I' },
        { token: 'ready', gloss: 'ready' },
        { token: 'aayi', gloss: 'became' },
      ],
      audio: { slow: 'njan-ready-aayi.slow', medium: 'njan-ready-aayi.medium', normal: 'njan-ready-aayi.normal' },
      tags: ['level:3'],
    },
    {
      id: 'avan-oru-teacher-aayi',
      manglish: 'avan oru teacher aayi',
      meaning: 'he became a teacher.',
      kind: 'sentence',
      notes: [
        'aanu says what someone is (avan oru school teacher aanu); aayi says what someone became.',
        'No script here: the English word has no settled Malayalam spelling.',
      ],
      segments: [
        { token: 'avan', gloss: 'he' },
        { token: 'oru', gloss: 'a' },
        { token: 'teacher', gloss: 'teacher' },
        { token: 'aayi', gloss: 'became' },
      ],
      audio: { slow: 'avan-oru-teacher-aayi.slow', medium: 'avan-oru-teacher-aayi.medium', normal: 'avan-oru-teacher-aayi.normal' },
      tags: ['level:3'],
    },
  ],
  pairs: [],
  drills: [
    { kind: 'multipleChoice', itemId: 'ninn', distractors: ['veettil-ninn', 'kadayil-ninn', 'officil-ninn'] },
    { kind: 'multipleChoice', itemId: 'veettil-ninn', distractors: ['kadayil-ninn', 'officil-ninn', 'busil-ninn'] },
    { kind: 'multipleChoice', itemId: 'officil-ninn', distractors: ['busil-ninn', 'veettil-ninn', 'kadayil-ninn'] },
    { kind: 'multipleChoice', itemId: 'sheri-aayi', distractors: ['njan-ready-aayi', 'avan-oru-teacher-aayi', 'ninn'] },
    {
      kind: 'sentenceBuilder',
      sentenceId: 'njan-veettil-ninn-varuva',
      bank: ['njan', 'veettil', 'ninn', 'varuva'],
      acceptedInputs: ['njan veettil ninn varuva'],
    },
    {
      kind: 'sentenceBuilder',
      sentenceId: 'avan-kadayil-ninn-varunnund',
      bank: ['avan', 'kadayil', 'ninn', 'varunnund'],
      acceptedInputs: ['avan kadayil ninn varunnund', 'avan kadayil ninn varunund'],
    },
    {
      kind: 'sentenceBuilder',
      sentenceId: 'njan-officil-ninn-varunnund',
      bank: ['njan', 'officil', 'ninn', 'varunnund'],
      acceptedInputs: ['njan officil ninn varunnund', 'njan officil ninn varunund'],
    },
    {
      kind: 'sentenceBuilder',
      sentenceId: 'avan-busil-ninn-irangi',
      bank: ['avan', 'busil', 'ninn', 'irangi'],
      acceptedInputs: ['avan busil ninn irangi'],
    },
    {
      kind: 'sentenceBuilder',
      sentenceId: 'avan-evide-ninn-varunnund',
      bank: ['avan', 'evide', 'ninn', 'varunnund'],
      acceptedInputs: ['avan evide ninn varunnund', 'avan evide ninn varunund'],
    },
    {
      kind: 'sentenceBuilder',
      sentenceId: 'njan-ippo-veettil-ninn-pokuva',
      bank: ['njan', 'ippo', 'veettil', 'ninn', 'pokuva'],
      acceptedInputs: ['njan ippo veettil ninn pokuva'],
    },
    { kind: 'multipleChoice', itemId: 'njan-ready-aayi', distractors: ['avan-oru-teacher-aayi', 'sheri-aayi', 'njan-veettil-ninn-varuva'] },
    {
      kind: 'sentenceBuilder',
      sentenceId: 'avan-oru-teacher-aayi',
      bank: ['avan', 'oru', 'teacher', 'aayi'],
      acceptedInputs: ['avan oru teacher aayi'],
    },
    { kind: 'typing', itemId: 'ninn', acceptedInputs: ['ninn'] },
    { kind: 'typing', itemId: 'veettil-ninn', acceptedInputs: ['veettil ninn', 'veettil nin'] },
  ],
}
