/**
 * Level 3 Unit 1 Lesson 5 — The -um particle (PLAN.md §5): also and
 * and. -um attaches to the last word of each thing it adds, so it
 * lands on English words and pronouns just as readily.
 */

import type { Lesson } from '../../types'

export const lesson5CasesUm: Lesson = {
  id: 'l3u1l5',
  levelId: 'level3',
  unitId: 'unit5',
  title: 'Also, and: -um',
  reviewSlots: 2,
  sprite: { file: 'audio/l3u1l5.mp3' },
  items: [
    {
      id: 'chaayayum',
      manglish: 'chaayayum',
      script: 'ചായയും',
      meaning: 'tea as well (chaaya + um)',
      kind: 'word',
      pos: 'noun',
      notes: ['-um on a word means too: chaaya (tea) + um = chaayayum, tea too.'],
      audio: { slow: 'chaayayum.slow', medium: 'chaayayum.medium', normal: 'chaayayum.normal' },
      tags: ['level:3'],
    },
    {
      id: 'kaappiyum',
      manglish: 'kaappiyum',
      script: 'കാപ്പിയും',
      meaning: 'coffee as well (kaappi + um)',
      kind: 'word',
      pos: 'noun',
      notes: ['The same particle on kaappi (coffee): kaappiyum, coffee too.'],
      audio: { slow: 'kaappiyum.slow', medium: 'kaappiyum.medium', normal: 'kaappiyum.normal' },
      tags: ['level:3'],
    },
    {
      id: 'avanum',
      manglish: 'avanum',
      script: 'അവനും',
      meaning: 'he too (avan + um)',
      kind: 'word',
      pos: 'pronoun',
      notes: ['-um also attaches to people: avan (he) + um = avanum, he too.'],
      audio: { slow: 'avanum.slow', medium: 'avanum.medium', normal: 'avanum.normal' },
      tags: ['level:3'],
    },
    {
      id: 'enikkum',
      manglish: 'enikkum',
      script: 'എനിക്കും',
      meaning: 'me too (enikk + um)',
      kind: 'word',
      pos: 'pronoun',
      notes: ['It attaches to the dative as well: enikk (to me) + um = enikkum, to me too.'],
      audio: { slow: 'enikkum.slow', medium: 'enikkum.medium', normal: 'enikkum.normal' },
      tags: ['level:3'],
    },
    {
      id: 'njanum',
      manglish: 'njanum',
      script: 'ഞാനും',
      meaning: 'I too (njan + um)',
      kind: 'word',
      pos: 'pronoun',
      notes: ['njan (I) + um = njanum, I too. The written form spells a long a that is short in speech, exactly as in njan.'],
      audio: { slow: 'njanum.slow', medium: 'njanum.medium', normal: 'njanum.normal' },
      tags: ['level:3'],
    },
    {
      id: 'veettilum',
      manglish: 'veettilum',
      script: 'വീട്ടിലും',
      meaning: 'at home as well (veettil + um)',
      kind: 'word',
      pos: 'noun',
      notes: ['A case suffix and -um can stack: veettil (at home) + um = veettilum, at home too.'],
      audio: { slow: 'veettilum.slow', medium: 'veettilum.medium', normal: 'veettilum.normal' },
      tags: ['level:3'],
    },
    {
      id: 'chaayayum-kaappiyum-und',
      manglish: 'chaayayum kaappiyum und',
      script: 'ചായയും കാപ്പിയും ഉണ്ട്',
      meaning: 'there is tea and coffee.',
      kind: 'sentence',
      notes: ['Put -um on each thing and the list means and: chaayayum kaappiyum, tea and coffee.'],
      segments: [
        { token: 'chaayayum', gloss: 'tea too' },
        { token: 'kaappiyum', gloss: 'coffee too' },
        { token: 'und', gloss: 'there is' },
      ],
      audio: { slow: 'chaayayum-kaappiyum-und.slow', medium: 'chaayayum-kaappiyum-und.medium', normal: 'chaayayum-kaappiyum-und.normal' },
      tags: ['level:3'],
    },
    {
      id: 'enikkum-venam',
      manglish: 'enikkum venam',
      script: 'എനിക്കും വേണം',
      meaning: 'I want it too.',
      kind: 'sentence',
      segments: [
        { token: 'enikkum', gloss: 'to me too' },
        { token: 'venam', gloss: 'want' },
      ],
      audio: { slow: 'enikkum-venam.slow', medium: 'enikkum-venam.medium', normal: 'enikkum-venam.normal' },
      tags: ['level:3'],
    },
    {
      id: 'avanum-varunnund',
      manglish: 'avanum varunnund',
      script: 'അവനും വരുന്നുണ്ട്',
      meaning: 'he is coming too.',
      kind: 'sentence',
      segments: [
        { token: 'avanum', gloss: 'he too' },
        { token: 'varunnund', gloss: 'is coming' },
      ],
      audio: { slow: 'avanum-varunnund.slow', medium: 'avanum-varunnund.medium', normal: 'avanum-varunnund.normal' },
      tags: ['level:3'],
    },
    {
      id: 'njanum-varunnund',
      manglish: 'njanum varunnund',
      script: 'ഞാനും വരുന്നുണ്ട്',
      meaning: 'I am coming too.',
      kind: 'sentence',
      segments: [
        { token: 'njanum', gloss: 'I too' },
        { token: 'varunnund', gloss: 'am coming' },
      ],
      audio: { slow: 'njanum-varunnund.slow', medium: 'njanum-varunnund.medium', normal: 'njanum-varunnund.normal' },
      tags: ['level:3'],
    },
    {
      id: 'njanum-avanum-officil-pokuva',
      manglish: 'njanum avanum officil pokuva',
      meaning: 'he and I are both going to the office.',
      kind: 'sentence',
      notes: [
        '-um on two people means and: njanum avanum, I and he.',
        'No script here: the English word has no settled Malayalam spelling.',
      ],
      segments: [
        { token: 'njanum', gloss: 'I too' },
        { token: 'avanum', gloss: 'he too' },
        { token: 'officil', gloss: 'to the office' },
        { token: 'pokuva', gloss: 'going' },
      ],
      audio: { slow: 'njanum-avanum-officil-pokuva.slow', medium: 'njanum-avanum-officil-pokuva.medium', normal: 'njanum-avanum-officil-pokuva.normal' },
      tags: ['level:3'],
    },
    {
      id: 'ente-veettilum-chaaya-und',
      manglish: 'ente veettilum chaaya und',
      script: 'എന്റെ വീട്ടിലും ചായ ഉണ്ട്',
      meaning: 'there is tea at my home too.',
      kind: 'sentence',
      segments: [
        { token: 'ente', gloss: 'my' },
        { token: 'veettilum', gloss: 'at home too' },
        { token: 'chaaya', gloss: 'tea' },
        { token: 'und', gloss: 'there is' },
      ],
      audio: { slow: 'ente-veettilum-chaaya-und.slow', medium: 'ente-veettilum-chaaya-und.medium', normal: 'ente-veettilum-chaaya-und.normal' },
      tags: ['level:3'],
    },
  ],
  pairs: [],
  drills: [
    { kind: 'multipleChoice', itemId: 'chaayayum', distractors: ['kaappiyum', 'avanum', 'enikkum'] },
    { kind: 'multipleChoice', itemId: 'kaappiyum', distractors: ['chaayayum', 'avanum', 'enikkum'] },
    { kind: 'multipleChoice', itemId: 'avanum', distractors: ['enikkum', 'njanum', 'veettilum'] },
    { kind: 'multipleChoice', itemId: 'enikkum', distractors: ['avanum', 'njanum', 'veettilum'] },
    { kind: 'multipleChoice', itemId: 'njanum', distractors: ['avanum', 'enikkum', 'veettilum'] },
    {
      kind: 'sentenceBuilder',
      sentenceId: 'chaayayum-kaappiyum-und',
      bank: ['chaayayum', 'kaappiyum', 'und'],
      acceptedInputs: ['chaayayum kaappiyum und'],
    },
    {
      kind: 'sentenceBuilder',
      sentenceId: 'enikkum-venam',
      bank: ['enikkum', 'venam'],
      acceptedInputs: ['enikkum venam'],
    },
    {
      kind: 'sentenceBuilder',
      sentenceId: 'avanum-varunnund',
      bank: ['avanum', 'varunnund'],
      acceptedInputs: ['avanum varunnund', 'avanum varunund'],
    },
    {
      kind: 'sentenceBuilder',
      sentenceId: 'njanum-varunnund',
      bank: ['njanum', 'varunnund'],
      acceptedInputs: ['njanum varunnund', 'njanum varunund'],
    },
    {
      kind: 'sentenceBuilder',
      sentenceId: 'njanum-avanum-officil-pokuva',
      bank: ['njanum', 'avanum', 'officil', 'pokuva'],
      acceptedInputs: ['njanum avanum officil pokuva'],
    },
    { kind: 'multipleChoice', itemId: 'ente-veettilum-chaaya-und', distractors: ['chaayayum-kaappiyum-und', 'enikkum-venam', 'avanum-varunnund'] },
    {
      kind: 'sentenceBuilder',
      sentenceId: 'ente-veettilum-chaaya-und',
      bank: ['ente', 'veettilum', 'chaaya', 'und'],
      acceptedInputs: ['ente veettilum chaaya und'],
    },
    { kind: 'typing', itemId: 'chaayayum', acceptedInputs: ['chaayayum'] },
    { kind: 'typing', itemId: 'veettilum', acceptedInputs: ['veettilum'] },
  ],
}
