/**
 * Level 2 Unit 4 — Politeness in context (PLAN.md §5): the pronoun
 * ladder in real sentences, from nee to the honorifics, plus title
 * substitution (chetta).
 */

import type { Lesson } from '../../types'

export const lesson4Politeness: Lesson = {
  id: 'l2u1l4',
  levelId: 'level2',
  unitId: 'unit4',
  title: 'Who you’re talking to',
  reviewSlots: 2,
  sprite: { file: 'audio/l2u1l4.mp3' },
  items: [
    {
      id: 'chetta',
      manglish: 'chetta',
      meaning: 'older brother; used to call or address a man',
      kind: 'word',
      pos: 'noun',
      notes: [
        'A calling form: you use it to call or address someone, never to talk about them.',
        'In a sentence the calling form takes a comma: chetta, pokunnundo?',
        'Asking the chettan himself, the calling form is fine: chetta, varunnundo. The Chettan and chechi lesson covers exactly that.',
        'No script here: the written form spells a long a that is short in speech.',
      ],
      audio: { slow: 'chetta.slow', medium: 'chetta.medium', normal: 'chetta.normal' },
      tags: ['level:2'],
    },
    {
      id: 'chetta-pokunnundo',
      manglish: 'chetta, pokunnundo',
      meaning: 'chetta, are you going?',
      kind: 'sentence',
      acceptedInputs: ['chetta pokunundo'],
      notes: [
        'chetta gets a comma: you are addressing him, not naming him.',
        'No script here: the written form spells a long a that is short in speech.',
      ],
      segments: [
        { token: 'chetta,', gloss: 'chetta (addressing him)' },
        { token: 'pokunnundo', gloss: 'are you going?' },
      ],
      audio: { slow: 'chetta-pokunnundo.slow', medium: 'chetta-pokunnundo.medium', normal: 'chetta-pokunnundo.normal' },
      tags: ['level:2'],
    },
    {
      id: 'nee-varuva',
      manglish: 'nee varunnundo',
      script: 'നീ വരുന്നുണ്ടോ',
      meaning: 'are you coming? (casual)',
      kind: 'sentence',
      acceptedInputs: ['nee varunundo', 'ni varunundo'],
      notes: ['A bare second-person -uva reads like a command, so questions use varunnundo.'],
      segments: [
        { token: 'nee', gloss: 'you (casual)' },
        { token: 'varunnundo', gloss: 'is coming?' },
      ],
      audio: { slow: 'nee-varuva.slow', medium: 'nee-varuva.medium', normal: 'nee-varuva.normal' },
      tags: ['level:2'],
    },
    {
      id: 'ningal-varuva',
      manglish: 'ningaḷ varunnundo',
      script: 'നിങ്ങൾ വരുന്നുണ്ടോ',
      meaning: 'are you coming? (polite)',
      kind: 'sentence',
      acceptedInputs: ['ningal varunundo'],
      segments: [
        { token: 'ningaḷ', gloss: 'you (polite)' },
        { token: 'varunnundo', gloss: 'is coming?' },
      ],
      audio: { slow: 'ningal-varuva.slow', medium: 'ningal-varuva.medium', normal: 'ningal-varuva.normal' },
      tags: ['level:2'],
    },
    {
      id: 'thaankal-varuva',
      manglish: 'thaangkaḷ varunnundo',
      script: 'താങ്കൾ വരുന്നുണ്ടോ',
      meaning: 'are you coming? (formal)',
      kind: 'sentence',
      acceptedInputs: ['thaankal varunundo'],
      segments: [
        { token: 'thaangkaḷ', gloss: 'you (formal)' },
        { token: 'varunnundo', gloss: 'is coming?' },
      ],
      audio: { slow: 'thaankal-varuva.slow', medium: 'thaankal-varuva.medium', normal: 'thaankal-varuva.normal' },
      tags: ['level:2'],
    },
    {
      id: 'thaankal-pokuva',
      manglish: 'thaangkaḷ pokunnundo',
      script: 'താങ്കൾ പോകുന്നുണ്ടോ',
      meaning: 'are you going? (formal)',
      kind: 'sentence',
      acceptedInputs: ['thaankal pokunundo'],
      segments: [
        { token: 'thaangkaḷ', gloss: 'you (formal)' },
        { token: 'pokunnundo', gloss: 'is going?' },
      ],
      audio: { slow: 'thaankal-pokuva.slow', medium: 'thaankal-pokuva.medium', normal: 'thaankal-pokuva.normal' },
      tags: ['level:2'],
    },
    {
      id: 'addheham-varuva',
      manglish: 'addheham ingott varunnundo',
      script: 'അദ്ദേഹം ഇങ്ങോട്ട് വരുന്നുണ്ടോ',
      meaning: 'is he coming here? (respectful)',
      kind: 'sentence',
      acceptedInputs: ['addheham ingott varunundo'],
      segments: [
        { token: 'addheham', gloss: 'he (respectful)' },
        { token: 'ingott', gloss: 'here (toward me)' },
        { token: 'varunnundo', gloss: 'is coming?' },
      ],
      audio: { slow: 'addheham-varuva.slow', medium: 'addheham-varuva.medium', normal: 'addheham-varuva.normal' },
      tags: ['level:2'],
    },
    {
      id: 'avar-varuva',
      manglish: 'avar varunnundo',
      script: 'അവർ വരുന്നുണ്ടോ',
      meaning: 'are they coming? (also polite he or she)',
      kind: 'sentence',
      acceptedInputs: ['avar varunundo'],
      segments: [
        { token: 'avar', gloss: 'they (also polite he or she)' },
        { token: 'varunnundo', gloss: 'is coming?' },
      ],
      audio: { slow: 'avar-varuva.slow', medium: 'avar-varuva.medium', normal: 'avar-varuva.normal' },
      tags: ['level:2'],
    },
  ],
  pairs: [],
  drills: [
    { kind: 'multipleChoice', itemId: 'chetta', distractors: ['nee-varuva', 'avar-varuva', 'addheham-varuva'] },
    { kind: 'multipleChoice', itemId: 'chetta-pokunnundo', distractors: ['nee-varuva', 'avar-varuva', 'addheham-varuva'] },
    { kind: 'multipleChoice', itemId: 'addheham-varuva', distractors: ['nee-varuva', 'avar-varuva', 'ningal-varuva'] },
    { kind: 'multipleChoice', itemId: 'avar-varuva', distractors: ['addheham-varuva', 'ningal-varuva', 'thaankal-varuva'] },
    {
      kind: 'sentenceBuilder',
      sentenceId: 'chetta-pokunnundo',
      bank: ['chetta,', 'pokunnundo'],
      acceptedInputs: ['chetta pokunundo'],
    },
    {
      kind: 'sentenceBuilder',
      sentenceId: 'nee-varuva',
      bank: ['nee', 'varunnundo'],
      acceptedInputs: ['nee varunundo', 'ni varunundo'],
    },
    {
      kind: 'sentenceBuilder',
      sentenceId: 'ningal-varuva',
      bank: ['ningaḷ', 'varunnundo'],
      acceptedInputs: ['ningal varunundo'],
    },
    {
      kind: 'sentenceBuilder',
      sentenceId: 'thaankal-varuva',
      bank: ['thaangkaḷ', 'varunnundo'],
      acceptedInputs: ['thaankal varunundo'],
    },
    {
      kind: 'sentenceBuilder',
      sentenceId: 'thaankal-pokuva',
      bank: ['thaangkaḷ', 'pokunnundo'],
      acceptedInputs: ['thaankal pokunundo'],
    },
    { kind: 'typing', itemId: 'chetta', acceptedInputs: ['chetta'] },
    { kind: 'typing', itemId: 'nee-varuva', acceptedInputs: ['nee varunundo'] },
  ],
}
