/**
 * Typed content format for Learn Malayalam (PLAN.md §12, refined).
 *
 * Item IDs are immutable. `contentRevision` reconciliation (PLAN.md §11) keys
 * off them, so never rename an id once a lesson ships.
 *
 * Romanization rules for `manglish` live in PLAN.md §9 and are enforced by
 * `npm run content:check`; the `dictionary.ts` module is the native-speaker
 * sign-off record (PLAN.md §13).
 */

/** Audio tiers. Every item has slow/medium/normal; sound items add focus clips. */
export type Tier = 'slow' | 'medium' | 'normal' | 'focus'

export type ItemKind = 'sound' | 'word' | 'phrase' | 'sentence' | 'expression'

export type Pos =
  | 'noun'
  | 'verb'
  | 'pronoun'
  | 'particle'
  | 'suffix'
  | 'adjective'
  | 'adverb'
  | 'number'
  | 'other'

/**
 * `colloquial`: the script field spells the form Malayalis actually write
 * informally (PLAN.md §9 rule 6). `written`: no natural colloquial spelling
 * exists, so the standard written form is shown with a "written form" badge.
 */
export type ScriptForm = 'colloquial' | 'written'

/** Sound-teaching items: SVG tongue diagram + brief cue, never text-only. */
export interface Articulation {
  /** File name inside src/content/articulations/ */
  diagram: string
  /** Brief coaching cue shown under the diagram. */
  tip: string
}

/**
 * Clip references into the lesson's audio sprite. Each ref must be
 * `<itemId>.<tier>`; real offsets are generated by `npm run audio:gen` into
 * audio-manifest.json (gitignored). The committed placeholder
 * `audio-placeholder.json` lists the required clips until audio is generated.
 */
export interface ItemAudio {
  slow: string
  medium: string
  normal: string
  /** Segment-level sound-focus clips (required for sound items). */
  focus?: string[]
}

export interface Item {
  id: string
  /** Strict display romanization per PLAN.md §9. */
  manglish: string
  /** Malayalam script, colloquial spelling (PLAN.md §9 rule 6). */
  script?: string
  scriptForm?: ScriptForm
  /** English gloss. */
  meaning: string
  kind: ItemKind
  pos?: Pos
  /** Illustration asset under public/images/ (required for concrete nouns/verbs). */
  image?: string
  articulation?: Articulation
  audio: ItemAudio
  /** Forgiving ASCII answers for typing drills (diacritic-folded, case-insensitive). */
  acceptedInputs?: string[]
  /** Formal-form notes, politeness, usage. */
  notes?: string[]
  tags: string[]
}

export type Segment = 'zh' | 'coronal' | 'geminate' | 'vowelLength'

/**
 * A minimal-pair discrimination item. `aClip`/`bClip` are `<itemId>.<tier>`
 * refs into the same lesson's sprite; both items must live in that lesson.
 */
export interface MinimalPair {
  id: string
  aItemId: string
  bItemId: string
  segment: Segment
  aClip: string
  bClip: string
}

export type DrillSpec =
  | { kind: 'anticipation'; itemId: string; tier: 'slow' | 'normal' }
  | { kind: 'multipleChoice'; itemId: string; distractors: string[] }
  | { kind: 'imageToWord' | 'wordToImage'; itemId: string; distractors: string[] }
  | { kind: 'minimalPair'; pairId: string }
  | { kind: 'speakAndCompare'; itemId: string }
  | { kind: 'typing'; itemId: string; acceptedInputs?: string[] }
  | { kind: 'sentenceBuilder'; sentenceId: string; bank: string[]; acceptedInputs?: string[] }
  | { kind: 'dialogueRolePlay'; dialogueId: string }

export interface Dialogue {
  id: string
  lines: { role: 'learner' | 'model'; itemId: string }[]
}

export interface Lesson {
  id: string
  levelId: string
  unitId: string
  title: string
  items: Item[]
  pairs: MinimalPair[]
  drills: DrillSpec[]
  /** Number of injected review items from 3-5 lessons back (0 in Unit 1). */
  reviewSlots: number
  /** Sprite file under public/; clip offsets live in the audio manifest. */
  sprite: { file: string }
}

export interface TestSpec {
  itemCount: 20 | 25
  passPct: 0.8
  sections: ['recognition', 'production', 'pronunciation']
  retake: 'unlimited-after-failed-review'
}

export interface Level {
  id: string
  name: string
  canDo: string[]
  lessons: Lesson[]
  test: TestSpec
}

/** License record per image asset (PLAN.md §11 allowlist). */
export interface ImageLicense {
  image: string
  source: string
  author: string
  license: 'CC0' | 'PD' | 'CC BY' | 'CC BY-SA'
  url?: string
}
