import type { Lesson } from '../types';

/**
 * Level 2 Unit 1 Lesson 2 — the copula (PLAN.md §5): aanu / aa / aano
 * say what something is, and athe, alla, illa answer yes and no.
 */
export const l2u1l2: Lesson = {
  id: 'l2u1l2',
  levelId: 'l2',
  unitId: 'l2u1',
  title: 'X is Y',
  comprehensionOnly: false,
  items: [
    {
      id: 'athu',
      manglish: 'athu',
      script: 'അത്',
      meaning: 'that (thing)',
      kind: 'word',
      audio: {
        slow: 'l2u1l2_athu_slow',
        medium: 'l2u1l2_athu_medium',
        normal: 'l2u1l2_athu_normal',
      },
      acceptedInputs: ['athu'],
      notes: ['The everyday "that" — it carries most of the example sentences in this lesson.'],
      tags: [],
    },
    {
      id: 'aanu',
      manglish: 'aanu',
      script: 'ആണ്',
      meaning: 'is',
      kind: 'word',
      audio: {
        slow: 'l2u1l2_aanu_slow',
        medium: 'l2u1l2_aanu_medium',
        normal: 'l2u1l2_aanu_normal',
      },
      acceptedInputs: ['aanu'],
      notes: ['The linking word: avan ready aanu, he is ready.'],
      tags: [],
    },
    {
      id: 'aa',
      manglish: 'aa',
      script: 'ആ',
      meaning: 'is (casual)',
      kind: 'word',
      audio: {
        slow: 'l2u1l2_aa_slow',
        medium: 'l2u1l2_aa_medium',
        normal: 'l2u1l2_aa_normal',
      },
      acceptedInputs: ['aa'],
      notes: ['The everyday short form of aanu: njan ready aa.'],
      tags: [],
    },
    {
      id: 'aano',
      manglish: 'aano',
      script: 'ആണോ',
      meaning: 'is it?',
      kind: 'word',
      audio: {
        slow: 'l2u1l2_aano_slow',
        medium: 'l2u1l2_aano_medium',
        normal: 'l2u1l2_aano_normal',
      },
      acceptedInputs: ['aano'],
      notes: ['Turns the statement into a question: ready aano?'],
      tags: [],
    },
    {
      id: 'athe',
      manglish: 'athe',
      script: 'അതെ',
      meaning: 'yes',
      kind: 'word',
      audio: {
        slow: 'l2u1l2_athe_slow',
        medium: 'l2u1l2_athe_medium',
        normal: 'l2u1l2_athe_normal',
      },
      acceptedInputs: ['athe'],
      notes: ['Yes to a question that used aanu: athe, ready aa.'],
      tags: [],
    },
    {
      id: 'alla',
      manglish: 'alla',
      script: 'അല്ല',
      meaning: 'no; not that',
      kind: 'word',
      audio: {
        slow: 'l2u1l2_alla_slow',
        medium: 'l2u1l2_alla_medium',
        normal: 'l2u1l2_alla_normal',
        focus: ['l2u1l2_alla_focus'],
      },
      acceptedInputs: ['alla'],
      articulation: {
        cue: 'Hold the doubled ll.',
      },
      notes: ['No to a statement: athu alla, not that one.'],
      tags: ['sound:geminate'],
    },
    {
      id: 'illa',
      manglish: 'illa',
      script: 'ഇല്ല',
      meaning: 'no; none',
      kind: 'word',
      audio: {
        slow: 'l2u1l2_illa_slow',
        medium: 'l2u1l2_illa_medium',
        normal: 'l2u1l2_illa_normal',
        focus: ['l2u1l2_illa_focus'],
      },
      acceptedInputs: ['illa'],
      articulation: {
        cue: 'Hold the doubled ll.',
      },
      notes: ['No to having or existing: chaaya illa, no tea.'],
      tags: ['sound:geminate'],
    },
    {
      id: 'njan-ready-aa',
      manglish: 'njan ready aa',
      script: 'ഞാൻ റെഡി ആ',
      meaning: 'I am ready',
      kind: 'sentence',
      audio: {
        slow: 'l2u1l2_njan-ready-aa_slow',
        medium: 'l2u1l2_njan-ready-aa_medium',
        normal: 'l2u1l2_njan-ready-aa_normal',
      },
      sentence: {
        bank: ['njan', 'ready', 'aa', 'avan'],
        orders: ['njan ready aa'],
        parts: [
          { word: 'njan', meaning: 'I' },
          { word: 'ready', meaning: 'ready' },
          { word: 'aa', meaning: 'am, is (casual)' },
        ],
      },
      notes: ['English words slot straight in: ready stays ready.'],
      tags: [],
    },
    {
      id: 'avan-ready-aanu',
      manglish: 'avan ready aanu',
      script: 'അവൻ റെഡി ആണ്',
      meaning: 'he is ready',
      kind: 'sentence',
      audio: {
        slow: 'l2u1l2_avan-ready-aanu_slow',
        medium: 'l2u1l2_avan-ready-aanu_medium',
        normal: 'l2u1l2_avan-ready-aanu_normal',
      },
      sentence: {
        bank: ['avan', 'ready', 'aanu', 'njan'],
        orders: ['avan ready aanu'],
        parts: [
          { word: 'avan', meaning: 'he' },
          { word: 'ready', meaning: 'ready' },
          { word: 'aanu', meaning: 'is' },
        ],
      },
      notes: ['The fuller form: aanu instead of aa.'],
      tags: [],
    },
    {
      id: 'ningal-ready-aano',
      manglish: 'ningaḷ ready aano',
      script: 'നിങ്ങൾ റെഡി ആണോ',
      meaning: 'are you ready?',
      kind: 'sentence',
      audio: {
        slow: 'l2u1l2_ningal-ready-aano_slow',
        medium: 'l2u1l2_ningal-ready-aano_medium',
        normal: 'l2u1l2_ningal-ready-aano_normal',
      },
      sentence: {
        bank: ['ningaḷ', 'ready', 'aano', 'athe'],
        orders: ['ningaḷ ready aano'],
        parts: [
          { word: 'ningaḷ', meaning: 'you' },
          { word: 'ready', meaning: 'ready' },
          { word: 'aano', meaning: 'is it?' },
        ],
      },
      notes: ['Aano on the end turns the statement into the question.'],
      tags: [],
    },
    {
      id: 'athu-alla',
      manglish: 'athu alla',
      script: 'അത് അല്ല',
      meaning: 'not that one',
      kind: 'sentence',
      audio: {
        slow: 'l2u1l2_athu-alla_slow',
        medium: 'l2u1l2_athu-alla_medium',
        normal: 'l2u1l2_athu-alla_normal',
      },
      sentence: {
        bank: ['athu', 'alla', 'athe'],
        orders: ['athu alla'],
        parts: [
          { word: 'athu', meaning: 'that' },
          { word: 'alla', meaning: 'not that, no' },
        ],
      },
      notes: ['The polite way to correct a wrong guess.'],
      tags: [],
    },
    {
      id: 'athe-njan-ready-aa',
      manglish: 'athe njan ready aa',
      script: 'അതെ ഞാൻ റെഡി ആ',
      meaning: 'yes, I am ready',
      kind: 'sentence',
      audio: {
        slow: 'l2u1l2_athe-njan-ready-aa_slow',
        medium: 'l2u1l2_athe-njan-ready-aa_medium',
        normal: 'l2u1l2_athe-njan-ready-aa_normal',
      },
      sentence: {
        bank: ['athe', 'njan', 'ready', 'aa', 'aano'],
        orders: ['athe njan ready aa'],
        parts: [
          { word: 'athe', meaning: 'yes' },
          { word: 'njan', meaning: 'I' },
          { word: 'ready', meaning: 'ready' },
          { word: 'aa', meaning: 'is (casual)' },
        ],
      },
      notes: ['Athe answers aano and aa questions; every word here is glossed below.'],
      tags: [],
    },
    {
      id: 'coffee-illa',
      manglish: 'coffee illa',
      script: 'കോഫി ഇല്ല',
      meaning: "there's no coffee",
      kind: 'sentence',
      audio: {
        slow: 'l2u1l2_coffee-illa_slow',
        medium: 'l2u1l2_coffee-illa_medium',
        normal: 'l2u1l2_coffee-illa_normal',
      },
      sentence: {
        bank: ['coffee', 'illa', 'athe'],
        orders: ['coffee illa'],
        parts: [
          { word: 'coffee', meaning: 'coffee' },
          { word: 'illa', meaning: 'no; none' },
        ],
      },
      notes: ['Coffee is English here — new slots in beginner sentences use English until the Malayalam word is taught.'],
      tags: [],
    },
  ],
  minimalPairs: [],
  drills: [
    { kind: 'multipleChoice', itemId: 'athu', distractors: ['is', 'yes', 'no; none'] },
    { kind: 'multipleChoice', itemId: 'aanu', distractors: ['yes', 'no; none', 'is it?'] },
    { kind: 'multipleChoice', itemId: 'aa', distractors: ['no; not that', 'yes', 'is it?'] },
    { kind: 'multipleChoice', itemId: 'aano', distractors: ['is', 'no; none', 'yes'] },
    { kind: 'multipleChoice', itemId: 'athe', distractors: ['no; not that', 'is (casual)', 'is it?'] },
    { kind: 'multipleChoice', itemId: 'alla', distractors: ['yes', 'is', 'no; none'] },
    { kind: 'multipleChoice', itemId: 'illa', distractors: ['no; not that', 'is (casual)', 'yes'] },
    { kind: 'sentenceBuilder', itemId: 'njan-ready-aa', mode: 'bank' },
    { kind: 'sentenceBuilder', itemId: 'avan-ready-aanu', mode: 'bank' },
    { kind: 'sentenceBuilder', itemId: 'ningal-ready-aano', mode: 'bank' },
    { kind: 'sentenceBuilder', itemId: 'athu-alla', mode: 'bank' },
    { kind: 'sentenceBuilder', itemId: 'athe-njan-ready-aa', mode: 'bank' },
    { kind: 'sentenceBuilder', itemId: 'coffee-illa', mode: 'bank' },
  ],
  reviewSlots: 0,
  spriteId: 'l2u1l2',
};
