import type { Lesson } from '../types';

/**
 * Level 2 Unit 1 Lesson 1 — the casual present tense (PLAN.md §5).
 * The -uva chunk is the present continuous ("am drinking"); the
 * habitual ("I drink") is the -um form, taught here as the contrast.
 */
export const l2u1l1: Lesson = {
  id: 'l2u1l1',
  levelId: 'l2',
  unitId: 'l2u1',
  title: 'The -uva pattern',
  comprehensionOnly: false,
  items: [
    {
      id: 'kudikkuva',
      manglish: 'kudikkuva',
      script: 'കുടിക്കുവാ',
      meaning: 'drinking',
      kind: 'word',
      audio: {
        slow: 'l2u1l1_kudikkuva_slow',
        medium: 'l2u1l1_kudikkuva_medium',
        normal: 'l2u1l1_kudikkuva_normal',
        focus: ['l2u1l1_kudikkuva_focus'],
      },
      acceptedInputs: ['kudikkuva'],
      articulation: {
        cue: 'Hold the doubled kk in the middle.',
      },
      notes: ['The -uva form is the present continuous: "am drinking". The habitual is kudikkum.'],
      tags: ['sound:geminate'],
    },
    {
      id: 'varuva',
      manglish: 'varuva',
      script: 'വരുവാ',
      meaning: 'coming',
      kind: 'word',
      audio: {
        slow: 'l2u1l1_varuva_slow',
        medium: 'l2u1l1_varuva_medium',
        normal: 'l2u1l1_varuva_normal',
      },
      acceptedInputs: ['varuva'],
      notes: ['Present continuous: "am coming".', 'Its natural sentence: njan angott varuva, I am coming there.'],
      tags: [],
    },
    {
      id: 'pokuva',
      manglish: 'pokuva',
      script: 'പോകുവാ',
      meaning: 'going',
      kind: 'word',
      audio: {
        slow: 'l2u1l1_pokuva_slow',
        medium: 'l2u1l1_pokuva_medium',
        normal: 'l2u1l1_pokuva_normal',
      },
      acceptedInputs: ['pokuva'],
      notes: ['Present continuous: "am going".'],
      tags: [],
    },
    {
      id: 'cheyyuva',
      manglish: 'cheyyuva',
      script: 'ചെയ്യുവാ',
      meaning: 'doing',
      kind: 'word',
      audio: {
        slow: 'l2u1l1_cheyyuva_slow',
        medium: 'l2u1l1_cheyyuva_medium',
        normal: 'l2u1l1_cheyyuva_normal',
      },
      acceptedInputs: ['cheyyuva'],
      notes: ['Present continuous: "am doing".'],
      tags: [],
    },
    {
      id: 'parayuva',
      manglish: 'parayuva',
      script: 'പറയുവാ',
      meaning: 'saying',
      kind: 'word',
      audio: {
        slow: 'l2u1l1_parayuva_slow',
        medium: 'l2u1l1_parayuva_medium',
        normal: 'l2u1l1_parayuva_normal',
      },
      acceptedInputs: ['parayuva'],
      notes: ['Present continuous: "am saying".'],
      tags: [],
    },
    {
      id: 'kazhikkuva',
      manglish: 'kazhikkuva',
      script: 'കഴിക്കുവാ',
      meaning: 'eating',
      kind: 'word',
      audio: {
        slow: 'l2u1l1_kazhikkuva_slow',
        medium: 'l2u1l1_kazhikkuva_medium',
        normal: 'l2u1l1_kazhikkuva_normal',
      },
      acceptedInputs: ['kazhikkuva'],
      notes: ['Present continuous: "am eating".'],
      tags: [],
    },
    {
      id: 'irikkuva',
      manglish: 'irikkuva',
      script: 'ഇരിക്കുവാ',
      meaning: 'sitting',
      kind: 'word',
      audio: {
        slow: 'l2u1l1_irikkuva_slow',
        medium: 'l2u1l1_irikkuva_medium',
        normal: 'l2u1l1_irikkuva_normal',
        focus: ['l2u1l1_irikkuva_focus'],
      },
      acceptedInputs: ['irikkuva'],
      articulation: {
        cue: 'Hold the doubled kk in the middle.',
      },
      notes: ['Present continuous: "am sitting".'],
      tags: ['sound:geminate'],
    },
    {
      id: 'vaanguva',
      manglish: 'vaanguva',
      script: 'വാങ്ങുവാ',
      meaning: 'buying',
      kind: 'word',
      audio: {
        slow: 'l2u1l1_vaanguva_slow',
        medium: 'l2u1l1_vaanguva_medium',
        normal: 'l2u1l1_vaanguva_normal',
      },
      acceptedInputs: ['vaanguva'],
      notes: ['Present continuous: "am buying".'],
      tags: [],
    },
    {
      id: 'iranguva',
      manglish: 'iranguva',
      script: 'ഇറങ്ങുവാ',
      meaning: 'setting off; leaving',
      kind: 'word',
      audio: {
        slow: 'l2u1l1_iranguva_slow',
        medium: 'l2u1l1_iranguva_medium',
        normal: 'l2u1l1_iranguva_normal',
      },
      acceptedInputs: ['iranguva'],
      notes: ['The leaving word: stepping out the door, setting off.'],
      tags: [],
    },
    {
      id: 'chaaya',
      manglish: 'chaaya',
      script: 'ചായ',
      meaning: 'tea',
      kind: 'word',
      audio: {
        slow: 'l2u1l1_chaaya_slow',
        medium: 'l2u1l1_chaaya_medium',
        normal: 'l2u1l1_chaaya_normal',
      },
      acceptedInputs: ['chaaya', 'chaya'],
      notes: ['The everyday drink of Kerala — it turns up in half the example sentences.'],
      tags: [],
    },
    {
      id: 'kudikkum',
      manglish: 'kudikkum',
      script: 'കുടിക്കും',
      meaning: 'drinks (sometimes)',
      kind: 'word',
      audio: {
        slow: 'l2u1l1_kudikkum_slow',
        medium: 'l2u1l1_kudikkum_medium',
        normal: 'l2u1l1_kudikkum_normal',
        focus: ['l2u1l1_kudikkum_focus'],
      },
      acceptedInputs: ['kudikkum'],
      articulation: {
        cue: 'Hold the doubled kk in the middle.',
      },
      notes: ['The habitual -um form: what you drink in general, not right now.', 'The same form is the plain future: will drink.'],
      tags: ['sound:geminate'],
    },
    {
      id: 'njan-chaaya-kudikkuva',
      manglish: 'njan chaaya kudikkuva',
      script: 'ഞാൻ ചായ കുടിക്കുവാ',
      meaning: 'I am drinking tea',
      kind: 'sentence',
      audio: {
        slow: 'l2u1l1_njan-chaaya-kudikkuva_slow',
        medium: 'l2u1l1_njan-chaaya-kudikkuva_medium',
        normal: 'l2u1l1_njan-chaaya-kudikkuva_normal',
      },
      sentence: {
        bank: ['njan', 'chaaya', 'kudikkuva', 'avan'],
        orders: ['njan chaaya kudikkuva'],
        parts: [
          { word: 'njan', meaning: 'I' },
          { word: 'chaaya', meaning: 'tea' },
          { word: 'kudikkuva', meaning: 'drinking' },
        ],
      },
      notes: ['Right now, in progress. The habitual "I drink tea sometimes" is njan chaaya kudikkum.'],
      tags: [],
    },
    {
      id: 'njan-chaaya-kudikkum',
      manglish: 'njan chaaya kudikkum',
      script: 'ഞാൻ ചായ കുടിക്കും',
      meaning: 'I drink tea sometimes',
      kind: 'sentence',
      audio: {
        slow: 'l2u1l1_njan-chaaya-kudikkum_slow',
        medium: 'l2u1l1_njan-chaaya-kudikkum_medium',
        normal: 'l2u1l1_njan-chaaya-kudikkum_normal',
      },
      sentence: {
        bank: ['njan', 'chaaya', 'kudikkum', 'kudikkuva'],
        orders: ['njan chaaya kudikkum'],
        parts: [
          { word: 'njan', meaning: 'I' },
          { word: 'chaaya', meaning: 'tea' },
          { word: 'kudikkum', meaning: 'drinks (sometimes)' },
        ],
      },
      notes: ['The habitual: what you drink in general, not right now.'],
      tags: [],
    },
    {
      id: 'njan-every-day-chaaya-kudikkum',
      manglish: 'njan every day chaaya kudikkum',
      script: 'ഞാൻ എവരി ഡേ ചായ കുടിക്കും',
      meaning: 'I drink tea every day',
      kind: 'sentence',
      audio: {
        slow: 'l2u1l1_njan-every-day-chaaya-kudikkum_slow',
        medium: 'l2u1l1_njan-every-day-chaaya-kudikkum_medium',
        normal: 'l2u1l1_njan-every-day-chaaya-kudikkum_normal',
      },
      sentence: {
        bank: ['njan', 'every', 'day', 'chaaya', 'kudikkum', 'kudikkuva'],
        orders: ['njan every day chaaya kudikkum'],
        parts: [
          { word: 'njan', meaning: 'I' },
          { word: 'every', meaning: 'every' },
          { word: 'day', meaning: 'day' },
          { word: 'chaaya', meaning: 'tea' },
          { word: 'kudikkum', meaning: 'drinks (sometimes)' },
        ],
      },
      notes: ['Every day is English here — new slots in beginner sentences use English until the Malayalam word is taught.'],
      tags: [],
    },
    {
      id: 'avan-varunnund',
      manglish: 'avan varunnund',
      script: 'അവൻ വരുന്നുണ്ട്',
      meaning: 'he is coming',
      kind: 'sentence',
      audio: {
        slow: 'l2u1l1_avan-varunnund_slow',
        medium: 'l2u1l1_avan-varunnund_medium',
        normal: 'l2u1l1_avan-varunnund_normal',
      },
      sentence: {
        bank: ['avan', 'varunnund', 'njan'],
        orders: ['avan varunnund'],
        parts: [
          { word: 'avan', meaning: 'he' },
          { word: 'varunnund', meaning: 'is coming' },
        ],
      },
      notes: ['The natural statement form: varunnund, not varuva.'],
      tags: [],
    },
  ],
  minimalPairs: [],
  drills: [
    { kind: 'multipleChoice', itemId: 'kudikkuva', distractors: ['coming', 'going', 'doing'] },
    { kind: 'multipleChoice', itemId: 'varuva', distractors: ['drinking', 'going', 'saying'] },
    { kind: 'multipleChoice', itemId: 'pokuva', distractors: ['drinking', 'coming', 'eating'] },
    { kind: 'multipleChoice', itemId: 'cheyyuva', distractors: ['saying', 'sitting', 'buying'] },
    { kind: 'multipleChoice', itemId: 'parayuva', distractors: ['doing', 'eating', 'coming'] },
    { kind: 'multipleChoice', itemId: 'kazhikkuva', distractors: ['drinking', 'sitting', 'buying'] },
    { kind: 'multipleChoice', itemId: 'irikkuva', distractors: ['eating', 'going', 'saying'] },
    { kind: 'multipleChoice', itemId: 'vaanguva', distractors: ['doing', 'coming', 'drinking'] },
    { kind: 'multipleChoice', itemId: 'iranguva', distractors: ['buying', 'sitting', 'going'] },
    { kind: 'multipleChoice', itemId: 'kudikkum', distractors: ['drinking', 'eating', 'saying'] },
    { kind: 'multipleChoice', itemId: 'chaaya', distractors: ['drinking', 'coming', 'going'] },
    { kind: 'sentenceBuilder', itemId: 'njan-chaaya-kudikkuva', mode: 'bank' },
    { kind: 'sentenceBuilder', itemId: 'njan-chaaya-kudikkum', mode: 'bank' },
    { kind: 'sentenceBuilder', itemId: 'njan-every-day-chaaya-kudikkum', mode: 'bank' },
    { kind: 'sentenceBuilder', itemId: 'avan-varunnund', mode: 'bank' },
  ],
  reviewSlots: 0,
  spriteId: 'l2u1l1',
};
