import type { Lesson } from '../types';

/**
 * Level 2 Unit 1 Lesson 1 — the casual present tense (PLAN.md §5).
 * The -uva chunk covers "does" and "is doing" at once; every verb here
 * is usable in a sentence immediately.
 */
export const l2u1l1: Lesson = {
  id: 'l2u1l1',
  levelId: 'l2',
  unitId: 'l2u1',
  title: 'The -uva pattern',
  comprehensionOnly: false,
  items: [
    {
      id: 'kudikkuva',
      manglish: 'kudikkuva',
      script: 'കുടിക്കുവാ',
      meaning: 'drink; drinking',
      kind: 'word',
      audio: {
        slow: 'l2u1l1_kudikkuva_slow',
        medium: 'l2u1l1_kudikkuva_medium',
        normal: 'l2u1l1_kudikkuva_normal',
        focus: ['l2u1l1_kudikkuva_focus'],
      },
      acceptedInputs: ['kudikkuva'],
      articulation: {
        cue: 'Hold the doubled kk in the middle.',
      },
      notes: ['The -uva form covers "drinks" and "is drinking".'],
      tags: ['sound:geminate'],
    },
    {
      id: 'varuva',
      manglish: 'varuva',
      script: 'വരുവാ',
      meaning: 'come; coming',
      kind: 'word',
      audio: {
        slow: 'l2u1l1_varuva_slow',
        medium: 'l2u1l1_varuva_medium',
        normal: 'l2u1l1_varuva_normal',
      },
      acceptedInputs: ['varuva'],
      notes: ['The -uva form covers "comes" and "is coming".'],
      tags: [],
    },
    {
      id: 'pokuva',
      manglish: 'pokuva',
      script: 'പോകുവാ',
      meaning: 'go; going',
      kind: 'word',
      audio: {
        slow: 'l2u1l1_pokuva_slow',
        medium: 'l2u1l1_pokuva_medium',
        normal: 'l2u1l1_pokuva_normal',
      },
      acceptedInputs: ['pokuva'],
      notes: ['The -uva form covers "goes" and "is going".'],
      tags: [],
    },
    {
      id: 'cheyyuva',
      manglish: 'cheyyuva',
      script: 'ചെയ്യുവാ',
      meaning: 'do; doing',
      kind: 'word',
      audio: {
        slow: 'l2u1l1_cheyyuva_slow',
        medium: 'l2u1l1_cheyyuva_medium',
        normal: 'l2u1l1_cheyyuva_normal',
      },
      acceptedInputs: ['cheyyuva'],
      notes: ['The -uva form of cheyyu, to do.'],
      tags: [],
    },
    {
      id: 'parayuva',
      manglish: 'parayuva',
      script: 'പറയുവാ',
      meaning: 'say; will say',
      kind: 'word',
      audio: {
        slow: 'l2u1l1_parayuva_slow',
        medium: 'l2u1l1_parayuva_medium',
        normal: 'l2u1l1_parayuva_normal',
      },
      acceptedInputs: ['parayuva'],
      notes: ['The -uva form of parayu, to say.'],
      tags: [],
    },
    {
      id: 'kazhikkuva',
      manglish: 'kazhikkuva',
      script: 'കഴിക്കുവാ',
      meaning: 'eat; eating',
      kind: 'word',
      audio: {
        slow: 'l2u1l1_kazhikkuva_slow',
        medium: 'l2u1l1_kazhikkuva_medium',
        normal: 'l2u1l1_kazhikkuva_normal',
      },
      acceptedInputs: ['kazhikkuva'],
      notes: ['The -uva form covers "eats" and "is eating".'],
      tags: [],
    },
    {
      id: 'irikkuva',
      manglish: 'irikkuva',
      script: 'ഇരിക്കുവാ',
      meaning: 'sit; sitting',
      kind: 'word',
      audio: {
        slow: 'l2u1l1_irikkuva_slow',
        medium: 'l2u1l1_irikkuva_medium',
        normal: 'l2u1l1_irikkuva_normal',
        focus: ['l2u1l1_irikkuva_focus'],
      },
      acceptedInputs: ['irikkuva'],
      articulation: {
        cue: 'Hold the doubled kk in the middle.',
      },
      notes: ['The -uva form covers "sits" and "is sitting".'],
      tags: ['sound:geminate'],
    },
    {
      id: 'vaanguva',
      manglish: 'vaanguva',
      script: 'വാങ്ങുവാ',
      meaning: 'buy; buying',
      kind: 'word',
      audio: {
        slow: 'l2u1l1_vaanguva_slow',
        medium: 'l2u1l1_vaanguva_medium',
        normal: 'l2u1l1_vaanguva_normal',
      },
      acceptedInputs: ['vaanguva'],
      notes: ['The -uva form covers "buys" and "is buying".'],
      tags: [],
    },
    {
      id: 'njan-chaaya-kudikkuva',
      manglish: 'njan chaaya kudikkuva',
      script: 'ഞാൻ ചായ കുടിക്കുവാ',
      meaning: 'I drink tea',
      kind: 'sentence',
      audio: {
        slow: 'l2u1l1_njan-chaaya-kudikkuva_slow',
        medium: 'l2u1l1_njan-chaaya-kudikkuva_medium',
        normal: 'l2u1l1_njan-chaaya-kudikkuva_normal',
      },
      sentence: {
        bank: ['njan', 'chaaya', 'kudikkuva', 'avan'],
        orders: ['njan chaaya kudikkuva'],
        parts: [
          { word: 'njan', meaning: 'I' },
          { word: 'chaaya', meaning: 'tea' },
          { word: 'kudikkuva', meaning: 'drink, drinking' },
        ],
      },
      notes: ['Subject first, then the rest, then the verb. The -uva form needs no "am".'],
      tags: [],
    },
    {
      id: 'avan-varuva',
      manglish: 'avan varuva',
      script: 'അവൻ വരുവാ',
      meaning: 'he is coming',
      kind: 'sentence',
      audio: {
        slow: 'l2u1l1_avan-varuva_slow',
        medium: 'l2u1l1_avan-varuva_medium',
        normal: 'l2u1l1_avan-varuva_normal',
      },
      sentence: {
        bank: ['avan', 'varuva', 'njan'],
        orders: ['avan varuva'],
        parts: [
          { word: 'avan', meaning: 'he' },
          { word: 'varuva', meaning: 'come, coming' },
        ],
      },
      notes: ['No "is" needed: varuva already carries the tense.'],
      tags: [],
    },
  ],
  minimalPairs: [],
  drills: [
    { kind: 'multipleChoice', itemId: 'kudikkuva', distractors: ['come; coming', 'go; going', 'do; doing'] },
    { kind: 'multipleChoice', itemId: 'varuva', distractors: ['drink; drinking', 'go; going', 'say; will say'] },
    { kind: 'multipleChoice', itemId: 'pokuva', distractors: ['drink; drinking', 'come; coming', 'eat; eating'] },
    { kind: 'multipleChoice', itemId: 'cheyyuva', distractors: ['say; will say', 'sit; sitting', 'buy; buying'] },
    { kind: 'multipleChoice', itemId: 'parayuva', distractors: ['do; doing', 'eat; eating', 'come; coming'] },
    { kind: 'multipleChoice', itemId: 'kazhikkuva', distractors: ['drink; drinking', 'sit; sitting', 'buy; buying'] },
    { kind: 'multipleChoice', itemId: 'irikkuva', distractors: ['eat; eating', 'go; going', 'say; will say'] },
    { kind: 'multipleChoice', itemId: 'vaanguva', distractors: ['do; doing', 'come; coming', 'drink; drinking'] },
    { kind: 'sentenceBuilder', itemId: 'njan-chaaya-kudikkuva', mode: 'bank' },
    { kind: 'sentenceBuilder', itemId: 'avan-varuva', mode: 'bank' },
  ],
  reviewSlots: 0,
  spriteId: 'l2u1l1',
};
