import type { Lesson } from '../types';

/**
 * Level 2 Unit 1 Lesson 3 — questions and tags (PLAN.md §5): the -o
 * particle turns statements into questions (varunno?, veno?), pokatte
 * and varatte ask for permission, and kettiyo tags a shared context.
 */
export const l2u1l3: Lesson = {
  id: 'l2u1l3',
  levelId: 'l2',
  unitId: 'l2u1',
  title: 'Questions and tags',
  comprehensionOnly: false,
  items: [
    {
      id: 'venam',
      manglish: 'venam',
      script: 'വേണം',
      meaning: 'want; need',
      kind: 'word',
      audio: {
        slow: 'l2u1l3_venam_slow',
        medium: 'l2u1l3_venam_medium',
        normal: 'l2u1l3_venam_normal',
      },
      acceptedInputs: ['venam'],
      notes: ['The plain want: njan chaaya venam.'],
      tags: [],
    },
    {
      id: 'niyyo',
      manglish: 'niyyo?',
      script: 'നിയ്യോ',
      meaning: 'you too?',
      kind: 'expression',
      audio: {
        slow: 'l2u1l3_niyyo_slow',
        medium: 'l2u1l3_niyyo_medium',
        normal: 'l2u1l3_niyyo_normal',
      },
      acceptedInputs: ['niyyo?', 'niyyo'],
      notes: ['The -o particle on nii: "you too?"'],
      tags: [],
    },
    {
      id: 'kettiyo',
      manglish: 'kettiyo?',
      script: 'കേട്ടിയോ',
      meaning: 'you know? right?',
      kind: 'expression',
      audio: {
        slow: 'l2u1l3_kettiyo_slow',
        medium: 'l2u1l3_kettiyo_medium',
        normal: 'l2u1l3_kettiyo_normal',
        focus: ['l2u1l3_kettiyo_focus'],
      },
      acceptedInputs: ['kettiyo?', 'kettiyo'],
      articulation: {
        cue: 'Hold the doubled tt.',
      },
      notes: ['Tag for shared context, like "you heard about it, right?"'],
      tags: ['sound:geminate'],
    },
    {
      id: 'varunno',
      manglish: 'varunno?',
      script: 'വരുന്നോ',
      meaning: 'coming?',
      kind: 'expression',
      audio: {
        slow: 'l2u1l3_varunno_slow',
        medium: 'l2u1l3_varunno_medium',
        normal: 'l2u1l3_varunno_normal',
        focus: ['l2u1l3_varunno_focus'],
      },
      acceptedInputs: ['varunno?', 'varunno'],
      articulation: {
        cue: 'Hold the doubled nn.',
      },
      notes: ['The -o question on varunnu: "coming?"'],
      tags: ['sound:geminate'],
    },
    {
      id: 'pokatte',
      manglish: 'pokatte?',
      script: 'പോകട്ടെ',
      meaning: 'may I go?',
      kind: 'expression',
      audio: {
        slow: 'l2u1l3_pokatte_slow',
        medium: 'l2u1l3_pokatte_medium',
        normal: 'l2u1l3_pokatte_normal',
        focus: ['l2u1l3_pokatte_focus'],
      },
      acceptedInputs: ['pokatte?', 'pokatte'],
      articulation: {
        cue: 'Hold the doubled tt.',
      },
      notes: ['Asks permission to leave: njan pokatte?'],
      tags: ['sound:geminate'],
    },
    {
      id: 'chaaya-veno',
      manglish: 'chaaya veno?',
      script: 'ചായ വേണോ',
      meaning: 'do you want tea?',
      kind: 'sentence',
      audio: {
        slow: 'l2u1l3_chaaya-veno_slow',
        medium: 'l2u1l3_chaaya-veno_medium',
        normal: 'l2u1l3_chaaya-veno_normal',
      },
      sentence: {
        bank: ['chaaya', 'veno?', 'und'],
        orders: ['chaaya veno?'],
        parts: [
          { word: 'chaaya', meaning: 'tea' },
          { word: 'veno?', meaning: 'want?, do you want?' },
        ],
      },
      notes: ['The standard offer: venam with the -o question particle.'],
      tags: [],
    },
    {
      id: 'njan-pokatte',
      manglish: 'njan pokatte?',
      script: 'ഞാൻ പോകട്ടെ',
      meaning: 'may I go?',
      kind: 'sentence',
      audio: {
        slow: 'l2u1l3_njan-pokatte_slow',
        medium: 'l2u1l3_njan-pokatte_medium',
        normal: 'l2u1l3_njan-pokatte_normal',
      },
      sentence: {
        bank: ['njan', 'pokatte?', 'varuva'],
        orders: ['njan pokatte?'],
        parts: [
          { word: 'njan', meaning: 'I' },
          { word: 'pokatte?', meaning: 'may I go?' },
        ],
      },
      notes: ['Said when leaving a place: njan pokatte?'],
      tags: [],
    },
    {
      id: 'ningal-varunno',
      manglish: 'ningaḷ varunno?',
      script: 'നിങ്ങൾ വരുന്നോ',
      meaning: 'are you coming?',
      kind: 'sentence',
      audio: {
        slow: 'l2u1l3_ningal-varunno_slow',
        medium: 'l2u1l3_ningal-varunno_medium',
        normal: 'l2u1l3_ningal-varunno_normal',
      },
      sentence: {
        bank: ['ningaḷ', 'varunno?', 'pokatte?'],
        orders: ['ningaḷ varunno?'],
        parts: [
          { word: 'ningaḷ', meaning: 'you' },
          { word: 'varunno?', meaning: 'coming?' },
        ],
      },
      notes: ['The everyday invite: ningaḷ varunno?'],
      tags: [],
    },
    {
      id: 'njan-varatte',
      manglish: 'njan varatte?',
      script: 'ഞാൻ വരട്ടെ',
      meaning: 'shall I come?',
      kind: 'sentence',
      audio: {
        slow: 'l2u1l3_njan-varatte_slow',
        medium: 'l2u1l3_njan-varatte_medium',
        normal: 'l2u1l3_njan-varatte_normal',
      },
      sentence: {
        bank: ['njan', 'varatte?', 'veno?'],
        orders: ['njan varatte?'],
        parts: [
          { word: 'njan', meaning: 'I' },
          { word: 'varatte?', meaning: 'shall I come?' },
        ],
      },
      notes: ['Offers to come over: njan varatte?'],
      tags: [],
    },
    {
      id: 'athu-sheri-alle',
      manglish: 'athu sheri alle?',
      script: 'അത് ശെരി അല്ലേ',
      meaning: "that's okay, right?",
      kind: 'sentence',
      audio: {
        slow: 'l2u1l3_athu-sheri-alle_slow',
        medium: 'l2u1l3_athu-sheri-alle_medium',
        normal: 'l2u1l3_athu-sheri-alle_normal',
      },
      sentence: {
        bank: ['athu', 'sheri', 'alle?', 'alla'],
        orders: ['athu sheri alle?'],
        parts: [
          { word: 'athu', meaning: 'that' },
          { word: 'sheri', meaning: 'okay' },
          { word: 'alle?', meaning: 'right?' },
        ],
      },
      notes: ['The tag question on a statement you are sure of.'],
      tags: [],
    },
  ],
  minimalPairs: [],
  drills: [
    { kind: 'multipleChoice', itemId: 'venam', distractors: ['you too?', 'coming?', 'may I go?'] },
    { kind: 'multipleChoice', itemId: 'niyyo', distractors: ['want; need', 'you know? right?', 'coming?'] },
    { kind: 'multipleChoice', itemId: 'kettiyo', distractors: ['may I go?', 'want; need', 'you too?'] },
    { kind: 'multipleChoice', itemId: 'varunno', distractors: ['want; need', 'you know? right?', 'may I go?'] },
    { kind: 'multipleChoice', itemId: 'pokatte', distractors: ['coming?', 'you too?', 'want; need'] },
    { kind: 'sentenceBuilder', itemId: 'chaaya-veno', mode: 'bank' },
    { kind: 'sentenceBuilder', itemId: 'njan-pokatte', mode: 'bank' },
    { kind: 'sentenceBuilder', itemId: 'ningal-varunno', mode: 'bank' },
    { kind: 'sentenceBuilder', itemId: 'njan-varatte', mode: 'bank' },
    { kind: 'sentenceBuilder', itemId: 'athu-sheri-alle', mode: 'bank' },
  ],
  reviewSlots: 0,
  spriteId: 'l2u1l3',
};
