import type { Lesson } from '../types';

/**
 * Level 2 Unit 1 Lesson 3 — questions and tags (PLAN.md §5): the -o
 * particle turns statements into questions (varunnundo?, veno?),
 * pokatte and varatte ask for permission, and ketto tags shared news.
 */
export const l2u1l3: Lesson = {
  id: 'l2u1l3',
  levelId: 'l2',
  unitId: 'l2u1',
  title: 'Questions and tags',
  comprehensionOnly: false,
  items: [
    {
      id: 'venam',
      manglish: 'venam',
      script: 'വേണം',
      meaning: 'want; need',
      kind: 'word',
      audio: {
        slow: 'l2u1l3_venam_slow',
        medium: 'l2u1l3_venam_medium',
        normal: 'l2u1l3_venam_normal',
      },
      acceptedInputs: ['venam'],
      notes: ['Wanting puts the person in the to-me form: enikk chaaya venam, to me tea is wanted.'],
      tags: [],
    },
    {
      id: 'neeyyo',
      manglish: 'neeyo',
      script: 'നീയോ',
      meaning: 'you?',
      kind: 'expression',
      audio: {
        slow: 'l2u1l3_neeyyo_slow',
        medium: 'l2u1l3_neeyyo_medium',
        normal: 'l2u1l3_neeyyo_normal',
      },
      acceptedInputs: ['neeyo', 'neeyyo', 'niyyo'],
      notes: ['The -o particle on nee: "you?" For "you too?" the word is neeyum.'],
      tags: [],
    },
    {
      id: 'neeyyum',
      manglish: 'neeyum',
      script: 'നീയും',
      meaning: 'you too?',
      kind: 'expression',
      audio: {
        slow: 'l2u1l3_neeyyum_slow',
        medium: 'l2u1l3_neeyyum_medium',
        normal: 'l2u1l3_neeyyum_normal',
      },
      acceptedInputs: ['neeyum', 'neeyyum', 'niyyum'],
      notes: ['-um adds "too": neeyum. Contrast with neeyo, plain "you?".'],
      tags: [],
    },
    {
      id: 'ketto',
      manglish: 'ketto',
      script: 'കേട്ടോ',
      meaning: 'did you hear?',
      kind: 'expression',
      audio: {
        slow: 'l2u1l3_ketto_slow',
        medium: 'l2u1l3_ketto_medium',
        normal: 'l2u1l3_ketto_normal',
        focus: ['l2u1l3_ketto_focus'],
      },
      acceptedInputs: ['ketto'],
      articulation: {
        cue: 'Hold the doubled tt.',
      },
      notes: ['The everyday tag on shared news. The fuller form is kettayirunno? (did you hear? — about the past).'],
      tags: ['sound:geminate'],
    },
    {
      id: 'varunundo',
      manglish: 'varunnundo',
      script: 'വരുന്നുണ്ടോ',
      meaning: 'coming?',
      kind: 'expression',
      audio: {
        slow: 'l2u1l3_varunundo_slow',
        medium: 'l2u1l3_varunundo_medium',
        normal: 'l2u1l3_varunundo_normal',
        focus: ['l2u1l3_varunundo_focus'],
      },
      acceptedInputs: ['varunnundo'],
      articulation: {
        cue: 'Hold the doubled nn.',
      },
      notes: ['The colloquial -o question on varunnund: "coming?"'],
      tags: ['sound:geminate'],
    },
    {
      id: 'pokatte',
      manglish: 'pokatte',
      script: 'പോകട്ടെ',
      meaning: 'may I go?',
      kind: 'expression',
      audio: {
        slow: 'l2u1l3_pokatte_slow',
        medium: 'l2u1l3_pokatte_medium',
        normal: 'l2u1l3_pokatte_normal',
        focus: ['l2u1l3_pokatte_focus'],
      },
      acceptedInputs: ['pokatte'],
      articulation: {
        cue: 'Hold the doubled tt.',
      },
      notes: ['Asks permission to leave: njan pokatte?'],
      tags: ['sound:geminate'],
    },
    {
      id: 'chaaya-veno',
      manglish: 'chaaya veno',
      script: 'ചായ വേണോ',
      meaning: 'do you want tea?',
      kind: 'sentence',
      audio: {
        slow: 'l2u1l3_chaaya-veno_slow',
        medium: 'l2u1l3_chaaya-veno_medium',
        normal: 'l2u1l3_chaaya-veno_normal',
      },
      sentence: {
        bank: ['chaaya', 'veno', 'und'],
        orders: ['chaaya veno'],
        parts: [
          { word: 'chaaya', meaning: 'tea' },
          { word: 'veno', meaning: 'want?, do you want?' },
        ],
      },
      notes: [
        'The standard offer: the person asked takes the to-you form, so the full form is ninakk chaaya veno.',
      ],
      tags: [],
    },
    {
      id: 'njan-pokatte',
      manglish: 'njan pokatte',
      script: 'ഞാൻ പോകട്ടെ',
      meaning: 'may I go?',
      kind: 'sentence',
      audio: {
        slow: 'l2u1l3_njan-pokatte_slow',
        medium: 'l2u1l3_njan-pokatte_medium',
        normal: 'l2u1l3_njan-pokatte_normal',
      },
      sentence: {
        bank: ['njan', 'pokatte', 'varuva'],
        orders: ['njan pokatte'],
        parts: [
          { word: 'njan', meaning: 'I' },
          { word: 'pokatte', meaning: 'may I go?' },
        ],
      },
      notes: ['Said when leaving a place: njan pokatte?'],
      tags: [],
    },
    {
      id: 'ningal-varunundo',
      manglish: 'ningaḷ varunnundo',
      script: 'നിങ്ങൾ വരുന്നുണ്ടോ',
      meaning: 'are you coming?',
      kind: 'sentence',
      audio: {
        slow: 'l2u1l3_ningal-varunundo_slow',
        medium: 'l2u1l3_ningal-varunundo_medium',
        normal: 'l2u1l3_ningal-varunundo_normal',
      },
      sentence: {
        bank: ['ningaḷ', 'varunnundo', 'pokatte'],
        orders: ['ningaḷ varunnundo'],
        parts: [
          { word: 'ningaḷ', meaning: 'you' },
          { word: 'varunnundo', meaning: 'coming?' },
        ],
      },
      notes: ['The everyday invite: ningaḷ varunnundo?'],
      tags: [],
    },
    {
      id: 'njan-varatte',
      manglish: 'njan varatte',
      script: 'ഞാൻ വരട്ടെ',
      meaning: 'shall I come?',
      kind: 'sentence',
      audio: {
        slow: 'l2u1l3_njan-varatte_slow',
        medium: 'l2u1l3_njan-varatte_medium',
        normal: 'l2u1l3_njan-varatte_normal',
      },
      sentence: {
        bank: ['njan', 'varatte', 'veno'],
        orders: ['njan varatte'],
        parts: [
          { word: 'njan', meaning: 'I' },
          { word: 'varatte', meaning: 'shall I come?' },
        ],
      },
      notes: ['Offers to come over: njan varatte?'],
      tags: [],
    },
    {
      id: 'athu-sheri-alle',
      manglish: 'athu sheri alle',
      script: 'അത് ശെരി അല്ലേ',
      meaning: "that's correct, right?",
      kind: 'sentence',
      audio: {
        slow: 'l2u1l3_athu-sheri-alle_slow',
        medium: 'l2u1l3_athu-sheri-alle_medium',
        normal: 'l2u1l3_athu-sheri-alle_normal',
      },
      sentence: {
        bank: ['athu', 'sheri', 'alle', 'alla'],
        orders: ['athu sheri alle'],
        parts: [
          { word: 'athu', meaning: 'that' },
          { word: 'sheri', meaning: 'correct, okay' },
          { word: 'alle', meaning: 'right?' },
        ],
      },
      notes: ['The tag question on something you are sure is correct.'],
      tags: [],
    },
  ],
  minimalPairs: [],
  drills: [
    { kind: 'multipleChoice', itemId: 'venam', distractors: ['you?', 'coming?', 'may I go?'] },
    { kind: 'multipleChoice', itemId: 'neeyyo', distractors: ['you too?', 'did you hear?', 'coming?'] },
    { kind: 'multipleChoice', itemId: 'neeyyum', distractors: ['you?', 'want; need', 'may I go?'] },
    { kind: 'multipleChoice', itemId: 'ketto', distractors: ['may I go?', 'want; need', 'you too?'] },
    { kind: 'multipleChoice', itemId: 'varunundo', distractors: ['want; need', 'did you hear?', 'may I go?'] },
    { kind: 'multipleChoice', itemId: 'pokatte', distractors: ['coming?', 'you?', 'want; need'] },
    { kind: 'sentenceBuilder', itemId: 'chaaya-veno', mode: 'bank' },
    { kind: 'sentenceBuilder', itemId: 'njan-pokatte', mode: 'bank' },
    { kind: 'sentenceBuilder', itemId: 'ningal-varunundo', mode: 'bank' },
    { kind: 'sentenceBuilder', itemId: 'njan-varatte', mode: 'bank' },
    { kind: 'sentenceBuilder', itemId: 'athu-sheri-alle', mode: 'bank' },
  ],
  reviewSlots: 0,
  spriteId: 'l2u1l3',
};
