import type { Lesson } from '../types';

/**
 * Level 2 Unit 2 Lesson 1 — the third-person ladder (PLAN.md §5): ayaaḷ
 * and iyaaḷ step up from avan, addheham is the respectful form, and avar
 * covers both "they" and polite he-or-she. The formal second person
 * thaankaḷ closes the ladder started in L1U3L1.
 */
export const l2u2l1: Lesson = {
  id: 'l2u2l1',
  levelId: 'l2',
  unitId: 'l2u2',
  title: 'He, she, politely',
  comprehensionOnly: false,
  items: [
    {
      id: 'ayaal',
      manglish: 'ayaaḷ',
      script: 'അയാൾ',
      meaning: 'he, that man',
      kind: 'word',
      pos: 'pronoun',
      audio: {
        slow: 'l2u2l1_ayaal_slow',
        medium: 'l2u2l1_ayaal_medium',
        normal: 'l2u2l1_ayaal_normal',
      },
      acceptedInputs: ['ayaal'],
      notes: ['A step up from avan: polite enough for anyone you do not know well.'],
      tags: [],
    },
    {
      id: 'iyaal',
      manglish: 'iyaaḷ',
      script: 'ഇയാൾ',
      meaning: 'he, this man',
      kind: 'word',
      pos: 'pronoun',
      audio: {
        slow: 'l2u2l1_iyaal_slow',
        medium: 'l2u2l1_iyaal_medium',
        normal: 'l2u2l1_iyaal_normal',
      },
      acceptedInputs: ['iyaal'],
      notes: ['For the man right here, nearby.'],
      tags: [],
    },
    {
      id: 'addheham',
      manglish: 'addheham',
      script: 'അദ്ദേഹം',
      meaning: 'he (respectful)',
      kind: 'word',
      pos: 'pronoun',
      audio: {
        slow: 'l2u2l1_addheham_slow',
        medium: 'l2u2l1_addheham_medium',
        normal: 'l2u2l1_addheham_normal',
      },
      acceptedInputs: ['addheham', 'addeham'],
      notes: ['The respectful he — for elders, bosses, and people you look up to.'],
      tags: [],
    },
    {
      id: 'avar',
      manglish: 'avar',
      script: 'അവർ',
      meaning: 'they; polite he or she',
      kind: 'word',
      pos: 'pronoun',
      audio: {
        slow: 'l2u2l1_avar_slow',
        medium: 'l2u2l1_avar_medium',
        normal: 'l2u2l1_avar_normal',
      },
      acceptedInputs: ['avar'],
      notes: ['Plural on paper, but the everyday polite he-or-she too.'],
      tags: [],
    },
    {
      id: 'ayaal-varuva',
      manglish: 'ayaaḷ varuva',
      script: 'അയാൾ വരുവാ',
      meaning: 'that man is coming',
      kind: 'sentence',
      audio: {
        slow: 'l2u2l1_ayaal-varuva_slow',
        medium: 'l2u2l1_ayaal-varuva_medium',
        normal: 'l2u2l1_ayaal-varuva_normal',
      },
      sentence: {
        bank: ['ayaaḷ', 'varuva', 'avan', 'iyaaḷ'],
        orders: ['ayaaḷ varuva'],
        parts: [
          { word: 'ayaaḷ', meaning: 'he, that man' },
          { word: 'varuva', meaning: 'coming' },
        ],
      },
      notes: ['Third person, so the plain -uva is fine.'],
      tags: [],
    },
    {
      id: 'iyaal-ready-aanu',
      manglish: 'iyaaḷ ready aanu',
      script: 'ഇയാൾ റെഡി ആണ്',
      meaning: 'this man is ready',
      kind: 'sentence',
      audio: {
        slow: 'l2u2l1_iyaal-ready-aanu_slow',
        medium: 'l2u2l1_iyaal-ready-aanu_medium',
        normal: 'l2u2l1_iyaal-ready-aanu_normal',
      },
      sentence: {
        bank: ['iyaaḷ', 'ready', 'aanu', 'aano'],
        orders: ['iyaaḷ ready aanu'],
        parts: [
          { word: 'iyaaḷ', meaning: 'he, this man' },
          { word: 'ready', meaning: 'ready' },
          { word: 'aanu', meaning: 'is' },
        ],
      },
      notes: ['Ready stays English — the register mixes freely.'],
      tags: [],
    },
    {
      id: 'addheham-varuva',
      manglish: 'addheham varuva',
      script: 'അദ്ദേഹം വരുവാ',
      meaning: 'he (respectful) is coming',
      kind: 'sentence',
      audio: {
        slow: 'l2u2l1_addheham-varuva_slow',
        medium: 'l2u2l1_addheham-varuva_medium',
        normal: 'l2u2l1_addheham-varuva_normal',
      },
      sentence: {
        bank: ['addheham', 'varuva', 'ayaaḷ', 'avar'],
        orders: ['addheham varuva'],
        parts: [
          { word: 'addheham', meaning: 'he (respectful)' },
          { word: 'varuva', meaning: 'coming' },
        ],
      },
      notes: ['Same sentence as avan varuva — the pronoun does the politeness.'],
      tags: [],
    },
    {
      id: 'avar-varuva',
      manglish: 'avar varuva',
      script: 'അവർ വരുവാ',
      meaning: 'they are coming; polite for he or she',
      kind: 'sentence',
      audio: {
        slow: 'l2u2l1_avar-varuva_slow',
        medium: 'l2u2l1_avar-varuva_medium',
        normal: 'l2u2l1_avar-varuva_normal',
      },
      sentence: {
        bank: ['avar', 'varuva', 'nammaḷ', 'addheham'],
        orders: ['avar varuva'],
        parts: [
          { word: 'avar', meaning: 'they; polite he or she' },
          { word: 'varuva', meaning: 'coming' },
        ],
      },
      notes: ['The safe default when you are not sure who deserves what.'],
      tags: [],
    },
    {
      id: 'thaankal-varunnundo',
      manglish: 'thaankaḷ varunnundo',
      script: 'താങ്കൾ വരുന്നുണ്ടോ',
      meaning: 'are you coming? (very formal)',
      kind: 'sentence',
      audio: {
        slow: 'l2u2l1_thaankal-varunnundo_slow',
        medium: 'l2u2l1_thaankal-varunnundo_medium',
        normal: 'l2u2l1_thaankal-varunnundo_normal',
      },
      sentence: {
        bank: ['thaankaḷ', 'varunnundo', 'nee', 'ningaḷ'],
        orders: ['thaankaḷ varunnundo'],
        parts: [
          { word: 'thaankaḷ', meaning: 'you (very formal)' },
          { word: 'varunnundo', meaning: 'coming?' },
        ],
      },
      notes: ['The question form again: a bare thaankaḷ varuva would read like a command.'],
      tags: [],
    },
    {
      id: 'nee-chaaya-kudikkum',
      manglish: 'nee chaaya kudikkum',
      script: 'നീ ചായ കുടിക്കും',
      meaning: 'you drink tea sometimes',
      kind: 'sentence',
      audio: {
        slow: 'l2u2l1_nee-chaaya-kudikkum_slow',
        medium: 'l2u2l1_nee-chaaya-kudikkum_medium',
        normal: 'l2u2l1_nee-chaaya-kudikkum_normal',
      },
      sentence: {
        bank: ['nee', 'chaaya', 'kudikkum', 'kudikkuva'],
        orders: ['nee chaaya kudikkum'],
        parts: [
          { word: 'nee', meaning: 'you (intimate)' },
          { word: 'chaaya', meaning: 'tea' },
          { word: 'kudikkum', meaning: 'drinks (sometimes)' },
        ],
      },
      notes: ['With nee, the habitual -um reads as a plain statement — only the -uva form commands.'],
      tags: [],
    },
  ],
  minimalPairs: [],
  drills: [
    { kind: 'multipleChoice', itemId: 'ayaal', distractors: ['he, this man', 'he (respectful)', 'they; polite he or she'] },
    { kind: 'multipleChoice', itemId: 'iyaal', distractors: ['he, that man', 'he (respectful)', 'they; polite he or she'] },
    { kind: 'multipleChoice', itemId: 'addheham', distractors: ['he, that man', 'he, this man', 'they; polite he or she'] },
    { kind: 'multipleChoice', itemId: 'avar', distractors: ['he, that man', 'he, this man', 'he (respectful)'] },
    { kind: 'sentenceBuilder', itemId: 'ayaal-varuva', mode: 'bank' },
    { kind: 'sentenceBuilder', itemId: 'iyaal-ready-aanu', mode: 'bank' },
    { kind: 'sentenceBuilder', itemId: 'addheham-varuva', mode: 'bank' },
    { kind: 'sentenceBuilder', itemId: 'avar-varuva', mode: 'bank' },
    { kind: 'sentenceBuilder', itemId: 'thaankal-varunnundo', mode: 'bank' },
    { kind: 'sentenceBuilder', itemId: 'nee-chaaya-kudikkum', mode: 'bank' },
  ],
  reviewSlots: 0,
  spriteId: 'l2u2l1',
};
