import type { Lesson } from '../types';

/**
 * Level 2 Unit 2 Lesson 1 — the third-person ladder (PLAN.md §5): ayaaḷ
 * and iyaaḷ step up from avan, addheham is the respectful form, and avar
 * covers both "they" and polite he-or-she. The formal second person
 * thaankaḷ closes the ladder started in L1U3L1.
 */
export const l2u2l1: Lesson = {
  id: 'l2u2l1',
  levelId: 'l2',
  unitId: 'l2u2',
  title: 'He, she, politely',
  comprehensionOnly: false,
  items: [
    {
      id: 'ayaal',
      manglish: 'ayaaḷ',
      script: 'അയാൾ',
      meaning: 'he, that man',
      kind: 'word',
      pos: 'pronoun',
      audio: {
        slow: 'l2u2l1_ayaal_slow',
        medium: 'l2u2l1_ayaal_medium',
        normal: 'l2u2l1_ayaal_normal',
      },
      acceptedInputs: ['ayaal'],
      notes: ['A step up from avan: polite enough for anyone you do not know well.'],
      tags: [],
    },
    {
      id: 'iyaal',
      manglish: 'iyaaḷ',
      script: 'ഇയാൾ',
      meaning: 'he, this man',
      kind: 'word',
      pos: 'pronoun',
      audio: {
        slow: 'l2u2l1_iyaal_slow',
        medium: 'l2u2l1_iyaal_medium',
        normal: 'l2u2l1_iyaal_normal',
      },
      acceptedInputs: ['iyaal'],
      notes: ['For the man right here, nearby.'],
      tags: [],
    },
    {
      id: 'addheham',
      manglish: 'addheham',
      script: 'അദ്ദേഹം',
      meaning: 'he (respectful)',
      kind: 'word',
      pos: 'pronoun',
      audio: {
        slow: 'l2u2l1_addheham_slow',
        medium: 'l2u2l1_addheham_medium',
        normal: 'l2u2l1_addheham_normal',
      },
      acceptedInputs: ['addheham', 'addeham'],
      notes: ['The respectful he — for elders, bosses, and people you look up to.'],
      tags: [],
    },
    {
      id: 'avar',
      manglish: 'avar',
      script: 'അവർ',
      meaning: 'they; polite he or she',
      kind: 'word',
      pos: 'pronoun',
      audio: {
        slow: 'l2u2l1_avar_slow',
        medium: 'l2u2l1_avar_medium',
        normal: 'l2u2l1_avar_normal',
      },
      acceptedInputs: ['avar'],
      notes: ['Plural on paper, but the everyday polite he-or-she too.'],
      tags: [],
    },
    {
      id: 'ayaal-ingott-varunnundo',
      manglish: 'ayaaḷ ingott varunnundo',
      script: 'അയാൾ ഇങ്ങോട്ട് വരുന്നുണ്ടോ',
      meaning: 'is he coming here?',
      kind: 'sentence',
      audio: {
        slow: 'l2u2l1_ayaal-ingott-varunnundo_slow',
        medium: 'l2u2l1_ayaal-ingott-varunnundo_medium',
        normal: 'l2u2l1_ayaal-ingott-varunnundo_normal',
      },
      sentence: {
        bank: ['ayaaḷ', 'ingott', 'varunnundo', 'avar'],
        orders: ['ayaaḷ ingott varunnundo'],
        parts: [
          { word: 'ayaaḷ', meaning: 'he, that man' },
          { word: 'ingott', meaning: 'to here; this way' },
          { word: 'varunnundo', meaning: 'coming?' },
        ],
      },
      notes: ['The question form with the direction: ingott.'],
      tags: [],
    },
    {
      id: 'addheham-ingott-varunnundo',
      manglish: 'addheham ingott varunnundo',
      script: 'അദ്ദേഹം ഇങ്ങോട്ട് വരുന്നുണ്ടോ',
      meaning: 'is he (respectful) coming here?',
      kind: 'sentence',
      audio: {
        slow: 'l2u2l1_addheham-ingott-varunnundo_slow',
        medium: 'l2u2l1_addheham-ingott-varunnundo_medium',
        normal: 'l2u2l1_addheham-ingott-varunnundo_normal',
      },
      sentence: {
        bank: ['addheham', 'ingott', 'varunnundo', 'ayaaḷ'],
        orders: ['addheham ingott varunnundo'],
        parts: [
          { word: 'addheham', meaning: 'he (respectful)' },
          { word: 'ingott', meaning: 'to here; this way' },
          { word: 'varunnundo', meaning: 'coming?' },
        ],
      },
      notes: ['Same check-in as ayaaḷ — the pronoun does the respect.'],
      tags: [],
    },
    {
      id: 'avar-varunnundo',
      manglish: 'avar varunnundo',
      script: 'അവർ വരുന്നുണ്ടോ',
      meaning: 'are they coming? (polite he or she)',
      kind: 'sentence',
      audio: {
        slow: 'l2u2l1_avar-varunnundo_slow',
        medium: 'l2u2l1_avar-varunnundo_medium',
        normal: 'l2u2l1_avar-varunnundo_normal',
      },
      sentence: {
        bank: ['avar', 'varunnundo', 'nammaḷ', 'addheham'],
        orders: ['avar varunnundo'],
        parts: [
          { word: 'avar', meaning: 'they; polite he or she' },
          { word: 'varunnundo', meaning: 'coming?' },
        ],
      },
      notes: ['The safe question when you are not sure who deserves what.'],
      tags: [],
    },
    {
      id: 'thaankal-varunnundo',
      manglish: 'thaankaḷ varunnundo',
      script: 'താങ്കൾ വരുന്നുണ്ടോ',
      meaning: 'are you coming? (very formal)',
      kind: 'sentence',
      audio: {
        slow: 'l2u2l1_thaankal-varunnundo_slow',
        medium: 'l2u2l1_thaankal-varunnundo_medium',
        normal: 'l2u2l1_thaankal-varunnundo_normal',
      },
      sentence: {
        bank: ['thaankaḷ', 'varunnundo', 'nee', 'ningaḷ'],
        orders: ['thaankaḷ varunnundo'],
        parts: [
          { word: 'thaankaḷ', meaning: 'you (very formal)' },
          { word: 'varunnundo', meaning: 'coming?' },
        ],
      },
      notes: ['The question form again: a bare thaankaḷ varuva would read like a command.'],
      tags: [],
    },
    {
      id: 'nee-chaaya-kudikkumello-alle',
      manglish: 'nee chaaya kudikkumello, alle',
      script: 'നീ ചായ കുടിക്കുമല്ലോ അല്ലേ',
      meaning: 'you drink tea, right?',
      kind: 'sentence',
      audio: {
        slow: 'l2u2l1_nee-chaaya-kudikkumello-alle_slow',
        medium: 'l2u2l1_nee-chaaya-kudikkumello-alle_medium',
        normal: 'l2u2l1_nee-chaaya-kudikkumello-alle_normal',
      },
      sentence: {
        bank: ['nee', 'chaaya', 'kudikkumello,', 'alle', 'kudikkum'],
        orders: ['nee chaaya kudikkumello, alle'],
        parts: [
          { word: 'nee', meaning: 'you (intimate)' },
          { word: 'chaaya', meaning: 'tea' },
          { word: 'kudikkumello,', meaning: 'drinks, as you know' },
          { word: 'alle', meaning: 'right?' },
        ],
      },
      notes: ['The tag form: kudikkumello states it gently, alle asks for the quick yes.'],
      tags: [],
    },
  ],
  minimalPairs: [],
  drills: [
    { kind: 'multipleChoice', itemId: 'ayaal', distractors: ['he, this man', 'he (respectful)', 'they; polite he or she'] },
    { kind: 'multipleChoice', itemId: 'iyaal', distractors: ['he, that man', 'he (respectful)', 'they; polite he or she'] },
    { kind: 'multipleChoice', itemId: 'addheham', distractors: ['he, that man', 'he, this man', 'they; polite he or she'] },
    { kind: 'multipleChoice', itemId: 'avar', distractors: ['he, that man', 'he, this man', 'he (respectful)'] },
    { kind: 'sentenceBuilder', itemId: 'ayaal-ingott-varunnundo', mode: 'bank' },
    { kind: 'sentenceBuilder', itemId: 'addheham-ingott-varunnundo', mode: 'bank' },
    { kind: 'sentenceBuilder', itemId: 'avar-varunnundo', mode: 'bank' },
    { kind: 'sentenceBuilder', itemId: 'thaankal-varunnundo', mode: 'bank' },
    { kind: 'sentenceBuilder', itemId: 'nee-chaaya-kudikkumello-alle', mode: 'bank' },
  ],
  reviewSlots: 0,
  spriteId: 'l2u2l1',
};
