import type { Lesson } from '../types';

/**
 * Level 2 Unit 3 Lesson 1 — the a/i distance paradigm (PLAN.md §5):
 * a-words point away, i-words point near. avide/ivide, ivan/ivaḷ,
 * angane/ingane, appo/ippo — plus njangal, the we that leaves you out.
 */
export const l2u3l1: Lesson = {
  id: 'l2u3l1',
  levelId: 'l2',
  unitId: 'l2u3',
  title: 'Near and far',
  comprehensionOnly: false,
  items: [
    {
      id: 'avide',
      manglish: 'avide',
      script: 'അവിടെ',
      meaning: 'there',
      kind: 'word',
      audio: {
        slow: 'l2u3l1_avide_slow',
        medium: 'l2u3l1_avide_medium',
        normal: 'l2u3l1_avide_normal',
      },
      acceptedInputs: ['avide'],
      notes: ['The a- points away: over there.'],
      tags: [],
    },
    {
      id: 'ivide',
      manglish: 'ivide',
      script: 'ഇവിടെ',
      meaning: 'here',
      kind: 'word',
      audio: {
        slow: 'l2u3l1_ivide_slow',
        medium: 'l2u3l1_ivide_medium',
        normal: 'l2u3l1_ivide_normal',
      },
      acceptedInputs: ['ivide'],
      notes: ['The i- points near: right here.'],
      tags: [],
    },
    {
      id: 'ivan',
      manglish: 'ivan',
      script: 'ഇവൻ',
      meaning: 'he, this one (casual)',
      kind: 'word',
      pos: 'pronoun',
      audio: {
        slow: 'l2u3l1_ivan_slow',
        medium: 'l2u3l1_ivan_medium',
        normal: 'l2u3l1_ivan_normal',
      },
      acceptedInputs: ['ivan'],
      notes: ['The near form of avan: this guy here.'],
      tags: [],
    },
    {
      id: 'ival',
      manglish: 'ivaḷ',
      script: 'ഇവൾ',
      meaning: 'she, this one (casual)',
      kind: 'word',
      pos: 'pronoun',
      audio: {
        slow: 'l2u3l1_ival_slow',
        medium: 'l2u3l1_ival_medium',
        normal: 'l2u3l1_ival_normal',
      },
      acceptedInputs: ['ival'],
      notes: ['The near form of avaḷ: this woman here.'],
      tags: [],
    },
    {
      id: 'angane',
      manglish: 'angane',
      script: 'അങ്ങനെ',
      meaning: 'like that',
      kind: 'word',
      audio: {
        slow: 'l2u3l1_angane_slow',
        medium: 'l2u3l1_angane_medium',
        normal: 'l2u3l1_angane_normal',
      },
      acceptedInputs: ['angane'],
      notes: ['The a- again: that way, like that.'],
      tags: [],
    },
    {
      id: 'ingane',
      manglish: 'ingane',
      script: 'ഇങ്ങനെ',
      meaning: 'like this',
      kind: 'word',
      audio: {
        slow: 'l2u3l1_ingane_slow',
        medium: 'l2u3l1_ingane_medium',
        normal: 'l2u3l1_ingane_normal',
      },
      acceptedInputs: ['ingane'],
      notes: ['The i- form: this way, like this.'],
      tags: [],
    },
    {
      id: 'appo',
      manglish: 'appo',
      script: 'അപ്പോ',
      meaning: 'then; so',
      kind: 'word',
      audio: {
        slow: 'l2u3l1_appo_slow',
        medium: 'l2u3l1_appo_medium',
        normal: 'l2u3l1_appo_normal',
        focus: ['l2u3l1_appo_focus'],
      },
      acceptedInputs: ['appo'],
      articulation: {
        cue: 'Hold the doubled pp.',
      },
      notes: ['Then, so — the far pair of ippo. Hold the doubled pp.'],
      tags: ['sound:geminate'],
    },
    {
      id: 'njangal',
      manglish: 'njangaḷ',
      script: 'ഞങ്ങൾ',
      meaning: 'we (not you)',
      kind: 'word',
      pos: 'pronoun',
      audio: {
        slow: 'l2u3l1_njangal_slow',
        medium: 'l2u3l1_njangal_medium',
        normal: 'l2u3l1_njangal_normal',
      },
      acceptedInputs: ['njangal'],
      notes: ['The exclusive we: us, but not you. Nammal includes you; njangal leaves you out.'],
      tags: [],
    },
    {
      id: 'ninte',
      manglish: 'ninte',
      script: 'നിന്റെ',
      meaning: 'your',
      kind: 'word',
      audio: {
        slow: 'l2u3l1_ninte_slow',
        medium: 'l2u3l1_ninte_medium',
        normal: 'l2u3l1_ninte_normal',
      },
      acceptedInputs: ['ninte'],
      notes: ['Your — the pair of ente (my).'],
      tags: [],
    },
    {
      id: 'avan-avide-und',
      manglish: 'avan avide und',
      script: 'അവൻ അവിടെ ഉണ്ട്',
      meaning: 'he is there',
      kind: 'sentence',
      audio: {
        slow: 'l2u3l1_avan-avide-und_slow',
        medium: 'l2u3l1_avan-avide-und_medium',
        normal: 'l2u3l1_avan-avide-und_normal',
      },
      sentence: {
        bank: ['avan', 'avide', 'und', 'ivide'],
        orders: ['avan avide und'],
        parts: [
          { word: 'avan', meaning: 'he' },
          { word: 'avide', meaning: 'there' },
          { word: 'und', meaning: 'is; there is' },
        ],
      },
      notes: ['The far form in a sentence.'],
      tags: [],
    },
    {
      id: 'njan-ivide-und',
      manglish: 'njan ivide und',
      script: 'ഞാൻ ഇവിടെ ഉണ്ട്',
      meaning: 'I am here',
      kind: 'sentence',
      audio: {
        slow: 'l2u3l1_njan-ivide-und_slow',
        medium: 'l2u3l1_njan-ivide-und_medium',
        normal: 'l2u3l1_njan-ivide-und_normal',
      },
      sentence: {
        bank: ['njan', 'ivide', 'und', 'avide'],
        orders: ['njan ivide und'],
        parts: [
          { word: 'njan', meaning: 'I' },
          { word: 'ivide', meaning: 'here' },
          { word: 'und', meaning: 'is; there is' },
        ],
      },
      notes: ['The near form in a sentence.'],
      tags: [],
    },
    {
      id: 'njangal-pokuva',
      manglish: 'njangaḷ pokuva',
      script: 'ഞങ്ങൾ പോകുവാ',
      meaning: 'we (not you) are going',
      kind: 'sentence',
      audio: {
        slow: 'l2u3l1_njangal-pokuva_slow',
        medium: 'l2u3l1_njangal-pokuva_medium',
        normal: 'l2u3l1_njangal-pokuva_normal',
      },
      sentence: {
        bank: ['njangaḷ', 'pokuva', 'nammaḷ', 'njan'],
        orders: ['njangaḷ pokuva'],
        parts: [
          { word: 'njangaḷ', meaning: 'we (not you)' },
          { word: 'pokuva', meaning: 'going' },
        ],
      },
      notes: ['Said when you are not invited: njangal, not nammaḷ.'],
      tags: [],
    },
  ],
  minimalPairs: [],
  drills: [
    { kind: 'multipleChoice', itemId: 'avide', distractors: ['here', 'like this', 'we (not you)'] },
    { kind: 'multipleChoice', itemId: 'ivide', distractors: ['there', 'like that', 'your'] },
    { kind: 'multipleChoice', itemId: 'ivan', distractors: ['she, this one (casual)', 'there', 'then; so'] },
    { kind: 'multipleChoice', itemId: 'ival', distractors: ['he, this one (casual)', 'here', 'like this'] },
    { kind: 'multipleChoice', itemId: 'angane', distractors: ['like this', 'here', 'then; so'] },
    { kind: 'multipleChoice', itemId: 'ingane', distractors: ['like that', 'there', 'we (not you)'] },
    { kind: 'multipleChoice', itemId: 'appo', distractors: ['here', 'like this', 'your'] },
    { kind: 'multipleChoice', itemId: 'njangal', distractors: ['we (not you) are going', 'here', 'then; so'] },
    { kind: 'multipleChoice', itemId: 'ninte', distractors: ['we (not you)', 'there', 'like that'] },
    { kind: 'sentenceBuilder', itemId: 'avan-avide-und', mode: 'bank' },
    { kind: 'sentenceBuilder', itemId: 'njan-ivide-und', mode: 'bank' },
    { kind: 'sentenceBuilder', itemId: 'njangal-pokuva', mode: 'bank' },
  ],
  reviewSlots: 0,
  spriteId: 'l2u3l1',
};
