import type { Lesson } from '../types';

/**
 * Level 2 Unit 3 Lesson 2 — the question words (PLAN.md §5): entha,
 * etha, engane, enthina, eppozhaa, evide. With engane und and evide
 * covered, these complete the everyday question set.
 */
export const l2u3l2: Lesson = {
  id: 'l2u3l2',
  levelId: 'l2',
  unitId: 'l2u3',
  title: 'Question words',
  comprehensionOnly: false,
  items: [
    {
      id: 'entha',
      manglish: 'entha',
      script: 'എന്താ',
      meaning: 'what',
      kind: 'word',
      audio: {
        slow: 'l2u3l2_entha_slow',
        medium: 'l2u3l2_entha_medium',
        normal: 'l2u3l2_entha_normal',
      },
      acceptedInputs: ['entha'],
      notes: ['The everyday what.'],
      tags: [],
    },
    {
      id: 'etha',
      manglish: 'etha',
      script: 'ഏതാ',
      meaning: 'which',
      kind: 'word',
      audio: {
        slow: 'l2u3l2_etha_slow',
        medium: 'l2u3l2_etha_medium',
        normal: 'l2u3l2_etha_normal',
      },
      acceptedInputs: ['etha'],
      notes: ['Which one.'],
      tags: [],
    },
    {
      id: 'engane-word',
      manglish: 'engane',
      script: 'എങ്ങനെ',
      meaning: 'how',
      kind: 'word',
      audio: {
        slow: 'l2u3l2_engane-word_slow',
        medium: 'l2u3l2_engane-word_medium',
        normal: 'l2u3l2_engane-word_normal',
      },
      acceptedInputs: ['engane'],
      notes: ['How — the question word inside engane und.'],
      tags: [],
    },
    {
      id: 'enthina',
      manglish: 'enthina',
      script: 'എന്തിനാ',
      meaning: 'why',
      kind: 'word',
      audio: {
        slow: 'l2u3l2_enthina_slow',
        medium: 'l2u3l2_enthina_medium',
        normal: 'l2u3l2_enthina_normal',
      },
      acceptedInputs: ['enthina'],
      notes: ['Why — entha plus -ina, what-for.'],
      tags: [],
    },
    {
      id: 'eppozhaa',
      manglish: 'eppozhaa',
      script: 'എപ്പോഴാ',
      meaning: 'when',
      kind: 'word',
      audio: {
        slow: 'l2u3l2_eppozhaa_slow',
        medium: 'l2u3l2_eppozhaa_medium',
        normal: 'l2u3l2_eppozhaa_normal',
      },
      acceptedInputs: ['eppozhaa'],
      notes: ['When — the question form of ippo, now.'],
      tags: [],
    },
    {
      id: 'evide',
      manglish: 'evide',
      script: 'എവിടെ',
      meaning: 'where',
      kind: 'word',
      audio: {
        slow: 'l2u3l2_evide_slow',
        medium: 'l2u3l2_evide_medium',
        normal: 'l2u3l2_evide_normal',
      },
      acceptedInputs: ['evide'],
      notes: ['Where — the question pair of ivide, here.'],
      tags: [],
    },
    {
      id: 'athu-entha',
      manglish: 'athu entha',
      script: 'അത് എന്താ',
      meaning: 'what is that?',
      kind: 'sentence',
      audio: {
        slow: 'l2u3l2_athu-entha_slow',
        medium: 'l2u3l2_athu-entha_medium',
        normal: 'l2u3l2_athu-entha_normal',
      },
      sentence: {
        bank: ['athu', 'entha', 'etha', 'evide'],
        orders: ['athu entha'],
        parts: [
          { word: 'athu', meaning: 'that (thing)' },
          { word: 'entha', meaning: 'what' },
        ],
      },
      notes: ['The pointing question.'],
      tags: [],
    },
    {
      id: 'athu-etha',
      manglish: 'athu etha',
      script: 'അത് ഏതാ',
      meaning: 'which one is that?',
      kind: 'sentence',
      audio: {
        slow: 'l2u3l2_athu-etha_slow',
        medium: 'l2u3l2_athu-etha_medium',
        normal: 'l2u3l2_athu-etha_normal',
      },
      sentence: {
        bank: ['athu', 'etha', 'entha', 'evide'],
        orders: ['athu etha'],
        parts: [
          { word: 'athu', meaning: 'that (thing)' },
          { word: 'etha', meaning: 'which' },
        ],
      },
      notes: ['Choosing between things.'],
      tags: [],
    },
    {
      id: 'ningal-evide',
      manglish: 'ningaḷ evide',
      script: 'നിങ്ങൾ എവിടെ',
      meaning: 'where are you?',
      kind: 'sentence',
      audio: {
        slow: 'l2u3l2_ningal-evide_slow',
        medium: 'l2u3l2_ningal-evide_medium',
        normal: 'l2u3l2_ningal-evide_normal',
      },
      sentence: {
        bank: ['ningaḷ', 'evide', 'avide', 'entha'],
        orders: ['ningaḷ evide'],
        parts: [
          { word: 'ningaḷ', meaning: 'you' },
          { word: 'evide', meaning: 'where' },
        ],
      },
      notes: ['No verb needed: the question word does the asking.'],
      tags: [],
    },
  ],
  minimalPairs: [],
  drills: [
    { kind: 'multipleChoice', itemId: 'entha', distractors: ['which', 'how', 'why'] },
    { kind: 'multipleChoice', itemId: 'etha', distractors: ['what', 'when', 'where'] },
    { kind: 'multipleChoice', itemId: 'engane-word', distractors: ['what', 'when', 'where'] },
    { kind: 'multipleChoice', itemId: 'enthina', distractors: ['what', 'how', 'where'] },
    { kind: 'multipleChoice', itemId: 'eppozhaa', distractors: ['what', 'how', 'why'] },
    { kind: 'multipleChoice', itemId: 'evide', distractors: ['what', 'which', 'why'] },
    { kind: 'sentenceBuilder', itemId: 'athu-entha', mode: 'bank' },
    { kind: 'sentenceBuilder', itemId: 'athu-etha', mode: 'bank' },
    { kind: 'sentenceBuilder', itemId: 'ningal-evide', mode: 'bank' },
  ],
  reviewSlots: 0,
  spriteId: 'l2u3l2',
};
