/**
 * Level 1 Unit 3 — Pronouns (PLAN.md §5). The personal pronouns and the
 * politeness ladder (nee / ningaḷ / thaangkaḷ), plus pro-drop: the reason
 * learners will hear these pronouns far less than textbooks suggest.
 */

import type { Lesson } from '../../types'

export const lesson1Pronouns: Lesson = {
  id: 'l1u3l1',
  levelId: 'level1',
  unitId: 'unit3',
  title: 'Pronouns',
  reviewSlots: 0,
  sprite: { file: 'audio/l1u3l1.mp3' },
  items: [
    {
      id: 'njan',
      manglish: 'njan',
      script: 'ഞാൻ',
      meaning: 'I',
      kind: 'word',
      pos: 'pronoun',
      notes: ['Usually dropped when the meaning is clear: engane und? already means "how are you?" — the njan is understood.'],
      audio: { slow: 'njan.slow', medium: 'njan.medium', normal: 'njan.normal' },
      tags: ['level:1'],
    },
    {
      id: 'nee',
      manglish: 'nee',
      script: 'നീ',
      meaning: 'you (casual)',
      kind: 'word',
      pos: 'pronoun',
      acceptedInputs: ['ni'],
      alsoIn: 'neeyo ("you?") and neeyum ("you too")',
      notes: [
        'For friends and kids. With elders or strangers use ningaḷ or thaangkaḷ.',
        'Also written ni.',
      ],
      audio: { slow: 'nee.slow', medium: 'nee.medium', normal: 'nee.normal' },
      tags: ['level:1'],
    },
    {
      id: 'ningal',
      manglish: 'ningaḷ',
      script: 'നിങ്ങൾ',
      meaning: 'you (polite)',
      kind: 'word',
      pos: 'pronoun',
      acceptedInputs: ['ningal'],
      notes: ['It is the safe choice with anyone you are not close to.'],
      audio: { slow: 'ningal.slow', medium: 'ningal.medium', normal: 'ningal.normal' },
      tags: ['level:1'],
    },
    {
      id: 'thaankal',
      manglish: 'thaangkaḷ',
      script: 'താങ്കൾ',
      meaning: 'you (formal)',
      kind: 'word',
      pos: 'pronoun',
      acceptedInputs: ['thaankal'],
      notes: ['It is very polite, mostly for formal speech and writing.'],
      audio: { slow: 'thaankal.slow', medium: 'thaankal.medium', normal: 'thaankal.normal' },
      tags: ['level:1'],
    },
    {
      id: 'avan',
      manglish: 'avan',
      script: 'അവൻ',
      meaning: 'he',
      kind: 'word',
      pos: 'pronoun',
      audio: { slow: 'avan.slow', medium: 'avan.medium', normal: 'avan.normal' },
      tags: ['level:1'],
    },
    {
      id: 'aval',
      manglish: 'avaḷ',
      script: 'അവൾ',
      meaning: 'she',
      kind: 'word',
      pos: 'pronoun',
      acceptedInputs: ['aval'],
      audio: { slow: 'aval.slow', medium: 'aval.medium', normal: 'aval.normal' },
      tags: ['level:1'],
    },
    {
      id: 'nammal',
      manglish: 'nammaḷ',
      script: 'നമ്മൾ',
      meaning: 'we (you and me)',
      kind: 'word',
      pos: 'pronoun',
      acceptedInputs: ['nammal'],
      notes: ['It includes the person you are talking to.'],
      audio: { slow: 'nammal.slow', medium: 'nammal.medium', normal: 'nammal.normal' },
      tags: ['level:1'],
    },
    {
      id: 'namukku',
      manglish: 'namukku',
      script: 'നമുക്ക്',
      meaning: "to us — also 'let's'",
      kind: 'word',
      pos: 'pronoun',
      notes: ['It is the easy way to suggest something: namukku pokaam, "let.s go".'],
      audio: { slow: 'namukku.slow', medium: 'namukku.medium', normal: 'namukku.normal' },
      tags: ['level:1'],
    },
  ],
  pairs: [],
  drills: [
    { kind: 'multipleChoice', itemId: 'njan', distractors: ['nee', 'avan', 'nammal'] },
    { kind: 'multipleChoice', itemId: 'nee', distractors: ['njan', 'ningal', 'aval'] },
    { kind: 'multipleChoice', itemId: 'ningal', distractors: ['nee', 'thaankal', 'nammal'] },
    { kind: 'multipleChoice', itemId: 'thaankal', distractors: ['ningal', 'njan', 'avan'] },
    { kind: 'multipleChoice', itemId: 'avan', distractors: ['aval', 'njan', 'nee'] },
    { kind: 'multipleChoice', itemId: 'aval', distractors: ['avan', 'nee', 'ningal'] },
    { kind: 'multipleChoice', itemId: 'nammal', distractors: ['namukku', 'njan', 'ningal'] },
    { kind: 'multipleChoice', itemId: 'namukku', distractors: ['nammal', 'nee', 'avan'] },
    { kind: 'typing', itemId: 'njan' },
    { kind: 'typing', itemId: 'nee' },
    { kind: 'typing', itemId: 'avan' },
    { kind: 'typing', itemId: 'nammal' },
  ],
}
