/**
 * Shared audio engine (PLAN.md §6 step 0, §11).
 *
 * One AudioContext for the whole app, unlocked by the first user tap
 * (mobile autoplay policy). iOS silent-switch immunity via
 * `navigator.audioSession.type = 'playback'`. Each lesson's clips live
 * in a single MP3 sprite; `audio-manifest.json` (generated by
 * `npm run audio:gen`, gitignored) maps clip refs like `zha.slow` to
 * [start, duration] offsets inside the sprite.
 *
 * Until audio is generated, the manifest and sprites 404. Every method
 * then reports 'missing' and the lesson player runs silently — there is
 * no runtime TTS and no faked playback.
 */

export type PrepareStatus = 'ready' | 'missing' | 'error'
export type PlayStatus = 'played' | 'missing' | 'locked'

interface SpriteManifest {
  lessons: Record<string, { sprite: string; offsets: Record<string, [number, number]> }>
}

const MANIFEST_URL = '/audio-manifest.json'

type BrowserWindow = Window & { webkitAudioContext?: typeof AudioContext }
type BrowserNavigator = Navigator & { audioSession?: { type: string } }

class AudioEngine {
  private ctx: AudioContext | null = null
  private manifest: SpriteManifest | null = null
  private manifestTried = false
  /** lessonId -> decoded sprite buffer */
  private buffers = new Map<string, AudioBuffer>()
  /** lessonId -> raw sprite bytes, fetched before unlock, decoded lazily */
  private pending = new Map<string, ArrayBuffer>()
  private active = new Set<AudioBufferSourceNode>()

  /** Create/resume the shared AudioContext. Must be called from a user tap. */
  unlock(): void {
    if (!this.ctx) {
      const Ctor = window.AudioContext ?? (window as BrowserWindow).webkitAudioContext
      if (!Ctor) return
      this.ctx = new Ctor()
    }
    if (this.ctx.state === 'suspended') void this.ctx.resume()
    const session = (navigator as BrowserNavigator).audioSession
    if (session) {
      try {
        session.type = 'playback'
      } catch {
        // audioSession is iOS-only; ignore when unavailable
      }
    }
  }

  get isUnlocked(): boolean {
    return this.ctx !== null
  }

  /**
   * Fetch the manifest and the lesson sprite (no AudioContext needed, so
   * availability is known before the start tap). Decoding is deferred to
   * the first play, which happens after unlock.
   */
  async prepareLesson(lessonId: string, spritePath: string): Promise<PrepareStatus> {
    if (!this.manifestTried) {
      this.manifestTried = true
      const res = await fetch(MANIFEST_URL).catch(() => null)
      if (res && res.ok) this.manifest = (await res.json()) as SpriteManifest
    }
    const entry = this.manifest?.lessons[lessonId]
    if (!entry) return 'missing'
    if (this.buffers.has(lessonId) || this.pending.has(lessonId)) return 'ready'
    const res = await fetch(`/${spritePath}`).catch(() => null)
    if (!res || !res.ok) return 'missing'
    this.pending.set(lessonId, await res.arrayBuffer())
    return 'ready'
  }

  /** Play one clip by ref (`zha.slow`). Resolves when the clip ends. */
  async playClip(lessonId: string, ref: string): Promise<PlayStatus> {
    if (!this.ctx) return 'locked'
    if (this.ctx.state === 'suspended') await this.ctx.resume()
    const entry = this.manifest?.lessons[lessonId]
    const offsets = entry?.offsets[ref]
    if (!offsets) return 'missing'
    const buffer = this.buffers.get(lessonId) ?? (await this.decode(lessonId))
    if (!buffer) return 'missing'
    const [start, duration] = offsets
    const source = this.ctx.createBufferSource()
    source.buffer = buffer
    source.connect(this.ctx.destination)
    source.start(0, start, duration > 0 ? duration : undefined)
    this.active.add(source)
    return new Promise((resolve) => {
      source.onended = () => {
        this.active.delete(source)
        resolve('played')
      }
    })
  }

  /** Stop everything currently playing (step changes, navigation). */
  stopAll(): void {
    for (const source of this.active) {
      try {
        source.onended = null
        source.stop()
      } catch {
        // already stopped
      }
    }
    this.active.clear()
  }

  private async decode(lessonId: string): Promise<AudioBuffer | null> {
    const bytes = this.pending.get(lessonId)
    if (!bytes || !this.ctx) return null
    try {
      const buffer = await this.ctx.decodeAudioData(bytes)
      this.pending.delete(lessonId)
      this.buffers.set(lessonId, buffer)
      return buffer
    } catch {
      this.pending.delete(lessonId)
      return null
    }
  }
}

/** App-wide singleton (PLAN.md §6 step 0: one shared AudioContext). */
export const audioEngine = new AudioEngine()
