/**
 * Level 2 Unit 2 — The copula (PLAN.md §5): aanu and aano say what
 * things are; athe, alla, and illa answer yes/no questions. Manglish
 * mixes English words freely, exactly as Kerala does.
 */

import type { Lesson } from '../../types'

export const lesson2Copula: Lesson = {
  id: 'l2u1l2',
  levelId: 'level2',
  unitId: 'unit2',
  title: 'Saying what things are',
  reviewSlots: 2,
  sprite: { file: 'audio/l2u1l2.mp3' },
  items: [
    {
      id: 'aanu',
      manglish: 'aanu',
      script: 'ആണ്',
      meaning: 'is (statement)',
      kind: 'word',
      pos: 'particle',
      notes: ['The linking word: X aanu means "X is".'],
      audio: { slow: 'aanu.slow', medium: 'aanu.medium', normal: 'aanu.normal' },
      tags: ['level:2'],
    },
    {
      id: 'aano',
      manglish: 'aano',
      script: 'ആണോ',
      meaning: 'is it? (question)',
      kind: 'word',
      pos: 'particle',
      notes: ['Turn a statement into a question by swapping aanu for aano.'],
      audio: { slow: 'aano.slow', medium: 'aano.medium', normal: 'aano.normal' },
      tags: ['level:2'],
    },
    {
      id: 'athe',
      manglish: 'athe',
      script: 'അതെ',
      meaning: 'yes (answering a question)',
      kind: 'word',
      pos: 'particle',
      audio: { slow: 'athe.slow', medium: 'athe.medium', normal: 'athe.normal' },
      tags: ['level:2'],
    },
    {
      id: 'illa',
      manglish: 'illa',
      script: 'ഇല്ല',
      meaning: 'no, there is not',
      kind: 'word',
      pos: 'particle',
      audio: { slow: 'illa.slow', medium: 'illa.medium', normal: 'illa.normal' },
      tags: ['level:2'],
    },
    {
      id: 'sheri-aanu',
      manglish: 'sheri aanu',
      script: 'ശെരി ആണ്',
      meaning: "it's fine, it's right",
      kind: 'sentence',
      segments: [
        { token: 'sheri', gloss: 'fine, right' },
        { token: 'aanu', gloss: 'is' },
      ],
      audio: { slow: 'sheri-aanu.slow', medium: 'sheri-aanu.medium', normal: 'sheri-aanu.normal' },
      tags: ['level:2'],
    },
    {
      id: 'njan-ready-aa',
      manglish: 'njaan ready aa',
      meaning: 'I am ready.',
      kind: 'sentence',
      notes: ['No script here: the English word has no settled Malayalam spelling.'],
      segments: [
        { token: 'njaan', gloss: 'I' },
        { token: 'ready', gloss: 'ready' },
        { token: 'aa', gloss: 'am (the linking word)' },
      ],
      audio: { slow: 'njan-ready-aa.slow', medium: 'njan-ready-aa.medium', normal: 'njan-ready-aa.normal' },
      tags: ['level:2'],
    },
    {
      id: 'athu-sheri-aa',
      manglish: 'athu sheri aa',
      script: 'അത് ശെരി ആ',
      meaning: "that's fine, that's right",
      kind: 'sentence',
      segments: [
        { token: 'athu', gloss: 'that' },
        { token: 'sheri', gloss: 'fine, right' },
        { token: 'aa', gloss: 'is' },
      ],
      audio: { slow: 'athu-sheri-aa.slow', medium: 'athu-sheri-aa.medium', normal: 'athu-sheri-aa.normal' },
      tags: ['level:2'],
    },
    {
      id: 'avan-teacher-aa',
      manglish: 'avan teacher aa',
      meaning: 'He is a teacher.',
      kind: 'sentence',
      notes: ['No script here: the English word has no settled Malayalam spelling.'],
      segments: [
        { token: 'avan', gloss: 'he' },
        { token: 'teacher', gloss: 'teacher' },
        { token: 'aa', gloss: 'is' },
      ],
      audio: { slow: 'avan-teacher-aa.slow', medium: 'avan-teacher-aa.medium', normal: 'avan-teacher-aa.normal' },
      tags: ['level:2'],
    },
    {
      id: 'ready-aano',
      manglish: 'ready aano',
      meaning: 'ready? (question form)',
      kind: 'sentence',
      notes: ['No script here: the English word has no settled Malayalam spelling.'],
      segments: [
        { token: 'ready', gloss: 'ready' },
        { token: 'aano', gloss: 'is it?' },
      ],
      audio: { slow: 'ready-aano.slow', medium: 'ready-aano.medium', normal: 'ready-aano.normal' },
      tags: ['level:2'],
    },
    {
      id: 'chaaya-illa',
      manglish: 'chaaya illa',
      script: 'ചായ ഇല്ല',
      meaning: "there's no tea",
      kind: 'sentence',
      segments: [
        { token: 'chaaya', gloss: 'tea' },
        { token: 'illa', gloss: 'there is not' },
      ],
      audio: { slow: 'chaaya-illa.slow', medium: 'chaaya-illa.medium', normal: 'chaaya-illa.normal' },
      tags: ['level:2'],
    },
  ],
  pairs: [],
  drills: [
    { kind: 'multipleChoice', itemId: 'aanu', distractors: ['aano', 'athe', 'illa'] },
    { kind: 'multipleChoice', itemId: 'aano', distractors: ['aanu', 'athe', 'illa'] },
    { kind: 'multipleChoice', itemId: 'athe', distractors: ['aanu', 'aano', 'illa'] },
    { kind: 'multipleChoice', itemId: 'illa', distractors: ['aanu', 'aano', 'athe'] },
    {
      kind: 'sentenceBuilder',
      sentenceId: 'njan-ready-aa',
      bank: ['njaan', 'ready', 'aa'],
      acceptedInputs: ['njaan ready aa'],
    },
    {
      kind: 'sentenceBuilder',
      sentenceId: 'athu-sheri-aa',
      bank: ['athu', 'sheri', 'aa'],
      acceptedInputs: ['athu sheri aa'],
    },
    {
      kind: 'sentenceBuilder',
      sentenceId: 'avan-teacher-aa',
      bank: ['avan', 'teacher', 'aa'],
      acceptedInputs: ['avan teacher aa'],
    },
    {
      kind: 'sentenceBuilder',
      sentenceId: 'ready-aano',
      bank: ['ready', 'aano'],
      acceptedInputs: ['ready aano'],
    },
    {
      kind: 'sentenceBuilder',
      sentenceId: 'chaaya-illa',
      bank: ['chaaya', 'illa'],
      acceptedInputs: ['chaaya illa'],
    },
    { kind: 'typing', itemId: 'sheri-aanu', acceptedInputs: ['sheri aanu'] },
    { kind: 'typing', itemId: 'ready-aano', acceptedInputs: ['ready aano'] },
  ],
}
