/**
 * Level 2 Unit 2 — The copula (PLAN.md §5): aanu and aano say what
 * things are; athe, alla, and illa answer yes/no questions. Manglish
 * mixes English words freely, exactly as Kerala does.
 */

import type { Lesson } from '../../types'

export const lesson2Copula: Lesson = {
  id: 'l2u1l2',
  levelId: 'level2',
  unitId: 'unit2',
  title: 'Saying what things are',
  reviewSlots: 2,
  sprite: { file: 'audio/l2u1l2.mp3' },
  items: [
    {
      id: 'aanu',
      manglish: 'aanu',
      script: 'ആണ്',
      meaning: 'is (statement)',
      kind: 'word',
      pos: 'particle',
      notes: ['The linking word: X aanu means "X is".'],
      audio: { slow: 'aanu.slow', medium: 'aanu.medium', normal: 'aanu.normal' },
      tags: ['level:2'],
    },
    {
      id: 'aano',
      manglish: 'aano',
      script: 'ആണോ',
      meaning: 'is it? (question)',
      kind: 'word',
      pos: 'particle',
      notes: ['Turn a statement into a question by swapping aanu for aano.'],
      audio: { slow: 'aano.slow', medium: 'aano.medium', normal: 'aano.normal' },
      tags: ['level:2'],
    },
    {
      id: 'athe',
      manglish: 'athe',
      script: 'അതെ',
      meaning: 'yes (answering a question)',
      kind: 'word',
      pos: 'particle',
      notes: ['It answers a question that used aano — aano is the question form, aanu is the statement/answer form.'],
      audio: { slow: 'athe.slow', medium: 'athe.medium', normal: 'athe.normal' },
      tags: ['level:2'],
    },
    {
      id: 'illa',
      manglish: 'illa',
      script: 'ഇല്ല',
      meaning: 'no, there is not',
      kind: 'word',
      pos: 'particle',
      audio: { slow: 'illa.slow', medium: 'illa.medium', normal: 'illa.normal' },
      tags: ['level:2'],
    },
    {
      id: 'sheri-aanu',
      manglish: 'sheri aanu',
      script: 'ശെരി ആണ്',
      meaning: "it's fine, it's right",
      kind: 'sentence',
      segments: [
        { token: 'sheri', gloss: 'fine, right' },
        { token: 'aanu', gloss: 'is' },
      ],
      audio: { slow: 'sheri-aanu.slow', medium: 'sheri-aanu.medium', normal: 'sheri-aanu.normal' },
      tags: ['level:2'],
    },
    {
      id: 'njan-ready-aa',
      manglish: 'njan ready aa',
      meaning: 'I am ready.',
      kind: 'sentence',
      notes: ['No script here: the English word has no settled Malayalam spelling.'],
      segments: [
        { token: 'njan', gloss: 'I' },
        { token: 'ready', gloss: 'ready' },
        { token: 'aa', gloss: 'am (the linking word)' },
      ],
      audio: { slow: 'njan-ready-aa.slow', medium: 'njan-ready-aa.medium', normal: 'njan-ready-aa.normal' },
      tags: ['level:2'],
    },
    {
      id: 'njan-okay-aanu',
      manglish: 'njan okay aanu',
      meaning: 'I am fine.',
      kind: 'sentence',
      notes: [
        'The everyday answer to engane und?. Not njan sheri: that means "I correct".',
        'English words are normal in casual sentences: okay, ready, teacher.',
        'No script here: the English word has no settled Malayalam spelling.',
      ],
      segments: [
        { token: 'njan', gloss: 'I' },
        { token: 'okay', gloss: 'okay' },
        { token: 'aanu', gloss: 'is' },
      ],
      audio: { slow: 'njan-okay-aanu.slow', medium: 'njan-okay-aanu.medium', normal: 'njan-okay-aanu.normal' },
      tags: ['level:2'],
    },
    {
      id: 'athu-sheri-aa',
      manglish: 'athu sheri aa',
      script: 'അത് ശെരി ആ',
      meaning: "that's correct",
      kind: 'sentence',
      segments: [
        { token: 'athu', gloss: 'that' },
        { token: 'sheri', gloss: 'correct' },
        { token: 'aa', gloss: 'is' },
      ],
      audio: { slow: 'athu-sheri-aa.slow', medium: 'athu-sheri-aa.medium', normal: 'athu-sheri-aa.normal' },
      tags: ['level:2'],
    },
    {
      id: 'avan-teacher-aa',
      manglish: 'avan oru school teacher aanu',
      meaning: 'He is a school teacher.',
      kind: 'sentence',
      notes: [
        'Copula statements about people take the article oru (a): avan oru teacher aanu.',
        'No script here: the English words have no settled Malayalam spelling.',
      ],
      segments: [
        { token: 'avan', gloss: 'he' },
        { token: 'oru', gloss: 'a (the article)' },
        { token: 'school', gloss: 'school' },
        { token: 'teacher', gloss: 'teacher' },
        { token: 'aanu', gloss: 'is' },
      ],
      audio: { slow: 'avan-teacher-aa.slow', medium: 'avan-teacher-aa.medium', normal: 'avan-teacher-aa.normal' },
      tags: ['level:2'],
    },
    {
      id: 'ready-aano',
      manglish: 'ready aano',
      meaning: 'ready? (question form)',
      kind: 'sentence',
      notes: ['No script here: the English word has no settled Malayalam spelling.'],
      segments: [
        { token: 'ready', gloss: 'ready' },
        { token: 'aano', gloss: 'is it?' },
      ],
      audio: { slow: 'ready-aano.slow', medium: 'ready-aano.medium', normal: 'ready-aano.normal' },
      tags: ['level:2'],
    },
    {
      id: 'chaaya-illa',
      manglish: 'chaaya illa',
      script: 'ചായ ഇല്ല',
      meaning: "there's no tea",
      kind: 'sentence',
      segments: [
        { token: 'chaaya', gloss: 'tea' },
        { token: 'illa', gloss: 'there is not' },
      ],
      audio: { slow: 'chaaya-illa.slow', medium: 'chaaya-illa.medium', normal: 'chaaya-illa.normal' },
      tags: ['level:2'],
    },
    {
      id: 'venam',
      manglish: 'venam',
      script: 'വേണം',
      meaning: 'want, need',
      kind: 'word',
      pos: 'verb',
      notes: ['Wanting takes enikk (to me), never njan.'],
      audio: { slow: 'venam.slow', medium: 'venam.medium', normal: 'venam.normal' },
      tags: ['level:2'],
    },
    {
      id: 'enikk-chaaya-venam',
      manglish: 'enikk chaaya venam',
      script: 'എനിക്ക് ചായ വേണം',
      meaning: 'I want tea',
      kind: 'sentence',
      notes: ['The dative: enikk (to me) chaaya venam (tea is wanted).'],
      segments: [
        { token: 'enikk', gloss: 'to me' },
        { token: 'chaaya', gloss: 'tea' },
        { token: 'venam', gloss: 'want' },
      ],
      audio: { slow: 'enikk-chaaya-venam.slow', medium: 'enikk-chaaya-venam.medium', normal: 'enikk-chaaya-venam.normal' },
      tags: ['level:2'],
    },
    {
      id: 'avan-varunnundo',
      manglish: 'avan varunnundo',
      script: 'അവൻ വരുന്നുണ്ടോ',
      meaning: 'is he coming?',
      kind: 'sentence',
      acceptedInputs: ['avan varunundo'],
      segments: [
        { token: 'avan', gloss: 'he' },
        { token: 'varunnundo', gloss: 'is coming?' },
      ],
      audio: { slow: 'avan-varunnundo.slow', medium: 'avan-varunnundo.medium', normal: 'avan-varunnundo.normal' },
      tags: ['level:2'],
    },
  ],
  pairs: [],
  drills: [
    { kind: 'multipleChoice', itemId: 'aanu', distractors: ['aano', 'athe', 'illa'] },
    { kind: 'multipleChoice', itemId: 'aano', distractors: ['aanu', 'athe', 'illa'] },
    { kind: 'multipleChoice', itemId: 'athe', distractors: ['aanu', 'aano', 'illa'] },
    { kind: 'multipleChoice', itemId: 'illa', distractors: ['aanu', 'aano', 'athe'] },
    {
      kind: 'sentenceBuilder',
      sentenceId: 'njan-ready-aa',
      bank: ['njan', 'ready', 'aa'],
      acceptedInputs: ['njan ready aa'],
    },
    {
      kind: 'sentenceBuilder',
      sentenceId: 'athu-sheri-aa',
      bank: ['athu', 'sheri', 'aa'],
      acceptedInputs: ['athu sheri aa'],
    },
    {
      kind: 'sentenceBuilder',
      sentenceId: 'avan-teacher-aa',
      bank: ['avan', 'oru', 'school', 'teacher', 'aanu'],
      acceptedInputs: ['avan oru school teacher aanu'],
    },
    {
      kind: 'sentenceBuilder',
      sentenceId: 'ready-aano',
      bank: ['ready', 'aano'],
      acceptedInputs: ['ready aano'],
    },
    {
      kind: 'sentenceBuilder',
      sentenceId: 'chaaya-illa',
      bank: ['chaaya', 'illa'],
      acceptedInputs: ['chaaya illa'],
    },
    { kind: 'multipleChoice', itemId: 'venam', distractors: ['aanu', 'aano', 'illa'] },
    { kind: 'multipleChoice', itemId: 'njan-okay-aanu', distractors: ['njan-ready-aa', 'sheri-aanu', 'avan-teacher-aa'] },
    { kind: 'multipleChoice', itemId: 'avan-varunnundo', distractors: ['enikk-chaaya-venam', 'ready-aano', 'chaaya-illa'] },
    {
      kind: 'sentenceBuilder',
      sentenceId: 'njan-okay-aanu',
      bank: ['njan', 'okay', 'aanu'],
      acceptedInputs: ['njan okay aanu'],
    },
    {
      kind: 'sentenceBuilder',
      sentenceId: 'enikk-chaaya-venam',
      bank: ['enikk', 'chaaya', 'venam'],
      acceptedInputs: ['enikk chaaya venam'],
    },
    {
      kind: 'sentenceBuilder',
      sentenceId: 'avan-varunnundo',
      bank: ['avan', 'varunnundo'],
      acceptedInputs: ['avan varunundo'],
    },
    { kind: 'typing', itemId: 'sheri-aanu', acceptedInputs: ['sheri aanu'] },
    { kind: 'typing', itemId: 'ready-aano', acceptedInputs: ['ready aano'] },
  ],
}
